### ISSUE TITLE
QDirStat registers as standard file viewer in gnome3

### ISSUE THREAD

**Issue by mslacken** [shundhammer/qdirstat#115]
On leap 15.1 the qdirstat rpm registers itself as standard application for files. So if one opens the Places dialog, qdirstat is shown and not nautilus.
Version used:
qdirstat-1.5.90+git.b0d877d-lp151.33.1.x86_64

**Comment by shundhammer** [comment]
QDirStat registers itself for
```ini
MimeType=inode/directory;inode/mount-point;
```

https://github.com/shundhammer/qdirstat/blob/master/src/qdirstat.desktop
```ini
[Desktop Entry]
Type=Application
Name=QDirStat
Exec=qdirstat %f
Icon=qdirstat
GenericName=QDirStat Directory Statistics
Terminal=false
MimeType=inode/directory;inode/mount-point;
Categories=Qt;System;Filesystem;
Keywords=directory;tree;size;statistic;disk;space;
```

...which is perfectly correct. It means that it is one application that can handle directories and mount points. If your desktop thinks it doesn't have any other application for that, that's the fault of the desktop, not of an application that can handle those MIME types.

I don't use GNOME (happy Xfce user here), but AFAIK you can set the standard application for certain things, including which web browser you prefer -- and which file manager. So please check your desktop settings. This might be a shortcut to get there:

```bash
exo-preferred-applications
```
![exo-pref-01](https://user-images.githubusercontent.com/11538225/61745762-85a0fd80-ad9a-11e9-872c-85b20763c489.png)

![exo-pref-02](https://user-images.githubusercontent.com/11538225/61745773-8c2f7500-ad9a-11e9-8db6-e1397975cebe.png)

QDirStat isn't even in that list on my machine.

**Comment by shundhammer** [comment]
See also

http://forums.mozillazine.org/viewtopic.php?f=38&t=3038130

**Comment by shundhammer** [comment]
Also check _Settings_ -> _MIME types_ what application your desktop wants to use for MIME type _inode/directory_.

**Comment by shundhammer** [comment]
Come to think of it, this might happen if you ever used "Open with other application" from the context menu in a file manager and then by accident clicked the "always use this application for this MIME type" check box.

**Comment by mslacken** [comment]
I would say Qdirstat should not have a mime-type at all, as the micromanagement of directories and mount poins is not its intended use.
You could also say, that gnome3 should not use every new mime-type as the new default one, but this is another story...

**Comment by shundhammer** [comment]
> I would say Qdirstat should not have a mime-type at all, as the micromanagement of directories and mount poins is not its intended use.

Yes, of course. It's not only about "micromanagement", it's about "doing something useful with that MIME type". Look what other applications I get for MIME type inode/directory:

![open-with](https://user-images.githubusercontent.com/11538225/61776852-2673d500-adfc-11e9-91cd-98fc2e597fe7.png)

There are other file managers, but there is also _Gwenview_, the image viewer, because you might want to use its integrated image browser in that directory. Then there is _Kid3-qt_ because you might want to edit the ID3 tags of all MP3 clips in that directory. None of those applications can or wants to be a replacement for a file manager where you can do all kinds of file manager operations; but they all do _something_ on the directory level.

Along similar lines, QDirStat does something useful with directories, and I daresay that it's even a lot closer to file manager semantics than those others.

Not registering that MIME type would mean that you couldn't easily use QDirStat with "Open with..." from a context menu. As a matter of fact, it was demanded from me by desktop people (!) on several occasions that QDirStat should register itself for that MIME type (both by GNOME and by KDE people).

**Comment by mslacken** [comment]
So this more a bug on the gnome3 side, so closing this is/was the right thing.
