### ISSUE TITLE
Directory structure breaks when manipulating it during scanning

### ISSUE THREAD

**Issue by raboof** [shundhammer/qdirstat#137]
To me, one of the big advantages of qdirstat is that you can start using it while scanning is still in progress.

The way I usually use it is by sorting on 'size' and browsing the hierarchy.

Unfortunately, it seems this recently(?) broke: I suspect after reordering due to updated information from the scanner, directories are shown under the wrong parent.

After scanning is complete everything is refreshed and looks OK again, so it seems like just a presentation issue.

I've reproduced the issue with 1.6.1 and b6c2a1f5ec8b8d65e1e43157bcb71e8661eca185, can bisect further later.

**Comment by shundhammer** [comment]
Early on when I ported QDirStat from the old KDE 3 KDirStat, I had left interactive sorting enabled even during reading directories, and the initial sort order was by read jobs (displayed in the percentage bar column). But that turned out to confuse the hell out of Qt's underlying model/view classes: There is no way to tell them that the sort order just changed because of updated fields, be it the number of pending read jobs or the total size.

Worse, if a user opens a branch that is still being read, any reordering caused the effect you just described; so I had to disable opening those branches until that directory was finished reading.

Maybe that disabling was not thorough enough; maybe you found a way to work around that.

But if you start merrily changing things while reading a directory branch is not finished, basically anything can happen; a typical symptom is the directory structure becoming apparently broken (as you observed) because the underlying QTreeView widget is not properly notified about changes.

Doing that properly is not realistically possible with all the ivory-tower logic (straight from the textbook of some computer science professor who never did any real programming) the Trolls put into those model/view classes; when they use them for their widgets, they constantly cheat their way around those restrictions by misusing internal private classes.

So, what exactly are you doing when that happens?

**Comment by shundhammer** [comment]
See also https://github.com/shundhammer/qdirstat/issues/24.

**Comment by shundhammer** [comment]
Actually, this looks very much like a duplicate of #24.

**Comment by raboof** [comment]
Agreed this is a duplicate of #24.

**Comment by shundhammer** [comment]
Okay, in that case I fear there is nothing that I can do short of disabling any user interaction whatsoever as long as reading directories is in progress.

**Comment by zmiimz** [comment]
Updating the structure during scan once per 30 s would be good enough for the user and not critical for the performance of qdirstat

**Comment by shundhammer** [comment]
A normal scan doesn't even take 30 seconds.

**Comment by zmiimz** [comment]
Yep. The average temperature in the hospital is 36.6 C. In a morgue +4, and in the department of infectious diseases 41 degrees.
