### ISSUE TITLE
Compare disk snapshots

### ISSUE THREAD

**Issue by stdedos** [shundhammer/qdirstat#139]
Given two disk cache files (or a current scan and a file), is it possible to compare them?

I am thinking of having a "stable state" saved and a state that the disk size is changed unfavorably, but it is not clearly seen who is responsible (or if _every folder_ was more or less responsible).

**Comment by shundhammer** [comment]
I don't see a reasonable way to do this.

I have been thinking about something similar since a long time ago: I am interested how the disk space changes over time. When I start cleaning up my disk, I want to see the status before and after; preferably over multiple program invocations.

Using cache files would be one way to implement this, so your question goes into the same general direction.

Basically, this comes down to visualizing a diff between two trees; the compared value would be the _total size_ of each branch.

This sounds easy as long as only the sizes differ, but the tree elements / branches are the same in both trees: Display a plus/minus bar in green or red for the size difference in each branch; something like this (just colored):

```
  mydir1    [    ===|    ]    760 GB  (-123 GB)
  mydir2    [       |====]    420 GB  (+307 GB)
```

That nice visualization might fall apart when whole branches are missing in either tree A or tree B.

Maybe it would be an option to emulate existing diff tools (KDE _kompare_, _mgdiff_, the GitHub diff viewer) comes to mind: Display deleted branches in red / with a red background and new branches in green / with a green background.

**Comment by shundhammer** [comment]
As for comparing cache files, a simple approach might be:

- Generate them with the `-l` option (in long format)
- Strip off all fields except type, name with path, size
- Ensure sorting
- Maybe normalize whitespace (replace all sequences of blanks and tabs with a single blank)
- Invoke a normal `diff -u`

That might be possible with a moderately complex shell script (or Perl, Ruby or Python script).

One weakness is that the directory lines contain only the size of the directory node itself, not the accumulated sum of the subtree.

**Comment by shundhammer** [comment]
Let me think about this some more.

**Comment by shundhammer** [comment]
For a shellscript-based solution, it's much simpler to use the `du` command since it only contains directories by default, and it always shows accumulated sizes for each, and you can tell it to use the same size unit for each line which makes further processing much simpler, such as a numeric sort and using only the top 20 largest subtrees:

```
# du -k `pwd` | sort -nr | head -n 20
173660	/work/home/sh/src/qdirstat
144208	/work/home/sh/src/qdirstat/src
109796	/work/home/sh/src/qdirstat/src/.obj
21292	/work/home/sh/src/qdirstat/.git
21016	/work/home/sh/src/qdirstat/.git/objects
18592	/work/home/sh/src/qdirstat/.git/objects/pack
7488	/work/home/sh/src/qdirstat/screenshots
400	/work/home/sh/src/qdirstat/src/.moc
300	/work/home/sh/src/qdirstat/doc
244	/work/home/sh/src/qdirstat/src/icons
92	/work/home/sh/src/qdirstat/scripts
84	/work/home/sh/src/qdirstat/.git/objects/d3
84	/work/home/sh/src/qdirstat/doc/stats
76	/work/home/sh/src/qdirstat/.git/objects/9f
60	/work/home/sh/src/qdirstat/src/icons/tree-small
60	/work/home/sh/src/qdirstat/src/icons/tree-medium
52	/work/home/sh/src/qdirstat/man
48	/work/home/sh/src/qdirstat/.git/objects/30
48	/work/home/sh/src/qdirstat/.git/logs
44	/work/home/sh/src/qdirstat/test
```

One interesting parameter is `-S` (`--separate-dirs`) which makes the size exclude the size of subdirectories, i.e. only the files directly on that directory level are taken into account:

```
# du -kS `pwd` | sort -nr | head -n 20
109796	/work/home/sh/src/qdirstat/src/.obj
33768	/work/home/sh/src/qdirstat/src
18592	/work/home/sh/src/qdirstat/.git/objects/pack
7488	/work/home/sh/src/qdirstat/screenshots
400	/work/home/sh/src/qdirstat/src/.moc
216	/work/home/sh/src/qdirstat/doc
144	/work/home/sh/src/qdirstat
124	/work/home/sh/src/qdirstat/src/icons
124	/work/home/sh/src/qdirstat/.git
84	/work/home/sh/src/qdirstat/.git/objects/d3
84	/work/home/sh/src/qdirstat/doc/stats
76	/work/home/sh/src/qdirstat/.git/objects/9f
60	/work/home/sh/src/qdirstat/src/icons/tree-small
60	/work/home/sh/src/qdirstat/src/icons/tree-medium
52	/work/home/sh/src/qdirstat/man
48	/work/home/sh/src/qdirstat/scripts
48	/work/home/sh/src/qdirstat/.git/objects/30
44	/work/home/sh/src/qdirstat/scripts/pkg-tools
44	/work/home/sh/src/qdirstat/.git/objects/bf
44	/work/home/sh/src/qdirstat/.git/objects/60
```

This shows the individual directories somewhere in that subtree that consume the most disk space.

**Comment by shundhammer** [comment]
As much as I'd like to have a GUI based comparison between the current state and one or more old states, this brings a couple of problems:

## Saving an Old State

Against what old state should the current state be compared? How and when would that old state be generated?

For you personally, you can easily make that decision and set up the necessary infrastructure: E.g. a cron job running once per day or every few hours that creates a cache file. Of course you want to do that as a batch job without any GUI. You certainly don't want to invoke QDirStat manually for that and click around to generate that old state.

For a user invoking QDirStat only now and then and not caring about setting up anything like that, this approach would not work at all. Even if QDirStat would implicitly write the current tree to disk for later use, that would be pointless if the user invokes QDirStat only every few weeks; or, worse, when disk space is getting scarce, several times a day to check what can be cleaned up. When would be a good time to save an old status? It's hard to tell; it depends on how that user works, if he is using QDirStat to clean up, or maybe just to check the used disk space and then uses other tools.

Typically, browser caches eat up a lot of disk space; something like 500 MB per browser (and if you use multiple browsers in parallel like Chrome, Firefox and Opera, and also Thunderbird for mail, this tends to multiply). To clean up that disk space, it's best to use the browsers built-in functions ("clear browser data"). That is outside of QDirStat, so a user would either restart QDirStat or just refresh its data.

When would be a good time to write a new old state? Once daily, when QDirStat is invoked first on that day? When that subtree has become smaller?

  As a user, I know when I start cleaning up; I would be interested to know how efficient my cleaning up was. I want to compare the status _after_ the cleanup against what I started out with. When my home directory has grown to 1.8 GB again, I start clearing browser caches, the image thumbnail cache and all that cruft that all those programs leave behind. I may start compacting git checkouts. I may invoke `make clean` or `git clean -dfx` for old checkouts that I don't currently work on.

  But when I compare, I want to compare after each step against the initial size to see the overall result of my work: Was my cleaning any efficient?

**Comment by shundhammer** [comment]
## Presenting a Diff

If there is only one saved state, another tree column would be sufficient; or maybe two? The current size, the old size, and/or the difference between them? Probably the difference to avoid confusion which size is which:

```
/work/src/qdirstat    169.6 MB  +24 MB
```

If there are multiple old states, it would become much more difficult: Let the user choose one to compare against? (How?)

Or present them all time-based, e.g. like this:

```
/work/src/qdirstat    169.6 MB  +24 MB  +15 MB  +12 MB
```

```
/work/src/qdirstat    169.6 MB  +12 MB  +15 MB  +24 MB
```

This would need much more information on the screen describing what each value is; as shown in this example, just raw numbers are not giving away any useful information: Is it +24 MB against yesterday, +15 MB against 20 minutes ago when I started cleaning up, +12 MB just now?

This is probably not very useful.

**Comment by shundhammer** [comment]
## Technical Considerations

Dealing with multiple directory trees to compare against makes handling internally in the QDirStat code _much_ more complicated. Right now it has one of them, and the views (the tree view and the treemap) only have to deal with that one.

When there are multiple of them, every action would need to specify which one to use, and the model class of the tree view would have to handle all of them for the comparison.

It's not as simple as adding one or more fields to each item in the tree: They need to be read in succession, probably the current one first (from disk with `opendir()`, `readdir()`, `stat()`), then the old one (from a cache file), then they would need to be compared against each other to find the diff.

That comparison would have to use paths to find the matching counterpart in the other tree which is already quite an expensive operation; performance would suffer, and of course the memory footprint as well.

**Comment by shundhammer** [comment]
## New and Deleted Tree Branches

It's not only the sizes that will be different between the current and an old tree: There might be any number of new branches in the current tree that did not exist in the old one, and there might be any number of deleted branches that existed in the old tree, but that no longer exist in the current one.

Handling that properly would not only be a technical challenge, it would also be difficult to visualize so a normal user can make sense of it.

A new branch could be considered as having an old size of 0; that is simple. But a deleted branch would not even exist in the current tree, so there isn't any place to present the information that there was this old branch that consumed x MB disk space. So that information would be silently ignored, or the old branch would still have to be shown in the current tree, but with a different visual representation; dimmed out like the <ignored> branches in the "Unpackaged Files" view? In red text color or with red background like in diff tools like `gitk`, KDE `kompare` or `mgdiff`?

This screams "attention grabbing information overload" at me. So this could and should not be a default for QDirStat, it would need to be a completely different view for advanced users; a view to be started only upon explicit request from the menu.

**Comment by shundhammer** [comment]
## Verdict

I don't think this would be anywhere near useful enough to warrant the hassle and the added UI complexity.

Not only would this be a considerable amount of work for the implementation, it would also raise the internal complexity of the code a notch or two; this in turn means increasing the technical debt considerably. And I don't see much value in return.

Feature creep is a real danger in software projects; once they are feature-complete in their original intended use, more and more stuff is added because someone thinks it might be useful. But here is where invariably the law of diminishing return sets in, and sometimes the overall value even decreases: The software becomes more complex, thus less stable and more difficult to maintain. The user interface also becomes more complex, making it more difficult for the average user to figure out how to use it.

A case in point are new views added after QDirStat reached the feature set of the old KDirStat:

- File type view
- File size distribution histogram
- Packages view
- Unpackaged files view

I have not received _any_ feedback about _any_ of them other than from the one user requesting the "file type" view. 

Are those features used at all? Are they useful to the average user? Are they useful to _anyone_? I don't know. Nobody seems to give a damn about any of them; at least not enough to write any kind of feedback (even though I opened up a GitHub issue for each of them to discuss them; no reply at all).

Not even those dozens of bloggers who blog about QDirStat even notice that they exist. They typically write a lot of text how to install it for their favourite Linux distribution (which is simple because they can copy & paste the text from a dozen similar old articles), they add a screenshot of the main window, they describe how to move a file to the trash bin and how to delete a file directly (and some wiseass in the comments always recommends to make a complete backup of the system before deleting anything); and that's it. They never even realize that those other features even exist, much less bother to explain how and when to use them (yet they all ask for a donation for the great job they are doing in describing the obvious).

Are other users different in that regard? I don't know; but I have doubts.

**Comment by shundhammer** [comment]
## Workaround

What I usually do when I realize that I need to clean up: I start QDirStat for that directory and leave it open for reference. Don't hit "refresh" in that window! Just leave it sitting there.

Then I start another instance and start cleaning up. Or, when it's the home directory and I see that all those browsers dumped a Gigabyte of garbage into the `~/.cache` directory again, I start them all in turn, clear their caches, and _then_ start a new QDirStat instance and continue cleaning up little stuff. All the while I can compare the numbers with the other QDirStat window.

Yes, this is a low-tech solution. But it's simple, and it works. :smiley:

**Comment by stdedos** [comment]
You have very elaborate and in-depth description of all aspects, and I cannot possibly try to argue with that in whole: You have internal code knowledge, have been running this project for ages, and you have overview of what people have been asking all this time. I'll pick up the points / general topics I have some answers / ideas to present:

## For the "old not existing dir anymore":
Collapse its size to the parent. Then, if the user expands the parent, create a 0-size counterpart on the new side, and present it like this (similarly to your idea of "new not existing in old scan").

## For the "duplicating UI code on both sides":
Don't do it. The only view that should "try" to be interactive, is the live one (if you are comparing snapshot-to-live). Except, of course, the collapse/expand interactive-ness. _If_ you want, maybe allow us to _try_ and call "Open File" and "Open Parent Directory" in any case.
In the text-diff, you _have_ everything needed to switch between states. In cache files, _you just have a photograph_ of what happened. You can play pretend, but ... that's it. It doesn't change anything.

## For the feature-creep:
File types: I've never used it. It usually does not make sense to me what are they - I care more "where is something", "does it make sense to be there" (i.e. will I find it if I don't know its name/path by following clues?), "is it duplicated / very old / not useful".

File Size statistics, on the other hand, sounds (and looks) potentially very interesting (and a learning opportunity).
However ... what does that tell me?
![image](https://user-images.githubusercontent.com/133706/86476022-6783a180-bd4e-11ea-9bc1-33be77d7688b.png)

The GUI overview is infinitely much more useful on how my drive looks like. (Unless I am comparing apples to oranges.)

![image](https://user-images.githubusercontent.com/133706/86476177-b2051e00-bd4e-11ea-9870-342d1d21f3af.png)

That I can read more easily, but still requires effort (and ofc I need know what am I looking for).

![image](https://user-images.githubusercontent.com/133706/86476480-4d968e80-bd4f-11ea-8cf9-38ec7d72adb2.png)

I am totally lost. So, the 100th bucket contains 638 50.5kb - 51.0kb files. Okay.
But, there is no bucket for my 16GB files? They do not matter / are not counted anywhere? 😕

The latest feature you've added made much more sense to me - real vs allocated size for <4kb files. _Maybe, somehow,_ I can use this information to make more educated guesses about which directories are putting "more strain" on my storage space. But then, what do I do to solve these issues? _Which are those issues?_
Should I re-partition a portion of that partition (or the whole partition) with smaller block sizes? Should I switch to BTRFS? I think you said it has a feature that bundles small files in one "partition block", thus "amending the situation (_what_ situation)"? Is _the situation(s)_ so big, that it's worth to do all of that?

(Un)Packages view:
I'd like to spin them more thoroughly sometime when I have the time to afford.

* I feel that Packages view is something like the Windows' "Installed Programs". It made sense when drive sizes were scarce, so you'd look for the big & old offenders. Nowadays ... meh. For people that "size matters", I am thinking some embedded scenarios, but that "in some parallel" it can be compared to a docker image size: There are ways to already see what each package is bringing in.

* I could check the Unpackaged view, but ... what will I do with that? I'll learn, _sometime_, to be more careful with what I install, cleanup, ... but then, it comes down to 3 things:
  * Size (discussed)
  * "Be more careful": sometimes, you _just need_ something, and it's not packaged for you. Which brings me to:
  * Packaging. If upstream is not packaging for you (... a random example, qdirstat 😝), then, you need to learn to do it yourself. So far, I have not been _that_ successful (but then again, maybe I haven't tried hard enough). And, even if I build my boilerplate-packaging files/magic ... then what? Once packaged, `dpkg` "magically" finds everything / matches everything, or do I still need to iteratively tie up loose ends?

All that being said ... Usually, silence about a feature it's not a holistic indicator of liking it or not.
Why would you expect that _every tutorial out there_ would mention e.g. File Size Statistics? Compared to "the"
qdirstat, this is a very niche feature. It will give some "omg YES thank you for existing" (maybe much more than _some_), but that's it.

To me, the _definite_ indicator of something being "good or not": remove/change it drastically. Ask me how many times I've complained and boiled with anger when someone decided "the new UI is _so much better_", without giving me the option of switching back. Sometimes, even to things I am directly (or indirectly) paying for. While I hate it in any case, in Freeware/Open Source, I just treat me with "If you _really don't like it and you need it_, why don't you fix it yourself" (I have about 20-30 projects like that on my disk. Managed to start 1.25 of them so far).

All that being said (v2), if a feature somehow live independently (and maybe only use a common data source), then maybe it's not that complex to keep it around / sustain it. I don't care about it, _you maybe don't_ but someone may find it useful somewhere down the road.

------

Apologies for blabbering. It started feeling like a forum / ground for discussion, and I've taken it.
