### ISSUE TITLE
Feature request: columns for all time stamps

### ISSUE THREAD

**Issue by talbym** [shundhammer/qdirstat#143]
Great tool, thanks a lot for sharing it, really appreciated!
It would be very helpful if more time stamps and dates could be shown:
created, modified, accessed
oldest file, newest file, oldest dir, newest dir

Imagine this case in a scientific laboratory: I need to move data from a server to an offline storage. In principal there is no need to enlarge the server and to thus also enlarge the burden of making daily backups of it, because data which is no more in use could be moved offline. Now, which is the big and old data to take off from the server first? qdirstat perfectly finds the big data, but more complete time information would answer if there is still someone actively using this data. Maybe it is from a science project which since years is abandoned and could be moved to an offline archive? Maybe it is very old and very big data, but still in use?

**Comment by shundhammer** [comment]
## Oldest File

An "Oldest File" column is already there (but not visible by default; use the context menu in the header to enable it):


![QDirStat-oldest-file](https://user-images.githubusercontent.com/11538225/62321447-f1721d00-b4a2-11e9-905e-713b771ab5f5.png)

For more details, see [issue 118](https://github.com/shundhammer/qdirstat/issues/118).

Notice this is strictly about the oldest _file_ in each subtree, disregarding directory timestamps.

**Comment by shundhammer** [comment]
## Modify time

QDirStat shows the "Last Modified" column by default (in Layouts L2 and L3). Unlike the "Oldest File" column, that includes directories; so you can see where any "traffic" was lately, i.e. where a user created or deleted a file (or just moved or renamed one). That information trickles up the hierarchy, so you can work your way downwards in the tree to see what directories were busy or idle lately.


## Other Timestamps

ctime (creation time) and atime (access time) are generally absolutely useless; atime in particular. atime changes whenever any process reads a file or directory for whatever reason. That happens all the time: Users invoking a `find` command or `grep -R` or even just `file`:

```
find /mytree -name "*foo*.cpp"

grep -Ri "*foo*" .

file *
```

A `find` command changes the atime of every directory in that subtree, `grep` and `file` read the atime of every file they check.

It would be a very lonely subtree that wasn't touched by any of these for long enough to make that column worthwhile to be displayed in QDirStat; you will find that you can't really make any sense of that information.

### ctime

ctime is so weird that I often wondered why it even exists. It is little different from mtime. In theory, it would tell you the original age of a file. But that doesn't really ever work out in real life. Consider this:

```
rm -f myfile.txt    # just making sure it really doesn't exist
vi myfile.txt       # create it - this is what you expect its ctime to be
```
...time passes...
...more time passes...

```
vi myfile.txt       # just do some editing
```

If ctime made any sense, the last command would not have changed it, right? After all, we only modified an existing file, so by rights it should have retained its original ctime.

But no, its ctime changed along with the mtime. Why? Because almost _all_ software never just opens a time for modification and writes it; no, they rename the old file, create a new one, write content to the new file and then remove the old file. Editors of any kind (vi, Emacs, ...) all do that.

Other software that handles binary files also does that in the vast majority of cases; after all, that's a standard best practice: If anything goes wrong during writing (e.g. disk full), you still have the old version intact, you are only missing your most recent changes. You never lose the complete content.

What you lose, though, is a meaningful ctime: Because it's a new file with a new i-node, it gets a new ctime. So basically ctime almost always is the same as mtime; except for directories. A directory retains its time of creation because it is always just opened for modification (by the kernel with the appropriate system calls).

**Comment by shundhammer** [comment]
Bottom line: The useful timestamps are already there in QDirStat; the ones it doesn't display are not helpful for any real-world problem.

**Comment by shundhammer** [comment]
For your particular use case, consider using network storage (NFS, Samba) and the automounter. If you suspect that certain directory trees are not in active use anymore, move them to a network mount; you might then even be able to check logs (NFS client side or NFS server side) about mount times.

Unfortunately, bcache does not support NFS (since NFS is not a block device, and bcache only supports block devices), so would not help you there; but maybe take that as a general hint to check if there is anything out there to make using a network mount less painful for your users.

**Comment by shundhammer** [comment]
I would have expected at least _some_ response with all the time I spent here explaining things.
