### ISSUE TITLE
Feature request "number of subdirectories" and "number of subfiles" metrics?

### ISSUE THREAD

**Issue by lockywolf** [shundhammer/qdirstat#146]
Firstly, thank you for an excellent tool!

I would like to, if possible, as for the following features:

1. Instead of adding up file sizes (or allocated file sizes), add up 1 (literal numeric 1) per found descendant file. This way, on the map, the largest directories will not be the ones with the "heaviest" contents, but with the largest _number_ of files. This is very useful when identifying bogus directories with "lots of empty files", which are otherwise invisible to the computer owner willing to do a cleanup.
2. Instead of adding up file sizes (or allocated file sizes), add up 1 (literal numeric 1) per found (sub-^n)directory. This way qdirstat could help identifying bogus subfolders that have the actual weight of 0, but stress the file system structure. 

Thank you for your consideration.

**Comment by shundhammer** [comment]
How is that different from the "Files" and "Subdirs" columns?

![QDirStat-L2](https://user-images.githubusercontent.com/11538225/98685697-fb522380-2367-11eb-9cbd-bd7f686e2463.png)

**Comment by lockywolf** [comment]
It's not!

It's just that I didn't find how to switch the "treemap" and "subtree percentage" to these metrics.

**Comment by shundhammer** [comment]
Displaying that in the treemap would not help you one bit: It would make the treemap degenerate into a gazillion squares of the same size. You would not be able to see any directory structure, just little squares in a regular grid.

The treemap displays leaf items of the tree; each leaf is associated with a value, in this case the size of the file it represents. If all leaves are forced to use the same size, as you suggest, you can't see anything.

This would be even worse than this attempt to use a logarithmic scale:

![treemap-logarithmic](https://user-images.githubusercontent.com/11538225/98691152-0445f380-236e-11eb-8e63-9026bc1722fd.png)

in https://github.com/shundhammer/qdirstat/issues/92

In this example, there are at least some colors since this also contains my photo collection (i.e. a lot of files with a known MIME category that has a color assigned to it). But even there you cannot even begin to guess a directory structure; it's just lots of cyan-colored squares.

In the general case, you'd end up with some 100,000 tiny grey squares. What would that help?
