### ISSUE TITLE
Cannot compile with QT Creator

### ISSUE THREAD

**Issue by xavierbaez** [shundhammer/qdirstat#147]
../../qdirstat/src/SysUtil.cpp:207:85: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive]
  207 |     QString parentPath = ( path.startsWith( "/" ) ? "/" : "" ) + pathSegments.join( '/' );
      |                                                                                     ^~~
      |                                                                                     |
      |                                                                                     char
../../qdirstat/src/SysUtil.cpp:207:85: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive]
In file included from /usr/include/qt4/QtCore/QString:1,

**Comment by shundhammer** [comment]
I already told you that this works fine on 3 different systems, 2 of which have the latest Qt 5.15.

**Comment by xavierbaez** [comment]
It compiles from CLI but not from QT Creator

**Comment by shundhammer** [comment]
So the problem is quite obviously in your Qt Creator setup.

It might prefer to use a different Qt version; you can select the Qt version to compile with somewhere in its settings. It might prefer to use different compiler flags. It might be a gazillion things.

If it compiles without so much as a warning from the command line, the problem can't be with QDirStat.

**Comment by shundhammer** [comment]
Building in QtCreator works fine on an up-to-date openSUSE Tumbleweed with Qt 5.15 and on Xubuntu 18.04 LTS with Qt 5.9. No warning at all.
