### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by kornava** [shundhammer/qdirstat#154]
Can you create a chocolatery package 
It can be very useful for windows users

**Comment by shundhammer** [comment]
https://github.com/shundhammer/qdirstat#windows-compatibility

**Comment by shundhammer** [comment]
Please read the documentation. It can be very useful for understanding what's going on.

**Comment by kornava** [comment]
rude answer, you can be more respectful

**Comment by shundhammer** [comment]
> rude answer, you can be more respectful

I had it with know-it-all newbies who want to teach all the world. Seriously. You very obviously don't know the first thing about QDirStat (which by itself is perfectly okay), but you also never bothered to even have a most casual look at the documentation. You just went ahead and, filled to the brim with total and utter ignorance, started making demands, never even knowing what it is that you demanded.

On top of that, you don't even know how to spell the very thing that you demand that I do for you. It's "chocolateley", not "chocolatery". https://chocolatey.org/

You didn't even spend any energy making a case **why** I should do that or **how** some user would benefit from it. Did you even build and install QDirStat? Did you start it even once? On what kind of system?

No, you just dump a two-liner into the issue tracker, and that's the extent of energy you are willing to spend on it; let others do the work and let's come back when the demands are satisfied.

This is not how Open Source works.

Open Source works by participating, and that means getting involved; which you carefully managed to avoid. Participating can mean many things; not everybody knows how to program. Pure end users can participate, too; if they do get involved, that is. If they come up with good suggestions which come from creative use of the software. But the very minimum is to read the available documentation because the people who wrote it spent a lot of time and energy writing it. If you are lazy and don't read the docs, that means disrespecting that work.

Seriously, I don't need you who never contributed anything to the project to act offended. **Respect is not anything that you are entitled to; respect has to be earned.** And on that scale, you just moved way down into the negative zone.
