### ISSUE TITLE
Question: Can this project be built on windows?

### ISSUE THREAD

**Issue by Darker** [shundhammer/qdirstat#162]
Qt is cross platform and also provides cross platform filesystem API, so I was wondering if I could build this on Windows. Or at least how much work it would be to port it.

Is it something that can be done without too much effort? I am aware of WinDirStat, but I like this project more.

**Comment by shundhammer** [comment]
See also https://github.com/shundhammer/qdirstat/blob/master/README.md#windows-compatibility

(open the collapsed "Details" section)

Most parts of QDirStat (I'd say roughly 80-90%) are pure Qt; that part can be built easily on Windows. That includes the GUI classes (of course) and the core data classes like `FileInfo`, `DirInfo`, `DirTree`.

And then comes the POSIX part: Reading directories (`DirReadJob` and related) which of course is the base of it all. They use POSIX / Linux system calls for efficient directory reading: `fstatat()`, `opendir()`, `readdir()`, `closedir()`. Those don't exist in that form on Windows.

The `DirReadJob` base class, however, is flexible enough; a non-POSIX subclass using Win32 calls could be added.

In theory it should also be possible create a subclass that uses only Qt classes for that like `QDir` and `QFileInfo`; but some crucial features would be missing (at least the last time that I checked): Since Linux / POSIX systems have no notion of Windows _drives_, all directories are _mounted_ to one large directory tree. But if a partition runs full and you get that dreaded "no space left on device" error, you want to restrict disk space analysis to that one partition, not include all the others that you may have. But `QFileInfo` doesn't report what device (i.e. typically which partition) a file or directory is on, so there is no reasonable way to stop traversing into a directory that is actually a _mount point_, i.e. that is on a different device.

Then there is the next large block of problems: Cleanup actions. On a POSIX (i.e. Linux, Unix, BSD) system it's a common thing to start external commands in a _shell_ with a quite powerful feature set, and it will report messages on _stdout_ and _stderr_. On Windows, there is no real counterpart.

Even if restricting this only to moving files or directories to the trash, that would work completely differently on Windows.

Then there are lots of convenience functions that use the `/proc` filesystem to obtain information about available filesystems (mount points) and many other things; there is no counterpart on Windows.

Then there are QDirStat's _package manager_ functions: List installed software packages by their size including what files they installed, or the reverse, show what _unpackaged_ (i.e. orphaned) files there are in system directories.

And there is probably more.

Yes, with lots of work and dedication it might be possible to create a QDirStat for Windows; but the reasonably easy way would only result in a very dumbed-down QDirStat that couldn't do most of what the Linux version does.

Would that be worth it? I am not so sure. WinDirStat would probably remain the better option. That's why I kept recommending WinDirStat on Windows.

**Comment by shundhammer** [comment]
Then there is also the option to use QDirStat in a Docker container which should also work on Windows (though I admit that I never tried that for lack of a halfway recent Windows version):

https://github.com/shundhammer/qdirstat#qdirstat-docker-container

Try it.
