### ISSUE TITLE
Potential conflict on log file

### ISSUE THREAD

**Issue by cmatheron** [shundhammer/qdirstat#163]
In case a user launch 2 runs in parallel on a same machine, I see a conflict on log file, can I suggest the following update on main.cpp:

96,104c96
<     int i_rand;
<     char s_rand[32];
<     char s_root[128];
<     srand(time(NULL));
<     i_rand=rand();
<     sprintf(s_rand,"%d",i_rand);
<     sprintf(s_root,"%s%s","/tmp/QDirStat-$USER-",s_rand);
<     Logger logger( s_root, "QDirStat.log" );
---
>     Logger logger( "/tmp/qdirstat-$USER", "qdirstat.log" );

**Comment by shundhammer** [comment]
There is no conflict: Each new program run of QDirStat does logfile rotation if there already is one, then creates a fresh one named `qdirstat.log` in `/tmp/qdirstat-$USER`.

Since each log line even contains the PID of the process that initiated the logging, not even mixing the log output from multiple instances would be a problem: They can be kept apart with a simple `grep` command, should that ever be necessary.

When you still have an instance of QDirStat running while starting a new one, the log file of that older instance will become `qdirstat-00.log`, and it keeps logging to that one (since the process still has the file open, it doesn't even notice the rename).

When you start even more instances, the logs of the 4 most recent instances are kept (`qdirstat.log` and `qdirstat-00.log`..`qdirstat-02.log`). Any that are even older will no longer be accessible (but the logs are still written; you just don't see a directory entry for them anymore).

That number can be changed, but there is no point to that: The logs are for debugging and for reporting problems, not an archive for eternity. Even having the current and 3 older logs is already stretching it; it stops being useful when there are too many of them.

As for using a random number, that ist the most counterproductive thing I could imagine: The last thing I want to do when debugging something is dealing with random numbers. What would be the point? Those names need to be predictable to be any useful. And worse, there is no guarantee that such randomly generated filenames don't collide with each other. The only useful approach would be to do that based based on PIDs because they are strictly monotonously increasing (until they wrap around which takes quite a while).

Sorry, but that approach tries to find a solution for a problem that doesn't exist (and it's not even a solution). ;-)
