### ISSUE TITLE
I would like to identify directory names for coloring (Mime), not only files

### ISSUE THREAD

**Issue by cmatheron** [shundhammer/qdirstat#164]
my purpose is to color all the files included under a specific directory matching a specific name, please can you suggest to me the best way to add this functionality ?

**Comment by shundhammer** [comment]
So, you would like to have a "search" function where you enter a filename pattern, then it would search the directory tree for directories that contain a file with that pattern and highlight the directories with matches, right?

What about subtrees where the directory itself does not contain the file, but a directory in the subtree does? Same highlight? Different highlight? No highlight? (Which would make the feature pretty pointless IMHO)

If this is about MIME types: Right now only the treemap tiles are colored. That's easy because it's a clear 1:1 thing between matching a MIME type and the corresponding color.

However, if you would like the directory containing them to be colored accordingly: That gets complicated pretty quickly. I discussed that once about coloring the grey areas in a directory where each treemap tile would be so tiny that you can't really color them anymore.

This is feasible only as long as a directory contains only files of that MIME type and nothing else. But what if it has mixed content (which is the common case)?

Imagine a directory full of MP3s; that's easy to handle. But as soon as there is just one other file there like for example the PNG or JPG image for the album cover, then what? Is it still an MP3 directory? To what extent should this be stretched? From what percentage margin on is it really mixed content?

And a few directories further up the hierarchy, when does an MP3 directory tree stop being one?

Believe me, I thought long and hard about that when I thought about colorizing the "misc tiny stuff" areas in the treemap. There are many solutions that sound good and logical and first, but when you go into the gory details, it's becoming very vague, and usability suffers.

**Comment by shundhammer** [comment]
About coloring directories in the tree view, we have an example what this _could_ look like:

![QDirStat-err-dirs-light](https://user-images.githubusercontent.com/11538225/121229433-35e45600-c88e-11eb-847f-26f8d680503c.png)

Here, the directories that couldn't be read (where there was a read error of some kind) are colored in bright red. But that's no good if it's only that one, and the branch where this is in is collapsed so you don't see it; so that status needs to be propagated higher in the tree up to the toplevel directory. So the directories that _contain_ a directory somewhere in the subtree that could not be read are also colored, this time in a darker red (closer to the normal black text color). The purpose is so you can see that there is something wrong in that subtree, so you can open branches until you get to the directory that really had the problem.

So this needs two different colors so you can tell the cases apart. But it gets worse:

![QDirStat-err-dirs-dark](https://user-images.githubusercontent.com/11538225/121229754-a7bc9f80-c88e-11eb-9e9c-079356e3e696.png)

Some users like dark widget themes. But in those you need text colors that are contrasting well enough; and that's a lot more challenging than you might think.

In this case I chose bright red for the directories that could not be read, and yellow for the ones that contain such a directory somewhere in their subtrees. And frankly, I am not too happy with either choice: The yellow doesn't scream "error" loud enough (it's too close to the normal white text color for the non-error case), and the red, though bright, isn't as contrasty as I would like it to have.

And now imagine that with all the different MIME colors. Not only would it be a very colorful mess, there is also no realistic way to guarantee good contrast with both a bright and a dark widget theme.

And it would collide with that error reporting here; as users get accustomed to seeing lots of color everywhere, they would soon stop noticing that there were errors.

**Comment by cmatheron** [comment]
It seems that I was not enough clear on my need. We are using some EDA tool generating data identified, not by file names (or file name extension) , but by the name of the directory where the files are located.
So I would like to color all individual files present under the identified directory, and not the directory himself.
Thanks for your help

**Comment by shundhammer** [comment]
Please elaborate more. So far I am not even sure anymore WHAT you want to colorize and where. In the tree view? In the treemap?

Based on exactly what? The name of the parent directory? Or the name of some ancestor directory even higher up in the tree?

An example directory tree would be helpful. I suggest you create one with lots of manual `mkdir` and `touch` to create (empty) files, then use `tree` and/or `tree -d` to visualize it and paste it here, formatted as code, i.e. with a line with 3 backticks ``` before and after.

Please also explain what you would like to see colorized and where.

**Comment by cmatheron** [comment]
In the below example, I would like to identify all directory named "SAVED_SESSION" and see a colored rectangles for all files contained by the selected directory (cmd_log, lib_map, mod1, mod10, etc....  in the example).
The type of files are not identified by the file names, but by hierarchical position under "SAVED_SESSION" directory.
'''
SIGNOFF/
├── CHECKS
│   ├── RUN
│   │   ├── run.csh
│   │   └── run.csh.ORI
│   └── SCRIPTS
├── EARLY_TIMING_ANALYSIS
│   ├── functional_ss28_0.85V_m40C_SigCmax_0y50kR_7y50kR
│   │   ├── reports.2019-10-31-18:56:51.1
│   │   │   ├── 1_link_design.rpt
│   │   │   ├── 4_read_constraints_waived.rpt
│   │   │   ├── 5_ocv.rpt
│   │   │   ├── 9_variables_dump.rpt
│   │   │   ├── report_waiver.rpt
│   │   │   ├── runtime.rpt
│   │   │   ├── SAVED_SESSION
│   │   │   │   ├── cmd_log
│   │   │   │   ├── lib_map
│   │   │   │   ├── lweco_pins.data
│   │   │   │   ├── lweco_pre.tcl
│   │   │   │   ├── mod0
│   │   │   │   ├── mod1
│   │   │   │   ├── mod10
│   │   │   │   ├── mod100
│   │   │   │   ├── mod100_vc
│   │   │   │   ├── mod101
│   │   │   │   ├── mod101_vc

'''

**Comment by shundhammer** [comment]
So you want to colorize the _treemap tiles_. Okay.

That still doesn't answer the rest of my questions: Only if those files are direct children of that directory named `SAVED_SESSION`, or also when there is a directory in between?

What if there are multiple directories with that name?

What is the use case? What do you intend to do with that?
Is the intention only to see that there is a saved session somewhere in that directory tree?
Do you want to navigate to that directory by clicking on one of the colored treemap tiles?

It would be helpful if I didn't have to write a ton of text for every tiny bit of information.

**Comment by shundhammer** [comment]
If the purpose of this is signalling when during a lengthy experiment or session or measuring cycle some process created such a directory, you'd be much better off with a simple shell command like

    find /base/directory -type d -name SAVED_SESSION && xterm -bg red

which opens a red window for notification. You'd have to wrap this basic command into a loop (the `watch` command comes to mind), but that's it.

**Comment by cmatheron** [comment]
Concerning your question about children, the goal is to treat all things under directory names SAVED_SESSION, files and sub tree.

Multiple directories have this name, as it is a way to identify coherent set of data.

The intend is to easily and graphically see on a huge disk, where this kind of data are located, in order to perform some actions, like remove or navigate.

Thanks for your help

**Comment by shundhammer** [comment]
So what you REALLY want is to locate directories with that name; the color would only serve as the tool to do that manually.

To me this screams (loudly!) for another "Discover" action. They look like this:

https://github.com/shundhammer/qdirstat/blob/master/src/MainWindow.cpp#L1322-L1327

Then it would need one more class derived from `TreeWalker`:

https://github.com/shundhammer/qdirstat/blob/master/src/TreeWalker.h#L142-L151

In this case (rough outline, untested, but you'll get the idea):

```C++
class SavedSessionTreeWalker: public TreeWalker
{
public:
            virtual bool check( FileInfo * item )
            { return item && item->isDir() && item->name() == "SAVED_SESSION"; }
}
```

And add it to the menu with Qt Designer in the `main-window.ui` file and connect that action in `MainWindow.cpp` with something like

```C++
CONNECT_ACTION( _ui->actionDiscoverSavedSessions,    this, discoverSavedSessions()    );
```

Then you could call it from the "Discover" menu and get a window showing where they are located like this:

![QDirStat-discover](https://user-images.githubusercontent.com/11538225/121373884-ba42e180-c93f-11eb-9464-ac4e0d7e60f2.png)

-----------------

This is easy if you want to do that yourself for that use case (it has no general use for others, so this is not anything for the QDirStat main line).

I suggest you fork the QDirStat repo on GitHub to create your own and do that in a branch; then you can rebase it from QDirStat master when there is a newer version without losing your changes and still keep getting all future fixes and improvements.

For the GitHub workflow, see

https://github.com/shundhammer/qdirstat/blob/master/doc/GitHub-Workflow.md

**Comment by cmatheron** [comment]
Thanks for the proposed solution, it is perfectly working...
