### ISSUE TITLE
File age histogram view

### ISSUE THREAD

**Issue by eliv** [shundhammer/qdirstat#165]
A file age histogram would also be really useful. Maybe selectable to show just year, or month/year.

**Comment by shundhammer** [comment]
This is pretty much the same as issue #118.

A histogram is probably not very useful for that; it would only give away information about the distribution of file ages in the complete directory tree. To be useful, it would need to allow breaking it down into subdirectories.

**Comment by shundhammer** [comment]
Also please notice that you can also activate an "Oldest File" column (right-click on the column titles in the tree view), and there is of course the "Last Modified" column. You can sort the tree view by either of them.

**Comment by shundhammer** [comment]
What is the use case for this?

**Comment by eliv** [comment]
So one of first things I do when looking at an FS near full is figure out if there's a bunch of old data that can be deleted or archived to some other media. Essentially what I do is a find . -type f -ls | awk '{print $10}' | grep '^201' | sort | uniq -c for example, to see files in the previous decade. Thinking about this more I think a more general and extremely useful functionality would be stackable filters.  So you could limit the list of files being included in the size calculations by a date range, and size range and some sort of path regex/glob. This would make more sophisticated queries available to users that aren't cli experts. Also, then being able to export the list of files matching the filters into a file would be great to feed into tar or zip etc.

**Comment by shundhammer** [comment]
Simply use "Discover" -> "Oldest  Files".

![QDirStat-discover](https://user-images.githubusercontent.com/11538225/121551539-06f5ed80-ca10-11eb-934a-801e4bb401a2.png)

Or activate the "Oldest File" column and sort by that column to drill down (which is the more pedestrian way of doing the same).

A histogram wouldn't help you at all with that: It would only show the age distribution without giving any hint where those files are, let alone be a navigation aid to get there quickly.

**Comment by eliv** [comment]
Not sure if e-mail reply will work, but hopefully the attached image comes through from my testing of qdirstat. When someone is looking at an FS with 6 million files and 1.5 million sub directories navigating individual files isn't useful. One needs a tool to sort and aggregate the files on a larger scale, thus my suggestion of the stackable filters. The file age histogram is the sort of a helper to start understanding what the data is, but the filters and lists of files matching them would actually allow folks to perform meaningful operations on thousands or millions of files at a time. I've been looking around and haven't found anything useful but qdirstat seems to have the potential to be a real powerful tool for folks doing this sort of data archaeology without requiring them to be fluent in awk.

    On Thursday, June 10, 2021, 11:20:46 AM EDT, Stefan Hundhammer ***@***.***> wrote:  
 
 


Simply use "Discover" -> "Oldest Files".



Or activate the "Oldest File" column and sort by that column to drill down (which is the more pedestrian way of doing the same).

A histogram wouldn't help you at all with that: It would only show the age distribution without giving any hint where those files are, let alone be a navigation aid to get there quickly.

**Comment by shundhammer** [comment]
This still doesn't change the fact that a histogram is not useful as a navigation tool. It visualizes a fequency distribution. It does not give any hint where those files might be. The number or the distribution among ages is irrelevant when you are trying to hunt down old cruft.

And it gets worse: More often than not, a file age of `(time_t) 0` i.e. 1970-01-01 00:00 means that the machine creating those files had an invalid system clock, or that some file tool copying or unpacking it was slightly broken. So those outliers are a very special case.

The idea of a special visualization based on age like in issue #118 has some merit; but when we are talking about numbers like 6e6, most visualizations lose their usefulness because every individual item becomes too tiny to visualize anything.

Stackable filters are something that are useful only in theory; in real life, the great majority of users are confused and won't use them. I have some hard real-life experience with that; not even hardcore nerds use it. It's hard to make such a thing well accessible.

**Comment by eliv** [comment]
Yes, it's certainly a difficult problem space and users seem largely resistant to organization. However, I think keeping the qdirstat interface essentially the same, i.e. showing a list of directories sorted by the recursive size of their files is a fine data representation. Just keeping that same interface and allowing users to apply a size, age, and extension filter(path glob) to see how the size changes of the directories would be quite a powerful tool for users to understand and make decisions on what further steps are needed to improve or reorganize the layout of a filesystem. The extension histogram is very much useful step in this direction. I see it could be a tool a sysadmin can give to users and say, here figure out what data you want to keep and what you don't, and then it could generate a list of files for the admin to work with, or send to cloud storage for the user etc.

**Comment by eliv** [comment]
I understand it's a big piece with the potential for a lot of feature creep. I've at least enjoyed the discussion to help clarify my thoughts.
For the filter UI, I was thinking a row below the buttons with 5 inputs: start date, end date, min size, max size, and file glob(that might be the hardest say supporting *.{png,jpg} for example, or *test*) Grey out the data entry boxes when they're not active, and an apply check box or button.
I agree running cleanup commands directly could be error prone. Is there a dry-run mode? That's why I was thinking it could have an export files matching the filters button. This exported file could then be QA'd by the user & admin to make sure things seem sane. I might even make sure to deploy qdirstat on a vm that doesn't actually have access to the filesystems and let the user/admin copy into place the cache files to work from.

**Comment by shundhammer** [comment]
I did some experiments about file age statistics:

![QDirStat-file-age-stats](https://user-images.githubusercontent.com/11538225/126706885-36a0a4d9-835f-40eb-8bc9-6dd81612b822.png)

This is currently in [branch _huha-age-stats_](https://github.com/shundhammer/qdirstat/tree/huha-age-stats). It is activated with menu _View_ -> _File Age Statistics_ or [F4]. It operates on the currently selected directory or, if there is none, on the scanned directory tree's root.

As you can see, it collects pretty crude file age data based on the _year_ of the _mtime_ (modification time) of all files (and only files, not directories or symlinks or whatever) in that subtree.

It keeps a count of all files for each year, and it also sums up the file _sizes_ of all the files in that year, and calculates the percentages of each. You can sort by year (the default) or by each other of those data, so you can choose to sort by _total size percent_ which might make a lot more sense.

On the downside, there is no simple way yet to _locate_ the files of a given year in the main window's tree view; you still have to drill down manually, and that will usually only work for the latest or for the oldest files: You can sort the main window's tree view by the _latest mtime_ column, or you can make the _oldest file_ column visible and sort by that.

Since so many files can possibly be involved, just making each year expandable and list all those files there is not an option; in this example, that would mean adding 42,000+ files with their paths to a list representing the year 2020. That would make it pretty much impossible to navigate in such a list.

So right now I am trying to come up with a good way to make that possible in a well-usable way.

But even without that next logical step of user interaction, it does give some insight into a very rough age distribution. I think restricting this to years is a good compromise; Unix/Linux keeps file timestamps on seconds precision, but that wouldn't be useful for anybody.

In some other more extreme examples I have files going back as far as 1996, but that's the oldest on my machines. In theory, it _could_ go back as far as 1970 (`time_t` 0) which might add another 30 years to that list; but I haven't seen that anywhere yet.

Notice that only years are listed where files with that mtime actually exist in the current subtree, so the list may have gaps. I am still unsure if those gaps should be filled by some kind of separator entry to clearly visualize that fact. I'll have to experiment.

If all works reasonably well, I am inclined to merge that branch to _git master_, even without further navigation; I think it is probably useful even in this state. But it might see more improvement.

**Comment by shundhammer** [comment]
When I started this, I had also planned to add some more information in a summary line like starting and end year or the median year; but as I used it a bit, I found that really redundant since it's not that many numbers, and the numbers are all readily available in that table anyway.

**Comment by shundhammer** [comment]
One possible way for navigation to the files of a selected year might be smilar to this:

![QDirStat-locating-file-types](https://user-images.githubusercontent.com/11538225/126709339-6780176d-75e5-4782-adde-64be4cb98f0c.png)

This is for locating files with a specific file extension from the _file type statistics_ window. It could be very similar with the years: It would open another non-modal pop-up dialog with all directories that contain files with that modification year, and selecting the directory would navigate to that directory, open the branch in the tree view, and preselect all matching files.

I'll have to experiment.

**Comment by shundhammer** [comment]
I toyed with that idea further, and I went down a different path.

**Comment by shundhammer** [comment]
No feedback at all.

**Comment by eliv** [comment]
Demos and write up in #172 seems great, I think it'll be really useful for helping folks understand the nature of their data and planning future steps. I'll try and get some time to put together a build environment to test out the changes on master with some of my data.

**Comment by shundhammer** [comment]
Please notice that for openSUSE (Tumbleweed, Leap 15.x) or SLES (15, 12) there are ready-made packages even for the current Git master:

https://software.opensuse.org/download/package?project=home:shundhammer:qdirstat-git&package=qdirstat

**Comment by eliv** [comment]
Yes, that's helpful I was able to spin up a Leap VM, and install the package. Looks good, very easy to use. Takes just over a minute to load my 7.6 million line cache file I'm testing with(adding zstd in addition to gzip might be nice.) Which seems fine for a large file collection. I like the Sync with main window feature, seems like the file type window needs it now too. Also gives me another idea on filtering, could add check boxes in the age & type windows for each row and with the sync to main window feature the user could easily see, for example, images(or just .jpgs) from 2020.

**Comment by shundhammer** [comment]
One thing I am not 100% sure yet is the flood of information in the "file age" window; it appears a bit overcrowded.

![QDirStat-file-age-stats](https://user-images.githubusercontent.com/11538225/127743464-a078716c-303e-4b34-ac63-a7791be0f9ec.png)

![QDirStat-file-age-stats-last-years-months](https://user-images.githubusercontent.com/11538225/127743490-439ce7f8-40eb-405c-bbfb-89bc4a1873e0.png)

I was considering to reduce that amount of information, yet I could not bring myself to omit any of those columns.

Sometimes you might be interested in the sheer number of files from a time period, sometimes your focus might be their size; thus also the two separate percent pars, one for number of files, one for size percentage.

I'll have to experiment some more with that; maybe reduce the data columns to only those that are visible in the main window (size, size percent, files), maybe make it configurable (which is of course the most work-intensive option for developing this). I don't know yet.

**Comment by eliv** [comment]
I really like all the info in the file age view. It's all directly relevant to the task at hand, though maybe a checkbox at the bottom to toggle showing the percentages could give a simplified view. I'd think folks would get used to it pretty quickly.

As for the multi-dimensional filtering, I think the interactive nature of qdirstat and the fact that it's all data directly about the filesystem should help folks get their heads around it. It's way better then the find . -ls | grep stuff that I'm used to using, or just manually browsing directories. I think the UI would be somewhat intuitive if there's a check box after each row in the age & type windows with a header saying something like filter main window data. Though that's a bit much for a column header. Limit, filter, reduce: lots of similar words not sure which would be best.

**Comment by eliv** [comment]
Thinking about the filtering check boxes some more, what seems most intuitive to me is to have the check boxes for the age & type rows come up all checked when the windows pop up, so the functionality is the same as currently. Then the user could uncheck boxes for data they don't want to see in the main window. I guess that would be reversing the case of the header I said before so it would be show, or include in main.
