### ISSUE TITLE
Add option to not simplify folders into gray colors. 

### ISSUE THREAD

**Issue by Marsfan** [shundhammer/qdirstat#166]
It would be nice to have the option to disable the converting of small files into gray folders in the tree map. I have found this conversion to have a somewhat jarring appearance, and much prefer the appearance of WizTree on Windows, where small files are still shown individually. 

The following images are from scanning the same directory, once with QDirStat, and once with WizTree. 

<details> 
<summary> Scanning with QDirStat </summary>

![image](https://user-images.githubusercontent.com/9311953/121833469-08364d00-cc92-11eb-9658-033451668e2e.png)
</details>

<details>
<summary> Scanning with WizTree </summary> 

![image](https://user-images.githubusercontent.com/9311953/121833518-27cd7580-cc92-11eb-97fd-5b74eac62ff1.png)
</details>

As the images show, QDirStat will abstract away folders with smaller files by turning the entire area gray, while WizTree will continue to display all files, no matter what the size.

**Comment by shundhammer** [comment]
Compare directory trees with the same amount of files; you will be surprised. Windows drives typically have about 10% the number of files as Linux filesystems, so everything on a treemap generated on Windows is on average 10 times as large as on Linux.

There is also this configuration option in `~/.config/QDirStat/QDirStat.conf`:

```ini
[Treemaps]
...
MinTileSize=3
...
```

that determines the minimum treemap tile size to try to find the matching color.

But since there are so many tiny tiles on a Linux filesystem, that will have a bad impact on performance.

**Comment by shundhammer** [comment]
See also #58

**Comment by shundhammer** [comment]
Please also notice that one cause for the amount of grey areas in the QDirStat treemap is the large percentage (about 30%) of files without filename extension on Linux, so the type cannot realistically be determined. Those will be grey, even if they are large enough to be rendered in color (i.e. > `MinTileSize`) in the first place.

And (to prevent the inevitable follow-up discussion) no, it is not an option to call the `file` command on every single one of that. I already discussed that extensively in several GitHub issues. ;-)
