### ISSUE TITLE
Allow Ctrl+= to act as Ctrl++

### ISSUE THREAD

**Issue by sakkamade** [shundhammer/qdirstat#174]
Hello. 

The problem that I see is that in order to zoom in the treemap, I need to use Ctrl+Shift+= shortcut, to zoom it out Ctrl+- (or Ctrl with numpad's `+` and `-`), which is not always so convenient.

Of course I experienced this same issue in numerous other programs as well, but QDirStat has no (apparent) way to change keyboard shortcuts, as far as I can see, hence my feature request.

Thank you for creating and maintaining this truly useful application.

**Comment by shundhammer** [comment]
This is problematic since this highly depends on the user's keyboard layout. In your case `Ctrl`-`Shift`-`=` may work well (US keyboard layout?); on my German keyboard layout, in the best case, it might not do anything at all, in the worst case, it would interfere with `Ctrl`-`0` (digit zero) because `=` is actually `Shift`-`0` in this layout.

  https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg

BTW the mouse scroll wheel also zooms in and out of the treemap (which is no good if you use a laptop without a mouse, of course).

Also, those default key bindings are intentionally what all the web browsers use for zooming (but I guess that is little consolation in your case).

**Comment by sakkamade** [comment]
> on my German keyboard layout, in the best case, it might not do anything at all, in the worst case, it might interfere with `Ctrl`-`0` (digit zero) because `=` is actually `Shift`-`0` in this layout.

Aw... Didn't expect that it could interfere. I see.

> BTW the mouse scroll wheel also zooms in and out of the treemap

Yes, but I don't like zooming with mouse wheel. I guess I'll keep using numpad, then.

Thank you for quick reply! 
Closing it.
