### ISSUE TITLE
Change the position of the file/directory size in the status bar

### ISSUE THREAD

**Issue by sakkamade** [shundhammer/qdirstat#177]
Being that the paths' lengths may greatly vary, the size of selected item keeps jumping about, since it is  located after the file/folder path.

I think it could be nice to see it at the left bottom corner, in other words, before the path of the item.

**Comment by shundhammer** [comment]
For one thing, this would be getting things backwards; the important part of that is the complete _path_ of the current file or directory, not the size.

Then there is the case of multi-selection which reports something like "3 items selected (42.0 MB total)" which would not fit at all into this scheme, or it would be inconsistent.

Also, this would make the _path_ jump around wildly since the pixel length of the size also varies: Not only because of the proportional font which is commonly used, also because of the different number of digits.

Verdict: No. This would not be an improvement.

For having a fixed location for the size of the currently selected file or directory, there is the _Details_ panel. The status line was important back when there was no _Details_ panel, but even then mostly for the complete path and for the sum of the sizes in case of multi-selection.
