### ISSUE TITLE
[Question] Will this work on WIndows 10?

### ISSUE THREAD

**Issue by BraINstinct0** [shundhammer/qdirstat#180]
I know that this is targeted primarily at UNIX-like systems.
However, since Windows 10 support Qt(not by default but it's doable) would running QDirStat on windows be feasible?
If not, would it be possible if WSL2 is used?

**Comment by shundhammer** [comment]
See https://github.com/shundhammer/qdirstat#windows-compatibility

Short answer: No, but you can try your luck with the _docker_ container that is provided by the community. I'd be interested in your feedback how well this works.

----------------------

Longer answer: Right, it's Qt-based, and Qt is a multi-platform framework. It's more than just a GUI toolkit; it's an all-encompassing framework that has abstraction layers for pretty much all that is needed for day-to-day programming. It can also handle file and network I/O, directories, starting processes; a lot of stuff, really.

But since QDirStat goes beyond what can be called "normal day-to-day programming", it needs more than that; so it uses POSIX standard system calls (which are available only by name in the Windows world), Linux/Unix conventions such as starting external programs via a _shell_, special files (e.g. the `/proc` filesystem) to get information that is otherwise not at all or not reasonably easily available, and Linux/Unix desktop standards like those from the _XDG_ (_X Desktop Group_) to provide functionality such as moving files and directories to the _trash_ directory.

All that goes beyond what Qt provides abstraction layers for, so using methods provided by POSIX system calls, infrastructure like Linux/Unix shells, the `/proc` filesystem or the _XDG trash standard_ are needed; and none of that is available in the same way on the Windows platform. Lots of functionality would be missing on a Windows port of QDirStat, and that would result in a much less powerful program.

But if you are of a mind to go new ways, by all means please try the _docker_ approach. It's very much a shrink-wrapped QDirStat with just the Linux environment that it needs; it's a bit like a virtual machine, but with _a lot_ less hassle, and it doesn't force you to install a Linux first into that virtual machine; which is of course very hard if you have little to none prior Linux know-how. The docker author did all that for you; all you have to do is install some basic infrastructure for docker containers in general, and then the QDirStat docker on top.

Give it a try. And then please share your experiences here; others will also be very interested.
