### ISSUE TITLE
Filenames with non-UTF-8 characters

### ISSUE THREAD

**Issue by izlence** [shundhammer/qdirstat#19]
Hello,
Nice to found this useful tool.

I have a problem. If a sub folder contains non-English characters, it cannot scanned. Also, the chars shown weird.

For example in Turkish,
"İnanç Esasları" shown as "Ä°nanÃ§ EsaslarÄ±"

Thank you.

**Comment by shundhammer** [comment]
What do you mean exactly with "cannot be scanned"? What happens? 
Is there an endless loop?
Does it return immediately without scanning that directory?
Is there a crash?
What does the log file say? (please attach; it's something like /tmp/qdirstat-???.log)

Please notice that there is no way to find out the encoding of file names. Modern Linux systems try to use UTF-8, but it is also possible to use e.g. Latin-5 (ISO-8859-9) for Turkish, or one of the various Japanese encodings. Or all of them on the same filesystem.

This has always be a problem, and it will always remain a problem. It is impossible to find out which one was used; there is no information anywhere on any of the widely used Linux file system types (ext2, ext3, ext4, btrfs, reiserfs, xfs) about this. Even worse, every application can do this differently, depending on how it converts the characters the user entered into a file selection box to what the underlying system call (open(), fopen()) uses.

Since UTF-8 is the most useful encoding for file names and it has been in wide use among all major Linux and BSD distributions, this is what QDirStat uses - or, more precisely, what it assumes that is used on a file system. If you are using ISO-8859-9 for your file (or directory) names, QDirStat will still treat them as UTF-8 and convert those bytes from UTF-8 to Unicode which will get you the wrong results (or sometimes fail if an invalid UTF-8 multi byte character sequence is detected).

That problem has been known for a long time. This is a generic problem for all file systems. The only sensible approach is to consistently use UTF-8 or, more limiting, to avoid non-ASCII characters (which includes all characters with accents, all Umlaut characters, that Turkish 'i' without the dot on top or the capital 'I' with an additional dot on top etc.).

QDirStat should clearly not crash, hang or loop forever, but any such non-UTF-8 characters might be displayed wrong.

**Comment by izlence** [comment]
No, qdirstat is not crashing. But if a file or directroy contains non-English char, its size looks like 0 Bytes and no additional information provided.
The result looks like:

![qdirtest](https://cloud.githubusercontent.com/assets/10724137/15221079/9dcf1376-1872-11e6-98cc-2a76a9eee718.png)

To be able to examine it by yourself, I prepared an example by downloading and renaming Google logo. It's in attached.

[qdirstat-test.zip](https://github.com/shundhammer/qdirstat/files/261726/qdirstat-test.zip)

**Comment by shundhammer** [comment]
First of all: Using non-UTF-8 locales is obsolete technology. Linux distributions have gone through great lengths to fix everything to make it work seamlessly since about 15 years with UTF-8.

With UTF-8, everything integrates well and without pain for both users and system administrators. You can have users creating file names in their native languages with all the characters used in any of those languages, no matter if it's Turkish, German, Russian, Japanese, Korean, Chinese, Thai and any number of other languages with their special characters. UTF-8 makes them coexist peacefully. Most users still cannot make sense of the file names in those other languages, but they are displayed correctly, and you can use command line tools as well as GUI tools to work with them. This is particularly important for the system administrator in case he needs to move any of those files away or delete them.

If you use non-UTF-8 locales like that Latin5 (ISO-8859-9) for Turkish or Latin1 (ISO-8859-1) for German etc., the users and the system administrator have to choose the correct locale ("setenv LANG=tr_TR.ISO8859-9") and stick with it. If you do that and any user sets up his personal environment differently to use another language ("setenv LANG=de_DE.ISO8859-1") and starts creating files in that language (e.g., "Überschuß.txt"), for everbody else the special characters might appear wrong (it's not even guaranteed that "Ü" which exists both in Turkish and in German use the same character code). It is very likely that the admin cannot even easily delete that file without resorting to tricks.

The sad truth is that those 8-bit locales use the same character codes for completely different characters (characters #128..#255 are almost guaranteed to be different for each of them), and there is no way to even tell that a different encoding was used - you can only tell as a human that those weird characters are out of place, that this file name does not make any sense.

This is why UTF-8 came along. This is not quite as wasteful as modern Windows file systems (VFAT, NTFS) that simply always use 16 bits (2 bytes) for each character, thus duplicating the size needed to store them. UTF-8 use multi-byte character sequences. Plain 7-bit ASCII characters (character #0..#127) use just one byte. Everything else starts with a special code above 128 that basically just says "attention, here comes a multi-byte sequence" (and implicitly how many bytes follow), and then anything from one to three more bytes. Thus, one single special character may consume 2, 3, or 4 bytes. But usually there are not that many of them, so the average overhead is typically much less than always using 2 bytes for every character.

This was introduced in most major Linux distributions about 15 years ago. The transition time was painful for everybody, since some systems were still using the old 8 bit encodings (ISO-8859-x), some were already using the new UTF-8. It took a while until it was widely adopted, but around 2005 (that's more than 10 years ago!) you could safely assume that other Linux users you sent mail to etc. should be able to handle UTF-8 files - both UTF-8 file content and UTF-8 file names.

Modern Linux distributions like e.g. (K)Ubuntu 14.04 LTS completed the transition: They don't even install the infrastructure for those old locales any more; they consistently use UTF-8 everywhere. This avoids a lot of trouble, and it introduces some discipline to enforce consistent encoding for everybody.

**Comment by shundhammer** [comment]
Having said that, I still tried to come up with a solution to your concrete problem. I acknowledge that while it would be good to have all file names on all file systems on UTF-8 consistently, there is legacy stuff that simply still exists, where nobody ever got around to make the transition to UTF-8 (even though the tools for that exist - the "convmv" script for the file names, and the "recode" command for file content).

So, I tried to create some test cases for UTF-8 file names (which is the default on my machines anyway), some for de_DE.ISO8859-1 (the old encoding for German), some for cs_CZ.ISO8859-2 (the old encoding for Czech since I took lessons in that language some time ago) and those files in Turkish (tr_TR.ISO8859-9, I assume).

But all those non-UTF-8 encodings did not work at all for me. I tried to set up support for them on my machine, but it didn't work. And when I unpack that ZIP file you sent, the file names are automagically converted to UTF-8 - not sure if the "zip" program does that while packing them (which would seem logical to me since ZIP is a transport format that should work on all kinds of systems, regardless of file name encoding) or if the Linux "unzip" does that while unpacking them.

So, adding that kind of support right now fails since there does not seem to be a reasonably easy way to come up with test cases. And I certainly don't want to do that kind of change blindly without being able to test anything.

So, the bottom line is that modern Linux systems made the transition to UTF-8 so thoroughly that they seem to flatly refuse to use any of the old encodings.

**Comment by shundhammer** [comment]
BTW I do know why QDirStat cannot display any useful information for those files: It stores the directory and file names in QString objects which use Unicode (UTF-16 - the format that uses 2 bytes for each character). The underlying opendir(), readdir() and lstat() system calls use plain bytes - they don't know or care what encoding is used. 

But when the information they return is stored internally in QDirStat, the names are converted to UTF-16, and for that a decision has to be made what encoding to use. QDirStat uses fromUtf8() and toUtf8() for that which is the safest to use in modern Linux environments.

It might also be possible to use fromLocal8Bit() here which chooses an encoding based on the locale the program runs in (it basically checks environment variables like LANG which should be set to the correct encoding - probably "tr_TR.ISO8859-9" in your case).

And here is the catch: This might or might not work. The locale environment in which a file was created might have been a completely different one than the locale environment QDirStat runs in. If a user used, say, a German locale environment with "de_DE.ISO8859-1" or even the modern "de_DE.utf8", it will still fail, but in different ways. It only works if there is a completely homogenous locale environment for all the files on the disk.

Most likely, we can safely assume that this is the case for you. But there is no way to guarantee that for everybody.

So one approach that might support even mixed cases would be to store a duplicate of the file names as unencoded byte arrays - e.g. a "rawFileName". This could be used to construct a "rawPath" all the way up the directory hierarchy which would be completely agnostic of encodings - for the system calls like opendir() and lstat().

Still, for displaying the names they would still have to be converted from the local 8 bit encoding (ISO-8859-9, ISO-8859-1, UTF-8 or whatever) to UTF-16 because that is what Qt uses to display characters. Again, some choice would have to be made which one to use, and again, we might guess wrong ("Überschuß.txt" vs. any of those Turkish file names).

And it continues with the cleanup actions: They use shell commands extensively. And it's not clear which locale environment is used in those shells; it depends on that shell's environment which can be configured in a lot of places (/etc/profile, ~/.bashrc, maybe ~/.zshrc - and a dozen other places).

Which environment should be used there? Would it be safe to use that rawFileName or rawPath? If we pick the wrong encoding here, the cleanup action might simply fail (which is annoying, but not that dangerous), or it might misbehave in spectacular ways; it might even open considerable security risks. 

It starts with the "cd" command which is issued first before the real cleanup command is invoked; it might fail because of that, and then the command might be executed in the wrong directory. This might be painful if the cleanup command deletes or even just modifies files in that directory without using the '%f' etc. placeholders.

The only really safe way would be to flatly refuse operating on paths or file names that contain non-ASCII characters - at least in non-UTF-8 locales. That would mean to keep track of that, to check if any path component of that directory contains such characters etc.; and for cleanup actions that go through directories recursively, it would have to be done for each of those directories before any command would be invoked.

This might open Pandora's box pretty widely.

**Comment by shundhammer** [comment]
![qdirstat-i18n](https://cloud.githubusercontent.com/assets/11538225/15268556/ee9ae5ba-19e3-11e6-9d17-e02953b35a95.png)

This is what the ZIP file you attached here looks like when unpacked on my machine (using the  de_DE.utf8 locale)

**Comment by izlence** [comment]
Your screenshot looks fine. I didn't understand what's missing on my system.
Thanks for the information.

**Comment by shundhammer** [comment]
Moved this to the TODO.md document. Closing here in the issue tracker.

**Comment by shundhammer** [comment]
I am not sure, but this might be the same as issue #61: There was a problem with QDirStat built against Qt 4.x (which NHellFire's PPA did). This is now fixed.

It is still possible, though, that you were indeed using an old-style Latin5 encoding. This is hard to tell apart because the symptoms are the same in this case.
