### ISSUE TITLE
Add a few file extensions for the list of known formats

### ISSUE THREAD

**Issue by C0rn3j** [shundhammer/qdirstat#191]
First some easy ones -
`.xz` -> Compressed Files
`.zst` -> Compressed Files
`.tzst` -> Compressed Archives

And two confusing ones, as they can be both Images or Video, but judging by the fact that `.gif` which can also be either is already sorted under Images...
`.jxl` -> Images
`.webp` -> Images

Maybe combining the Images and Videos section together might be a solution due to some files being hybrid formats?

**Comment by shundhammer** [comment]
If you would like to combine images and videos to just one category, you can do that for your personal configuration. But I don't think that would be a good idea in general: Those are different things, and I really want to see if it's my photo collection or some downloaded videos that take up all that space. The categories are already quite broad (because with the shading there is a limited number of colors for practical use); making them even broader would defeat the purpose of having them at all.

As for the specific formats:

- `.xz`, `.zst`, `.tzst` [https://github.com/shundhammer/qdirstat/blob/master/src/MimeCategorizer.cpp#L330-L331](are there). If you don't see them, try deleting your `~/.config/QDirStat/QDirStat-mime.conf` file while QDirStat is not running (unless you made heavy changes to it); it will be restored with defaults upon the next program start.

- `.webp` is a pure image format as far as Wikipedia tells me. I have never seen that one in the wild, though. Are you confusing it with `.webm` which is indeed a video format?

**Comment by C0rn3j** [comment]
> .webp is a pure image format as far as Wikipedia tells me.

It can however do video via animation - https://en.wikipedia.org/wiki/WebP#Animation, by which extent I would call it a video format, despite not being able to play sound(or at least I believe it can't play sound), though I suppose it doesn't matter as much and it usually is used for simple images.

> .xz, .zst, .tzst [are there](https://github.com/shundhammer/qdirstat/blob/master/src/MimeCategorizer.cpp#L330-L331). If you don't see them, try deleting your ~/.config/QDirStat/QDirStat-mime.conf file (unless you made heavy changes to it)

That's apparently an addition from 7 months ago, and the latest stable release is older than that, which would explain why I am missing them even after deleting the config.

Thanks for adding the rest!
