### ISSUE TITLE
FileInfo.cpp:310:27: warning: comparison of constant ‘0’ with boolean expression is always false

### ISSUE THREAD

**Issue by EFanZh** [shundhammer/qdirstat#20]
I got the following warning when compiling QDirStat:

```
FileInfo.cpp:310:27: warning: comparison of constant ‘0’ with boolean expression is always false [-Wbool-compare]
       url.contains( "/" ) < 0 )    // No (more) "/" in this URL
       ~~~~~~~~~~~~~~~~~~~~^~~
```

I'm wondering if this could leads to some problems.

**Comment by shundhammer** [comment]
Thanks for spotting this!

This was an artifact of the Qt3 -> Qt5 migration. The old code had used QString::find() (for the lack of a QString::contains() function in Qt3 ) which returned the position of the found substring, so back then the comparison against 0 did make sense. Today with QString::contains() that returns a bool it does not.

Since this function is used only very rarely in QDirStat (it was used a lot in the old KDirStat), any potential impact of this would be minimal: It is used once in TreemapView::rebuildTreemap() to restore a potentially zoomed-in treemap; in that case, it might reset the zoom to display the complete treemap again. It is used twice in DirTreeCache, but with the default for 'findDotEntries' which is 'false', so it would not get into that branch anyway.

But anyway, this certainly deserves to be fixed, and it's easy to fix, too.

**Comment by shundhammer** [comment]
Fixed.

**Comment by shundhammer** [comment]
I just grepped through the code, and it looks like this really was the only case of such a bad Q3String::find() -> Q5String::contains() migration.
