### ISSUE TITLE
Idea: Average File size Column

### ISSUE THREAD

**Issue by bobobeastie** [shundhammer/qdirstat#200]
Would be nice to have a sortable column for average file size (size/items) within a folder.  I mostly use QDirStat to find files to remove to free up drive space, in folders 2+ layers deep, and would like to start with the largest files first because it's more efficient. All I can really tell is how large a folder is, if it contains a million tiny files, reviewing each one before removing isn't efficient.  If an average was provided, I would have more of an idea about the size of the contents.  Obviously I can calculate based on the info given, but can't sort based on that.  Some of the columns are blank when you look at a file, so that would also apply here.

**Comment by shundhammer** [comment]
An extra column for that would be _completely_ pointless. All the information is already there, and it's already on the screen:

![Screenshot_2022-08-04_21-58-34](https://user-images.githubusercontent.com/11538225/182942084-4d7ed971-af64-4b65-9f38-37fc68e7cba1.png)

Just look at the percentage bar. You see two fat ones, the one for _opera_ and the one for _google-chrome_; all the others are tiny in comparision, so they are inconsequential if you are going after the largest space consumers (notice I didn't write "space wasters" because that's something different).

On the file level, it's the same:

![Screenshot_2022-08-04_21-59-26](https://user-images.githubusercontent.com/11538225/182942492-87730dfb-a946-4ed1-ac5e-dcb68df80e1b.png)

Only the first one sticks out, all the others are tiny in comparison.

Still, there are already full-scale file size distribution statistics (Menu _View_ -> _File Size Statistics_ or `F2`):

![Screenshot_2022-08-04_22-00-09](https://user-images.githubusercontent.com/11538225/182942826-45781868-bdd1-4d97-94a2-2a769941a480.png)

That gives you the _median_, not the average which is greatly distorted by single outliers; and quartiles and percentiles. But that's not meant for hunting down space wasters; it would do a poor job at that. It's intended for optimizing filesystem parameters and general interest.

If you want the largest files in an entire subtree, there is _Discover_ -> _Largest Files_. It does what you are asking for, but not in a clumsy way that needs a lot of mental acrobatics, but automatically.

![Screenshot_2022-08-04_22-09-15](https://user-images.githubusercontent.com/11538225/182943474-d4a1996f-f977-4350-948c-99e15027f606.png)

And you can even execute cleanup actions directly from there with the context menu that you get with a right click.

**Comment by bobobeastie** [comment]
Thank you for the detailed response, Discover Larger Files is likely to be useful to me and I will start using it. I still think it could be useful and I think maybe you aren't thinking on the same scale that I am:

![image](https://user-images.githubusercontent.com/69119347/182945607-acacb146-ab81-4f3d-8d70-afe3ff569dc6.png)

The highlighted directory is 108.9 GB with 46 items, the one above it is 123 GB with 985 items.  If I'm going to decide which one is best to spend my time organizing, the highlighted one is where to start.  There could be a directory 500 lines down with a single file of 50GB, that would be a much more efficient place to start.

I don't see a way to get to files from "File Size Statistics", so I don't see how it is useful in my case. It's entirely possible that Discover Largest Files is all I need, but I also ask you rhetorically why not add average file size as a column? Just don't enable it by default.  If it matters or helps show my point of view, I'm running QDirStat as a docker container in UnRaid and I separately browse the directories in Windows because the files are mostly videos which I need to scan through to determine what gets deleted, which I don't think can be done through a docker.

It would probably help if I reduced the scope of which shares I scan, and not scan my whole array.  At 200 TB the graphical part at the bottom becomes less useful.

**Comment by shundhammer** [comment]
In your example, you are already spending time with inconsequential parts of your overall disk usage. If you want to free some disk space quickly, go for the big items and don't bother with the small stuff. Of course that assumes that all directories have roughly equally important content; which is probably not very realistic in real life.

Learn to use the treemap; it gives you that information at a glance that you are trying to compute and then set into relation with other values in your brain. Move your mouse to the lower half of the window (the _treemap_), zoom in (with the mouse wheel) and then start _visually_comparing the rectangles (the _treemap tiles_).

The easiest way to zoom to the relevant directory level is to click on the _breadcrumbs_ widget (the path above the tree view) one level above the directories you want to compare, and then just scroll the mouse wheel all the way as far as it will go; then you'll get only that subtree in the treemap. Now click on the largest blobs; those are the largest files on that level. It's really simple, and you don't need mental acrobatics. Try it!

**Comment by bobobeastie** [comment]
Yeah that's why I said I should probably scan less things at once, the green files that are big enough to click on are not in consideration to be removed.

![image](https://user-images.githubusercontent.com/69119347/182953156-23baeedc-55a3-44c7-8d0a-5e96fe1f6dea.png)

The ones to remove are in the poorly drawn black box, which is an unorganized subset of the whole directory.  Graphically it's not very useful like this. Also, it is useful to me to find groups of large files because my workflow if more efficient processing directories at the bottom of the tree all at once, and not processing files in and directory while only focusing on size.

I had no clue you could zoom in to different directories and levels on the treemap, when I do this it's better, but still not as useful as what you are implying. I completely agree in the case of your previous examples that an average would be useless. If you want, it might be useful to inform the user they can mouse scroll zoom, I would but a message in the empty space below the tree map.

![image](https://user-images.githubusercontent.com/69119347/182955223-1ca233cf-b025-400e-8ccb-5d22f17f50ec.png)

I can see larger files clearly at this zoom level, but I can't see how they are grouped, there's no visible bounding for directories unless they are selected.  Only about the bottom 3rd of the above is up for organizing, I find it easier to drop organized folders into a folder next to them than one in a different directory next to the parent, but that's my problem (all of this is my problem, not yours, I appreciate your time), which I could adjust to make this easier. 

I'm still looking at which of the 3,381 subfolders to organize, yes when I look at the Items, Files, and Size columns I can tell pretty easily if it's a good candidate, but I can't organize the tree list such that all of those candidates are grouped together, like I could if there was an average column which was sortable.  I can't store 3,381 averages in my brain and then sort them, that's what computers are for.  Like I said before, a good candidate for organizing could be almost anywhere in the 3,381 folders, because the number of files and sizes are relatively random.

If I can't convince you to make this change, that's fine, you don't owe me anything, I'm otherwise enjoying your work.  I'm happy to keep discussing for whatever reason, if you want.  I just don't want to waste your time.

**Comment by shundhammer** [comment]
The criteria what to clean up and where depend on the use case. Are all data equally important? Is the _age_ of files important? When you need to free up disk space, which part of your data can you get rid of? Are there files that are totally redundant, files that can easily be regenerated, or files that are cruft anyway?

It depends. There is no one-size-fits all for that.

Is it really helpful to start with fewer files that are larger on average than those in a different directory? IMHO the overall sum is more important; and when several directories are roughly in the same ballpark with their total disk usage, I am not sure if it's useful to concentrate on the fewer larger files. Lots of little stuff tends to add up to a lot; and in particular when much space is wasted due to lots of tiny files with a nominal small size, but a large allocated size because each one still consumes a whole cluster (4k), that can be worse than a handful of larger files.

It really depends. This is where a sharp eye and a keen mind come into play. ;-)

**Comment by shundhammer** [comment]
From the technical perspective, it's not even as easy as it may look like.

The average is easily calculated: Total size divided by number of items.

But what total size? The total size of the directory, the size that you see displayed in its "size" column? That includes non-file items (directory nodes, symlinks etc.) as well. And should it use the nominal byte size or the allocated size? That can make a vast difference if there are sparse files.

Since QDirStat has that special "<Files>" node in the tree (the "dot entry") that only collects non-directory items (files, symlinks etc.) on that level, and that does not descend into subdirectories, it goes without saying that in the general case, you'd have to take _two_ such average values into account: The one on the directory node itself which does include subdirectories and their content, and the one on the _dot entry_ ("Files") that does not.


But the simple average is misleading: One single outlier greatly distorts the value. If you have one 2 GB ISO or MP4 movie in a directory full of little stuff, that average will be dominated by that outlier, even though it's absolutely atypical for that directory's content overall.

The _median_ would be much more useful, but the median is also much more expensive to calculate: It needs all values to be in a sorted list to pick the middle point. While this is acceptable for a single median, it becomes prohibitive to calculate for evey single directory node in the tree; it would mean sorting not only the items in each directory in the whole tree in advance, but even doing it multiple times since on each parent level all items in all subdirectories again have to be put into a list and sorted.

This is an absolute performance killer, and it would be needed for a value that is almost never used.

**Comment by shundhammer** [comment]
You might be interested in the latest feature described in issue #210.
