### ISSUE TITLE
periodic/notified rescanning?

### ISSUE THREAD

**Issue by Mousketeer** [shundhammer/qdirstat#206]
An potential feature request to make qdirstat even more awesome:

Durning a _cleanup _frenzy_ I would love to have the **option** to do an automatic rescan. On modern (local) SSD systems the impact is so low that it could almost be ignored and is well worth having your changes automatically present in the UI.

A simplistic way would be to periodically rescan the tree, or the part of the tree that is/was in the view window.
A more performant way might be to fsnotify/inotify the whole tree, or again the part in view?

A further refinement could be if the change was over X bytes, to avoid flagging temp/lock/pid files all the time.

The output could either be a visual indication on a line "something has changed here", or a re-calc and re-draw of the tree. In the later case it would be nice if the focus was not lost or the UI didn't flicker.

**Comment by shundhammer** [comment]
Hm... a quick & dirty version of that shouldn't be too hard to implement.

A **good** version of that, however, is probably almost impossible: Because a refresh always throws away most of your context; like open vs. closed tree branches, scroll position, selection status (what files or directories were selected).

And I learned the hard way that compromises and limitations are absolutely never honored: Even if the user requesting a feature was fine with limitations of a feature or with some quirks and oddities that it causes, for sure it won't take long until somebody pops up and complains about it.

Let me think about this for a while.

**Comment by shundhammer** [comment]
I am not sure if fsnotify/inotify of a directory tree that might span a whole filesystem, i.e. several 100,000 files and directories, is feasible; most likely, it will consume an enormous amount of resources and run out of them at some point, or bring the system to a crawl.

But yes, I know that a complete refresh, when using an SSD or even just a modern kernel that caches a lot of inode/directory information, takes just a moment.

**Comment by shundhammer** [comment]
I looked into the sources thoroughly, and I experimented a bit. The result:

This would be an absolute user interface nightmare.

If you wish to refresh all content, you can simply press the `F5` key or use the "Refresh All" button in the tool bar. And when you do that, you won't be suprised when it refreshes everything and everything is reset.

But with an auto-refresh, no matter if timer-based or based on a notification mechanism like _inotify_ (which I still don't know if that would be feasible for the complete filesystem; I didn't check), there would be several issues:

1. This would introduce the concept of a _mode_ in the program's main window: Normal operation or auto-refresh. That mode would need to be shown somehow, and that would need to be shown in a way that would make it obvious to the average user what it is and how to get rid of it. Because people click around and experiment; and it would be a nasty surprise for most.

1. An auto-refresh mode would make normal working with the program impossible. Because when you open or close tree branches, scroll the tree, select items (one or several) in the tree and/or in the treemap, the moment an auto-refresh happens, all that would be _gone_; it would be reset to the initial state with all tree branches except the toplevel ones collapsed, nothing selected, the list scrolled to the very top.  

    That would be throwing away a user's work. And that is the absolutely worst thing that a GUI program 
can do; users would lose confidence that it's worthwhile to do anything with the program because it might throw it away at any time. And of course users communicate that kind of frustration on social media, ruining the program's reputation. It doesn't matter if they just overlooked something, if maybe they acted a little bit stupid. They won't care, and nobody will listen to anybody trying to clear that up. Even if somebody _would_ try to follow up on all those posts, which I really don't want to do.

## Conclusion: No.

If you need a refresh, please simply hit `F5`. It's just a single keypress, it's there already, and it does not cause the ton of problems that an auto-refresh would.
