### ISSUE TITLE
Squarified cushion shading isn't correct

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#223]
The addRidge() call at the start of layoutRow() uses the parent tile rectangle instead of a rectangle representing the row.  This results in ill-defined cushion highlights that are mostly centred outside the leaf tiles.  Using a newly-created a rectangle for each row results in well-defined cushion highlights.  See the attached screenshot (not that the tile layout is also altered to match the original published paper, I'll discuss that in a separate issue).
![Screenshot_2023-11-16_18-20-58](https://github.com/shundhammer/qdirstat/assets/7702742/37dbecaf-b05b-40a3-bf52-de7f7a87e80d)

**Comment by shundhammer** [comment]
See also my answers to #224.

I would not exclude the possibility that there are bugs in the part adding those highlights. But as that paper by Huis et. al. shows, the highlight is typically not in the center of each tile; the deeper nested a directory is in the tree, the more it shifts away from the center because the ridges are added to give some visual hint about the directory hierarchy; they gravitate towards the center of the parent.

Having said that, it is entirely possible that the current QDirStat code does this slightly wrong.

**Comment by shundhammer** [comment]
## Showing the Hierarchy

In practice, it turned out that the slight hint of shifting the highlights towards the center of the parent doesn't give all that much visual cues; in particular in deeply nested trees (which are very common on real life Linux systems.

That's why not so long ago the _middle_ mouse click was introduced in QDirStat to highlight the borders of the parent directory, and its parent and grandparent etc. almost all the way to the top; see issue #181.

**Comment by shundhammer** [comment]
As far as I can tell, in your screenshot you zoomed in all the way to that directory level, right? When you zoom out agan one, two or three levels, the shading should change to give at least _some_ visual cue about the hierarchy; even if it's probably not much in an icon directory with a gazillion very small files. It works better if there are fewer, but larger files.

**Comment by Lithopsian** [comment]
I agree the highlight doesn't give much of a visual cue in the current qdirstat.  Because its centred outside the tile in most cases :)  Here's the new version zoomed out all the way.  The highlight shifts on off-centre tiles, but is sufficiently centred to give a much better visual cue.  I'll prepare a patch so you can try it out, or just so you can see where the issue is.

**Comment by Lithopsian** [comment]
Here are the patches to make cushion shading work with squarified tiles.  I've split the changes into two patches: the first just shades the rows correctly.  The second fixes the rendering to use the original published shading algorithm.  The changes look dramatic, but make surprisingly little visible difference.  Dark base colours are brightened slightly and there are very subtle changes to the highlight shape and position.  Apply these after the squarification patches on the other thread, not sure if they'll work against the master file.

**Comment by Lithopsian** [comment]
I've created a pull request.

In other news, I'm seeing some strange yellow lines on highlighted tiles on the treemap.  I don't think they are a deliberate feature.  They appear rather randomly on one or two sides, as in the screenshot.  Is something bleeding through from behind that should be hidden?  I see it whether the tile is selected with a click in the treemap or from the directory listing pane.

Is it a rounding issue with the tile boundaries?  I don't see it with my latest development code which fully clamps the tile boundaries to whole pixels without any gaps.
![Screenshot_2023-11-23_12-56-01](https://github.com/shundhammer/qdirstat/assets/7702742/669979e0-1edd-4ec0-8ba2-4943a97fb666)

**Comment by shundhammer** [comment]
A yellow outline is normally a multi-selection: The _current_ tile is outlined in red, all those that are additionally selected (`Shift`-`click`, `Ctrl`-`click`) are yellow. Since both outlines are additional overlays (`QGraphicsRectItem`) with different Z heights, the red one having a higher Z value than the yellow one, rounding errors might make a yellow one visible even though it should really be obscured by the red one.

![multi-selection](https://github.com/shundhammer/qdirstat/assets/11538225/4b76340f-1372-4f45-be85-cf8a98a5dd4a)

**Comment by shundhammer** [comment]
I just merged PR #225 into a new feature branch [better-tremap](https://github.com/shundhammer/qdirstat/tree/better-treemap) for parameter tweaking before merging that branch into _master_.

**Comment by shundhammer** [comment]
See also the summary in #236.
