### ISSUE TITLE
Status bar text isn't updated when zooming with the mouse wheel

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#228]
With hover effects on, the directory under the mouse appears in the statusbar.  If the treemap is then zoomed in or out, the mouse is almost always over a different directory, but the statusbar text is unchanged until the mouse is moved.

Related (?), the statusbar text doesn't time out.  Without hover effects, the statusbar text remains forever even with a timeout in the settings.  It disappears immediately when moving the mouse over one of the menuitems.

With hover effects, the text for messages such as the rebuild time doesn't disappear.  Text for the selected item is persistent (intentionally?), including for the invisible (root tile) current item when the program is first started.  The hover effect text disappears promptly when leaving the treemap area without a selected or current item, for example after hitting F5 (see issue #226).

**Comment by shundhammer** [comment]
The flickering status bar that you get if you enable the hover effect is something that I really never liked. Some users wanted it; but it has problems, as you found out.

The biggest problem is that every information in the status bar that should get the user's attention gets drowned out by the constant flicker.

If the hover effect is disabled, the text remains without a timeout by design. Why the menu bar removes it I don't know; but I am also not investing a lot of time to find out.
