### ISSUE TITLE
Packaged files are reported as unpackaged

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#229]
In my unpackaged files view, top of the list is /usr/lib, which I thought was a bit suspicious.  Of the handful I looked at, dpkg is showing them all at /lib, which is a symlink to /usr/lib.  This is Debian Bookworm, which has /bin, /sbin, and /lib merged under /usr, by default and I think mandatory, but some packages apparently still install to the symlinks.

**Comment by shundhammer** [comment]
So, Debian is now also doing the _usr-merge_ like OpenSUSE Tumbleweed, meaning that

- `/lib` -> `/usr/lib`
- `/bin` -> `/usr/bin`
- `/sbin` -> `/usr/sbin`
- `/etc` is now for users, the system uses `/usr/etc`

On dpkg/apt systems, QDirstat uses `/usr/bin/dpkg -S '*'` to get the complete file list for all packages. If that file list contains directories that now no longer exist because part of that path is now a symlink, I would consider that packaging errors: A package's file list should contain _real_ paths, not containing symlinked directories.

So I would say that QDirStat reports legitimate errors here. That might even help Debian packagers to find out where they still need to do that migration.

Yes, that is annoying for end users; but the problem is with the packaging, not with QDirStat.

**Comment by shundhammer** [comment]
As I am sure you found out, directories and files (by glob pattern) can be excluded from that view; but in this case, this might be sweeping real problems under the rug, so use it with caution.
