### ISSUE TITLE
add support for compressed files

### ISSUE THREAD

**Issue by marvintwentyfour** [shundhammer/qdirstat#230]
Well, title says it all. Add support for compressed files like in wiztree (for windows), e.g. a checkbox under View->"Show compressed file size".
Unfortunately, the "compsize" command needs root privileges but maybe there is an other way.

**Comment by shundhammer** [comment]
Well, the title did NOT say it all. Actually, that never works. That's just being lazy; or unable to express your thoughts. You are leaving me guessing what it is that you actually want. What do you mean with "support"?

**Comment by shundhammer** [comment]
You are confusing several concepts that have nothing to do with each other.

## Allocated vs. Byte Size

One is the allocated size of a file vs. the nominal ("byte") size: Almost all filesystems allocate disk space in _clusters_ (typically 4k), so a file always consumes multiples of the cluster size. That's only a minor thing for large files, but for very small ones (just a few clusters) it can really make a difference: A 46 bytes file almost always consumes one whole cluster, i.e. 4096 (4k) bytes.

But that has nothing to do with compression, and QDirStat already tells you _both_ sizes, especially when they are very different. That was the focus of the V1.7 release of QDirStat three and a half years ago, and it was documented [there](https://github.com/shundhammer/qdirstat/releases/tag/1.7) and in issue #134 extensively.


## Btrfs Compression

What you meant with _support for compression_ was obviously [_Btrfs_ compression](https://btrfs.readthedocs.io/en/latest/Compression.html). That is a filesystem feature that is very specific to Btrfs.

And like all things Btrfs, the _enfant terrible_ of filesystems, it behaves in weird, unpredictable ways. And the Btrfs developers, like always, insist on all related tools always requiring root permission because - well, _because reasons_ (no better explanation given). That makes them inaccessible for normal users.

You can't even use mundane tools like `btrfs df` to figure out the _true_ free disk space (as opposed to the blatantly lying result they return to _normal_ tools like `df` or the `statfs()`) without root permissions. I consider that a severe bug, but they don't care.

If anything, querying a very specialized tool like Btrfs `compsize` would be something to assign to a _cleanup action_ in QDirStat; you can do that yourself. But you'll need to prefix it with `sudo` and have your `sudo` environment set up in a way where you can use it without supplying the password there and then.

QDirStat does not and will not prompt the user for a password for elevated permissions; that would destroy the user community's trust base. If you wish to run it with _root_ permissions, that is certainly possible, and your free choice. But it will not nag you for a `sudo` password.

So, bottom like: The Btrfs developers misdesigned that; it's them who'd need to fix it.

**Comment by shundhammer** [comment]
More about Btrfs and their approach to reporting free disk space (and needing root permissions to do even that basic task):

https://github.com/shundhammer/qdirstat/blob/master/doc/Btrfs-Free-Size.md

Whatever made them think that either was a good idea (the false `df` reporting and requiring _root_ permissions) is beyond me.
