### ISSUE TITLE
Extending selection selects wrong items

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#233]
I think this one is reliably reproducible.
1. Start with a brand new tree and open up a directory with a fair number of files.  On my machine /usr/lib/x86_64-linux-gnu is convenient, but it works with others too.
2. Click the first file in the DirTree (left click, no modifiers).
3. Click another file, say the 10th in the list (left click in the DirTree, no modifiers).
4. Click another file, say the 20th file, **in the treemap** (left click, no modifiers).
5. Shift-click the first file in the DirTree.
The items between the 1st and 10th file become selected, when I'd expect it to be between the 1st and 20th.

This all sounds a bit complex, but it is just the most reliable way I could find to reproduce something odd that kept cropping up when I was playing with the highlighter.

I've tried to follow the signals and it seems like the tree model isn't being kept aware of which the current item is, so far as QDirStat is concerned.  Everybody seems to agree that the current item changes from the 20th to the 1st file, then a selectionChanged signal comes flying in with the wrong items in it.

**Comment by shundhammer** [comment]
There is the `SelectionModel` which keeps track of a set of _selected_ items and one _current_ item. Both the `TreeView` and the `TreemapView` are connected to it; both ways, sending and receiving. When one of the views sends a `select` signal, it temporarily blocks signals from the `SelectionModel` to avoid neverending signal ping-pong, because the `SelectionModel` will of course propagate that to all connected views.

In an ideal world, it wouldn't matter in which of the views you extend your selection, and you should be able to select a range of items in the `TreeView` with `Shift-Click` and then extend that selection with `Ctrl-Click` in the `TreemapView`. But since that is suck a finicky thing even with only one view, I wouldn't rely too much on that: One click when you didn't keep the modifier key (`Ctrl` or `Shift`) down exactly right, and the selection is gone.

This is very much like mouse copy&paste on X11: In theory it should work, and it should be simple, but in practice you start yelling at your computer because it messed it up again, and instead of your _primary selection_ you pasted your _cut buffer 0_ into that web form.

I am not sure if those details are worthwhile spending too much time on; it's dysfunctional on whole different levels already. Lipstick on a pig etc...

**Comment by shundhammer** [comment]
After a little experimenting, I think I realized what you mean. But I fear this is not only pushing the limits of the `QTreeView` widget, it goes beyond them.

AFAICS it has its own concept of the starting item of a _range_ selection, clicking the initial item and then selecting the last one of the range and all items between them with `Shift-Click`. It works well if you do it all in the same widget, but not when you do part of it outside, in this case in the `TreemapView`, and another part in the `QTreeView`.

What happens in this case is that part of the selection activity comes from the _outside_, from QDirStat's `SelectionModel`: One or more items are added to the set of selected items, and the `QTreeView` correctly shows them as selected.

What it does not do, however, is consider any one of them the start of a _range_ of items; think of it as `Ctrl-Clicking` a bunch of random items. Since the order of items is defined by the _item model_, the `QTreeView` has no way of knowing if an item that you selected from the outside is before or after the one that it considers the _current_ one; as a matter of fact, if the `QTreeView` doesn't have the focus, it probably doesn't even consder a current item.

When you click into the `QTreeView`, however, it gets the focus again, and the item that you clicked implicitly becomes the current item; and the starting point of any range selection that you might start from that moment on.

That is even the same when you use exclusively the `TreeView`: Click on any one item, `Ctrl-Click` on some more in a non-contiguous selection, then release `Ctrl` and `Shift-Click` an item further down the list; you get a range, but that range does not start from the very first item that is selected, but from the one you selected just prior to your `Shift-Click`.

This is the normal behavior. It's not specific to having two separate views working on the same item model and selection model.
