### ISSUE TITLE
Treemap Improvements

### ISSUE THREAD

**Issue by shundhammer** [shundhammer/qdirstat#236]
## Treemap Improvements

_See also issues #223 and #224 and PRs #225 and #235 by @Lithopsian._

### Layout Algorithm

@Lithopsian noticed that the treemap layout algorithm and the shading of treemap tiles were somewhat different in QDirStat from the original papers by the TU Eindhoven from 1999-2000. He observed that QDirStat was more prone to produce thin, elongated rectangles than necessary, instead of squares which are much better to compare relative sizes: The area of a treemap tile directly corresponds to the file or directory that it represents, and it's very hard to compare a long, thin rectangle to a square. Is it larger? Is it smaller? Or is it the same size? That's hard to tell when the shapes are very different.

#### Subdivisions

Building a treemap from a tree means subdividing a given area into rectangles to fit treemap tiles into that area; sometimes horizontally (left to right), sometimes vertically (top to bottom). The order in which that was done was different in QDirStat than what the papers proposed. @Lithopsian fixed that with the pull requests that he contributed; now it uses the _smaller_ side so the resulting tiles are more squarish and less elongated and thin.

#### Directory Grouping

The result is not only much more square tiles, but also a very visible grouping on each directory level: You can now clearly see larger squares on the top left and increasingly smaller squares down to the bottom right. As usual, as they become so small that you couldn't make them out anymore anyway, they are not rendered anymore, so in large trees, the bottom right tends to be a a flat grey area of "leftover tiny stuff" on many directory levels.

You can use the mouse wheel to zoom in and see more details.

### Ridges and Lighting

During each subdivision, a small visual "ridge" is added to give some more visual cues which tiles belong together, i.e. the lighting changes a little bit. This is another area that @Lithopsian improved in his pull requests; now the light source is no longer outside of a directory anymore, but in its geometric center.

### Treemap Parameters Tuning

This was all a good start on the way to improved treemaps, but the old treemap parameters for lighting, ridge heights and some more didn't fit very well anymore, so they needed some tuning - and simplification, because some of them were quite redundant and sometimes cancelled each other out.

Even in the old QDirStat (and KDirStat) treemaps those parameters sometimes didn't quite fit: Some treemaps had very dull colors, sometimes much too dark in some areas, sometimes too washed out and too light.  That is now much improved; the colors are now much brighter and cleaner.

It might still get some more fine-tuning in the future, though.

#### Old

![Treemap-src-qdirstat-old](https://github.com/shundhammer/qdirstat/assets/11538225/2acfc20e-0bbf-4242-ad97-991e42aa94b5)

#### New

![Treemap-src-qdirstat-new](https://github.com/shundhammer/qdirstat/assets/11538225/ec6c739f-df47-4f08-9022-cd72d9d29294)

#### Old

![Treemap-home-full-old](https://github.com/shundhammer/qdirstat/assets/11538225/ad1010cb-c229-4955-9ebc-a6ac67fe0124)

#### New

![Treemap-home-full-new](https://github.com/shundhammer/qdirstat/assets/11538225/3ff4bd7f-bc90-4892-aa99-3c887c89fb5d)

### My Home Directory after Cleaning Browser Caches etc.

You'd be amazed how much cruft is still left over after cleaning caches in the Internet browsers (Opera, Chrome, FireFox). I did some more manual cleaning here, too, using the new "Find" function, searching for "cache", "thumbnails" and similar.

#### Old

![Treemap-home-clean-old](https://github.com/shundhammer/qdirstat/assets/11538225/a99f5719-900d-4cb4-acda-43412389be22)

#### New

![Treemap-home-clean-new](https://github.com/shundhammer/qdirstat/assets/11538225/f739ef89-7124-4c68-b7f8-2752a0000d69)

#### Old

![Treemap-root-old](https://github.com/shundhammer/qdirstat/assets/11538225/cf1147b2-1b79-414d-9069-a39bc12e0ede)

#### New

![Treemap-root-new](https://github.com/shundhammer/qdirstat/assets/11538225/9c865cbf-eefa-4775-9ad6-75a0859a0418)

Don't get confused with the bold font in red for /var: This couldn't be read completely because of permissions (hence the red color), but still it's one of the largest directories on that level (hence the bold font).

#### Old

![Treemap-all-pkg-old](https://github.com/shundhammer/qdirstat/assets/11538225/c0094261-fad0-4899-9b6b-ae848c003283)

Notice the blue strip at the bottom which was the result of another minor bug; this is now also fixed.

#### New

![Treemap-all-pkg-new](https://github.com/shundhammer/qdirstat/assets/11538225/91b3a50f-2880-459b-9ea9-72ca80505373)

The sort order between packages is now slightly different because it now takes the _allocated_ size into account.

### Old

![Treemap-yast-pkg-old](https://github.com/shundhammer/qdirstat/assets/11538225/0b7f25f7-9ee9-4609-9c74-10c9dbc31f4d)

### New

![Treemap-yast-pkg-new](https://github.com/shundhammer/qdirstat/assets/11538225/00d829b8-8950-4c0b-8aff-a6763e7af16d)

Doesn't that already qualify as computer art? ;-)

## Conclusion

- Observe how the directory grouping is now much more obvious.

- Observe how much cleaner and brighter and much less washed out the colors now are.

**Comment by Lithopsian** [comment]
Do you want to take this further?  I've improved the algorithm to be faster as well as prettier.

Previously (minTileSize=3):
![Screenshot_2023-12-28_20-19-10](https://github.com/shundhammer/qdirstat/assets/7702742/b5f05c26-ca08-4bed-9bf1-6a81011c2d0b)

New algorithm (also minTileSize=3):
![Screenshot_2023-12-28_20-19-32](https://github.com/shundhammer/qdirstat/assets/7702742/27eff01f-4415-40e8-9a5a-c51c7a3947d5)
Instead of stopping dead at the first small tile, the algorithm carries on, but quietly drops many tiles while creating some at the minimum size to fill the available space.

There are many other performance improvements:
- streamlining the tile and cushion surface constructors
- optimising some of the loops in the tile layout functions
- factoring out the coefficient calculations some more
- precalculations of cushion heights and some pixmap values
- mime categorizer changes to improve the pattern precedence rules (eg. moc*_.cpp takes precedence over *.cpp) and still be a little faster.  Patterns with no wildcards (eg. Makefile) now have the highest precedence.

Dropping tiles "invisibly" makes an issue with zooming more obvious: when the selected item is a tile that isn't in the treemap, it isn't possible to zoom.  With the new treemap algorithm, a tile that is present at one zoom level may not be at the next and zooming will suddenly stop working.  This can be fixed by calculating the zoom actions directly from the DirTree instead of from the treemap.

Another oddity I came across is the treemap in the config dialog.  I didn't realise for ages that it is a real live treemap with a random DirTree.  It allows tile selection and also zooming.  Unfortunately there is no selection model, so the selections tend to keep disappearing.  I could fix up a workaround, but I'm not sure if this is something you really wanted to be in there, or if it just happened.  The zooming in particular could be a bit confusing.  I have set it up so the treemap just gets re-painted when a colour changes, but not rebuilt.  The main treemap also gets re-rendered when category changes are committed.

Lastly, I put the treemap build into a separate thread.  That doesn't make it much faster, but it avoids blocking the UI and allows for things like smooth resizing and scaling.  I also put the cushion rendering into background threads while the treemap is being built, which does make it faster although not as much as I'd hoped; there is too much overhead in either spawning thousands of threads or sending signals to one and it is heavily bottlenecked in the mime categorizer.  I'm still trying to improve it.  It seems stable here, but I imagine there might still be uncommon race conditions.  I had to mutex the mime categorizer singleton and pay very close attention to being able to cleanly cancel a building treemap since it no longer blocks other actions.  Attempts to break the actual tile construction into pieces have all failed miserably; I suspect that QGraphicsRectItem itself is the problem because the tiles themselves are largely independent.  I thought the FileInfo iterators might be a problem, but they seemed to be OK with it.

**Comment by shundhammer** [comment]
Since this issue was really meant to document the last changes (hence the "doc" label), let's please move this to a separate issue.

**Comment by shundhammer** [comment]
_Moved @Lithopsian's post to a new issue #237 to keep the user documentation (here) and the developer discussions separate_.
