### ISSUE TITLE
Subfolders are swapped while scanning

### ISSUE THREAD

**Issue by phiresky** [shundhammer/qdirstat#24]
To reproduce:
1. Scan a large folder
2. While scanning, click the arrow icon to show the subtree of a folder
3. The shown subtree sometimes actually belongs to a different directory

Example: Here the contents of /etc are shown as the contents of /usr
![2016-08-19-19-06-48](https://cloud.githubusercontent.com/assets/2303841/17817727/33b33afa-6640-11e6-9b3b-cf6a410be9a8.png)

**Comment by Smile4ever** [comment]
This issue might be related: when scanning, selecting a subfolder and using your arrows, the status bar text doesn't always reflect the item selected.

**Comment by shundhammer** [comment]
Yes, something is badly out of sync here. I noticed you don't even need to change the sorting; just opening or closing branches may already trigger this behaviour.

**Comment by pizzadude** [comment]
The main reason I still use k4dirstat is because of this bug.

**Comment by shundhammer** [comment]
Looks like QAbstractItemModel is too simplistic to realistically do this right: It is not made for data that are constantly changing and thus the sort order has to constantly change, too. So QDirStat's DirTreeModel would basically have to tell it all the time to rebuild itself completely whenever the sort order might have changed - i.e. whenever there is a new read job or a read job has finished.

That in turn would not only mean much more flicker, but also context information would constantly get lost - information such as the current scrollbar positions and what branches are expanded or collapsed. That would be a usability nightmare.

So it turned out to be necessary to give up the concept of sorting by read jobs during reading. Now sorting by directory names instead.

Interestingly enough, the user can still sort by any other column; but the sorting is only effective for the moment the user clicks on that header. As the numbers change, the sorting might get out of order. **This is a known limitation and any complaints about that will be declared invalid** and any such bugs closed as invalid. The alternative would be to disable user sorting completely while directories are read.
