### ISSUE TITLE
Clarify support for hard links?

### ISSUE THREAD

**Issue by anntzer** [shundhammer/qdirstat#25]
I am curious about how qdirstat handles hard links (if at all).  The lack of support for hard links in filelight, for example (https://bugs.kde.org/show_bug.cgi?id=144948), is highly annoying...

**Comment by shundhammer** [comment]
It does, and it does it exactly the same way as KDirStat did it:
http://kdirstat.sourceforge.net/news-archive.html#kdirstat-2.4.4

> Files with multiple hard links are now added up partially for each hard link found and displays them as something like 512 MB / 8 Links.

> A 512 MB file with 8 hard links now gets 512 MB / 8 for each time found. If all 8 hard links are within the current directory tree, it adds up to 512 MB. Formerly, this file was simply added up 8 times, thus distorting the overall sum.

> All in all, this comes much closer to what "du" reports - "du" takes hard links and sparse files into account, too. (There may still be some difference due to the way of accounting partially used file system clusters, though.)

From the KDirStat FAQ (which was part of the KDirStat online help that did not make it to QDirStat):

https://github.com/shundhammer/kdirstat/blob/master/doc/en/index.docbook

> Q: What does this display mean: 878.5 KB / 21 Links  ?

> A: This means that this file has a number of hard links. &kdirstat; uses only the
respective portion of its size for its statistics - in the above case, 878.5 KB
/ 21 = 41.8 KB. When another link to this file is processed, the next 875.5/21
KB are added to the total - and so on.

> The rationale is that is makes no sense to count such a file 21 times with its
full size  - this would greatly distort the statistics. For example, look at
/usr/lib/locale on a (SuSE) Linux system - many files
there have multiple hard links to save disk space. The total sum of that
directory on a SuSE Linux 9.2-i386 system is 40.5 MB -- as opposed to 205.6 MB
that the added-up output of /bin/ls -lR would suggest - sometimes, as in this example, this really makes a difference!

> Hard links can also introduce a whole new dimenstion of problems with
applications that create backup copies of working files - they usually only
rename the original file to a backup name and write their content to a new
file. Editors usually work that way. This however means that any additional
hard links to that file now point to the outdated backup copy - which is
normally not what is desired. Only very few applications handle this
reasonably. So the bottom line is: Use hard links only if you know very well
what you are doing.

**Comment by shundhammer** [comment]
Please notice that this raises problems if you have a hard-linked file in a directory tree you scanned, but that has more hard links outside of that tree:

If you scanned /work/iso/ with a file CoolLinux.iso that has 800 MB and 4 hard links, but only 2 of those 4 hard links are inside /work/iso, the others are in, say, /work/testing/, QDirStat will recognize that each of those 4 hard links accounts for 800 MB / 4 = 200 MB, so it will report to you 400 MB for the accumulated hard links in your /work/iso tree, disregarding the other 400 MB outside of it. If you want to burn the entire /work/iso/ tree to DVD, you might find that it doesn't quite fit on the DVD since you'll need space for the entire 800 MB of that file, not just the calculated share.

This might or might not be what you want. When I introduced that feature to KDirStat back in 2005, I thought long and hard how to handle that, and this was the solution that made sense in most cases. As pointed out, it has its limitations, though.

**Comment by shundhammer** [comment]
As for FileLight not doing that, I think they have the same misconception I had when I thought about introducing it for the first time:

They seem to think that it is necessary to keep a list of i-numbers and full paths (directory + name) for each file to make that happen. Well, not quite; you'd need only those files (not directories or any other type of file system object, only plain files) in that list that actually have more than one hard link; you could omit all others.

But if you do the accounting the way QDirStat / KDirStat do it, you simply need the number of links for each file system object, which the good old stat() system call will get you anyway. It is only a matter of providing the correct getter methods when returning the relevant size information: True size (disregarding number of hard links) or size to be accounted (true size divided by the number of hard links). It's really no rocket science.

But figuring out a good way to display it might be; I am not sure what would be the appropriate way to do it with FileLight's display.

**Comment by anntzer** [comment]
Thanks for your long answer.  I think a note about better hard link support in the README would be useful in attracting a few more users :-)
