### ISSUE TITLE
Possibly unintended change to the sorting of hardlinks

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#253]
[Commit cad30f9 ](https://github.com/shundhammer/qdirstat/commit/cad30f9f7be49808bf3958c999e016fecf4c59d3) seems to have affected the sort order of hardlinks, which I don't think was the intention.  An example on my machine is /usr/bin/gunzip/uncompress, a hardlink with an allocation of 4096 bytes and an actual byte size of 2346.  It shows in the tree as "2.3k / 2 Links" which seems fair enough, but it is sorted at the very end of the tiny non-symlink files.  In release 1.8, it was sorted amongst the files of about 1.2k.
![Screenshot_2024-01-28_16-25-34](https://github.com/shundhammer/qdirstat/assets/7702742/041af320-692d-4755-814e-3cfde343b381)

The change to the sort order for handling directories which very often have the same allocated size has the unintended consequence of sorting normal files by allocated size first, then total size.  Sorting was previously strictly by total size.  Usually this is OK, since small files all have the same 4096 allocated size, and are then sorted by their total size.  Hardlinks get a smaller allocated size, even though their total size may be much larger than many small files.

**Comment by shundhammer** [comment]
It becomes clearer when we see a bit more context:

![hard-linked-small-files](https://github.com/shundhammer/qdirstat/assets/11538225/16de715c-6ad7-452d-952e-cf9ac7f8766a)

So we have a lot of small files that all consume one cluster (4k), so the _other_ rule comes into play:

https://github.com/shundhammer/qdirstat/blob/master/src/FileInfoSorter.cpp#L40-L47

```C++
if ( a->totalAllocatedSize() == b->totalAllocatedSize() )
{
    // This is a common case because of cluster-wise allcation
    return a->totalSize() < b->totalSize();
}
else
    return a->totalAllocatedSize() < b->totalAllocatedSize();
```

All those tiny files are sorted by their `totalSize()`, the _byte size_ because their `totalAllocatedSize()` is the same every time: 4k, so you see them sorted by the few bytes of their nominal size.

But when compared with the files with multiple hard links, their `totalSize()` is no longer the same: Because the files with only one hard link still have one cluster (4k), while those with multiple hard links share that one cluster between all their hard links, so it's actually less than that one cluster; in this example one cluster divided by their two links, i.e. 4k / 2 = 2k.

That might be a bit irritating because it looks like there is a jump in the sorting, but it's really consistent.
