### ISSUE TITLE
Ignored directory has children that are not ignored

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#263]
It looks like /mnt has "no unignored children" (only looking for file children?), although it has directory children.  They are currently empty because nothing is mounted there.
![Screenshot_2024-02-20_12-33-07](https://github.com/shundhammer/qdirstat/assets/7702742/bdf711ce-33ad-4427-97f9-35b57ded8653)

**Comment by shundhammer** [comment]
I am not going to add yet another special handling for this arcane case. It's empty directories that don't belong there anyway. They are filed under `<Ignored>` because there are no unpackaged files there (because there are no files there at all), but if you put any files in any of them, those files will show up as unpackaged; which is correct.
