### ISSUE TITLE
Feature idea: Some improvements to mitigate accidental deletion

### ISSUE THREAD

**Issue by escitalopram** [shundhammer/qdirstat#267]
Hi,
I just accidentally deleted a bunch of data when trying to make space on my drive using QDirStat (1.8.1). The following happened:

I repeated this action for a while:
I intended to delete a bunch of subfolders of a common parent folder and used Ctrl+Click to select them and then use the »Delete (no way to undelete!)« context menu item.

Sometimes, the parent folder would also be deleted and I was left none the wiser with error messages like this:

```
…
cd /home/user/.m2/repository/com/acme/bantiger/statham/statham-cli/4.0.7-SNAPSHOT
rm -rf '/home/user/.m2/repository/com/acme/bantiger/statham/statham-cli/4.0.7-SNAPSHOT/statham-cli-4.0.7-SNAPSHOT.pom
Process finished.
rm -rf '/home/user/.m2/repository/com/acme/bantiger/statham/statham-cli/4.0.7-SNAPSHOT'
Process finished.
rm -rf '/home/user/.m2/repository/com/acme/bantiger/statham/statham-cli/4.0.7-SNAPSHOT/_remote.repositories'
Error: Process failed to start.
rm -rf '/home/user/.m2/repository/com/acme/bantiger/statham/statham-cli/4.0.7-SNAPSHOT/maven-metadata-local.xml'
Error: Process failed to start.
…
```
(edited for privacy reasons and to illustrate that the parent directory would be deleted in the middle of a list of its subdirectories)

I found out, that this was probably due to user error: Apparently, i had clicked on the parent folder to reveal its subfolders, and then held onto Ctrl too early, so I did not only select the subfolders, but also the parent folder.

I have two suggestions to mitigate user errors like this:

1. I can see no legitimate use for selecting anything for deletion when an ancestor folder is already there to be deleted. Therefore, one could make QDirStat show a big flashy warning, whenever a user wants an item and any of its ancestors deleted in the same operation. Another option would be to automatically deselect a directory when any descendant item is added to the selection, and block any ancestor directories of already selected items from being added to the selection.

2. The »Please confirm – Delete (no way to undelete!)« dialog only shows the first few items to be deleted, and with many items selected, ends with something like `... (37 items selected)`. This often makes it impossible for the user to recognize their error at this point. Therefore, it might be a good idea to add a listbox control with the full flat list of items to be deleted to that dialog. Also, display the items in order of their preorder traversal.

**Comment by shundhammer** [comment]
This is wrong on so many levels...

- The forced deletion already tells you "Delete (no way to undelete!)" in its title. This is the first of many reminders that you should be cautious when using that function.
- It prompts you for confirmation.
- That confirmation pop-up contains the first few files or directories to delete with their full paths, and an additional total number that will be deleted.
  
  ![del-files](https://github.com/shundhammer/qdirstat/assets/11538225/f3af8c85-51ad-4ab4-8a65-7c49a770f2f7)

- If that set of items to delete contains directories, it also says in bold font "**Directory**" to make that clear.
 
  ![del-dirs](https://github.com/shundhammer/qdirstat/assets/11538225/fc8a3eba-5ca1-4295-8ea0-ba5d6fba85b3)

Yet you manage to blame the program on your own bad decisions. Sorry, no. That function needs to remain usable. We are not doing the American approach here of dumbing down everything to the level of making it completely useless. I flatly refuse.

If you think you can't handle this powerful cleanup action, simply disable it and use "move to trash" instead which lets you restore everything if you think you did it wrong.

Why the hell do you keep Ctrl-clicking until you forgot what all that stuff is that you selected? If you are unsure, select only one (or very few) items. That's when the "tear-off" function of the "Cleanup" menu comes in handy: Use the dotted line above the first item in the "Cleanup" menu from the menu bar (not the context menu!), and you have all the cleanup actions instantly available:

![cleanup-tearoff](https://github.com/shundhammer/qdirstat/assets/11538225/cb8315d9-f6e3-4ce2-873c-efb96eaf7276)

Now you can select one directory at a time and nuke it without having to opening that menu again. That's the reason why I added this feature. I do that in conjunction with the "Bookmarks" menu to rapidly review all the junk directories that my Internet browsers keep filling all the time.

The "Delete (no way to undelete!)" cleanup is the big gun for big boys. It needs to be used with great deliberation; it's definitely not something for casual use.

**Comment by shundhammer** [comment]
> I can see no legitimate use for selecting anything for deletion when an ancestor folder is already there to be deleted.

I can. I do that all the time. When I spot a big blob in the treemap that I want to get rid of, I select it. And sometimes I also select its parent or grandparent or higher up. I don't want or need yet another babysitter flooding me with more warnings.

> Therefore, one could make QDirStat show a big flashy warning, whenever a user wants an item and any of its ancestors deleted in the same operation. 

You received such a warning. You ignored it. Lesson learned: Too many admonitions only lead to a "Yes, mom" reaction with rolling eyes - and get ignored.

> Another option would be to automatically deselect a directory when any descendant item is added to the selection, and block any ancestor directories of already selected items from being added to the selection.

What happens internally is that the set of selected items gets _normalized_, meaning that child (or grandchild etc.) items are removed from the set when the parent / grandparent etc. is already selected. This is needed because depending on the order of deletion, when the parent / grandparent is deleted first, the child / grandchild ceases to exist before it's its turn to also get deleted, resulting in invalid pointers.

**Comment by shundhammer** [comment]
In summary: When you use the Big Nuke, be careful. Nuke one country (or better yet, one city) at a time, not a whole continent. Nuke carefully.

Alternatively, don't use the nuke; put individuals into jail (the trash can) and then revisit the jail population before you nuke the jail.

**Comment by escitalopram** [comment]
I'm sorry that you interpret my suggestion as whining after my lost data. It was not meant as such. I'm not blaming anyone. The data wasn't even that important to begin with. I've also been a regular and happy user of qdirstat and kdirstat for a long time. I was sharing an experience with using qdirstat with the hope to contribute in some way to spare other users the experience I had. Think of it like a RCA after a plane crash.

Letting the user select an item and one of its parent folders to delete is obviously something that was not thought about prior, because if it were, there wouldn't be any of the `process failed to start` errors. I think we won't disagree about that? But I can see that some other users perceive this as a feature. And if that's important, I don't disagree about leaving the selection process the way it is.

However, I cannot follow your arguments about »You have been warned«. By not using a full list of items to delete in the warning dialog, you are actively preventing the user from checking their decision once more. The warning message is incomplete if enough items are selected , and because it is a modal dialog, people are discouraged from checking their selection in the tree view. Also, appending a line or two to the warning dialog about having selected an item and one of its ancestors wouldn't hurt anyone.

I think good software should make it hard for users to err, while at the same time not constraining them too much (think of e.g. autocomplete).

Once more: I'm not here to blame anyone, and I recognize, that deleting stuff is the user's responsibility after all.

**Comment by shundhammer** [comment]
Adding a scrollable list with all items that are selected would only make the problem recursive, and _nobody_ would read it if it's more than a handful of items. Even the 7 or so that are currently being displayed are borderline useful.

Imagine you selected 5 directories and 5 files outside of those directories. What would it display? The 5 files; and 5 directories? Or 5 directories with their complete content? Or yet another tree view where you'd want to expand or collapse that content?

Right now, you see something like this:

![del-selected-dirs](https://github.com/shundhammer/qdirstat/assets/11538225/4fed6e7a-9d7a-4c36-a106-d01ed90518d7)

That pop-up does not live in isolation! You also have the main window with the details panel on the right that gives a summary of what you selected, and you can still set the treemap with the selected items outlined in red (for the current one) and yellow (for all other selected ones). If you are unsure, you can cancel the cleanup action at any time and revisit your selection.

But again, it's much more useful not to spend a long time for an elaborated selection, but to select a few items and then start the cleanup action for those few ones; in particular if it's a very destructive one that cannot be undone, such as "Delete (no undelete!)" or "Clear directory contents".

What you suggest comes close to this:

![full-list](https://github.com/shundhammer/qdirstat/assets/11538225/82f27de6-6f7e-4a45-b2b8-e93ac4022994)

or this:

![only-dirs](https://github.com/shundhammer/qdirstat/assets/11538225/91333b59-8c34-4651-b7ec-61a87b8e365a)

And now what? What does that tell me other than "gee, that's a lot of stuff"? This is completely over the top for a _confirmation pop-up_! It's so large (by neccessity) that it covers a good part of the main window, obscuring a lot of other stuff that I might be interested in.

You expect users to scroll in that thing and think hard if they really want to delete this particular item; for each one? Without being able to see more details about it in the details panel on the right? The same kind of users who just spent multiple minutes clicking together a selection of that size?

That's not realistic. Nobody does that.

And it gets worse: If I then decide that I probably selected too much, then what? Then I close that list and go hunting for the things that were too much? How would I go about that? Frantically go through the tree view in the main window and search where those items were?

Or add another level of selection _in_ that list where I could remove items from it? With one click - and _oops, it's gone, that was the wrong one; how do I get it back into the list_? Or with yet another confirmation, i.e. a confirmation pop-up in the big confirmation list?

Don't you see where this is going? It only makes the whole experience worse. _A lot_ worse.

And, as explained before, that concept already exists: It's the desktop trash can. If this is the approach you like, simply don't delete directly; move to trash, then check the trash, and if you find anything there that shouldn't belong there, restore it with two clicks.

**Comment by escitalopram** [comment]
I'm sorry for not being sufficiently clear about whether I suggested a list of all items to be deleted or just the selected ones. I meant just the selected ones. I corrected that in my last post. I'm a little short with time atm, but I will consider the rest of your last statement later today.

**Comment by shundhammer** [comment]
Only the selected items is already what you see. The only difference is that the list is cut off after a reasonable number of items; because the human brain has a hard time grasping more than about 7 items at a time.

Again, the problem is the approach of selecting so many items at the same time. That's not a good idea; at least not for this particular cleanup action. I wouldn't do that. But I also don't want to treat users like little children; if they insist, they are free to work that way. But it might bad consequences in some scenarios, as you found out.
