### ISSUE TITLE
QApplication file not found or missing

### ISSUE THREAD

**Issue by Khrouhman** [shundhammer/qdirstat#272]
I couldn't install the qdirstat with yay on my Arch Linux device

Got error that QApplication: No such file or directory

**Comment by shundhammer** [comment]
You don't even write what exactly you did, or where you got the QDirStat package from. If it's complaining about `QApplication`, this sounds very much like you tried to install a _source_ package or tarball.

But one way or the other, this is about a _distribution package_, not about the QDirStat source code. Please contact the Arch Linux maintainer for QDirStat, or ask in an Arch Linux user forum.

Chances are that you might have completely misunderstood how to use the `yay` command. And since you are using Arch Linux, did you try the normal thing first, install QDirStat with the `pacman` command?

**Comment by Khrouhman** [comment]
You're right, i did misunderstand the yay command. pacman could not find qdirstat so i used git clone. When i did qmake and make it gave me the same error yay did. I will check around with Arch Linux community.

**Comment by Khrouhman** [comment]
I was able to fix this by reinstalling qt-base. Not sure why it didnt work before this but I appreciate your time
