### ISSUE TITLE
Display file name and file size in status bar upon hovering over a treemap tile

### ISSUE THREAD

**Issue by Smile4ever** [shundhammer/qdirstat#30]
It would be nice to see the file name and size in the status bar if you hover above a file in the colored view, just like WinDirStat does. #28 was the wrong feature request in fact :)

**Comment by shundhammer** [comment]
I admit I never used WinDirStat (I don't use Windows all that much). How does it handle an item in the tree view being selected at the same time? That behaviour would be an inconsistency if an item in the tree view or in the treemap is selected; it would be unclear what item the status bar refers to.

Anyway, using the status bar rather than a tool tip is a completely different matter, and that sounds much more intuitive to me - except for that issue of hover vs. currently selected item (and there is almost always something selected in the tree view and thus in the treemap).

**Comment by Smile4ever** [comment]
WinDirStat can run very well on Wine, so maybe you should try it :)

WinDirStat shows the selected file in the status bar until you hover another file in the color map. If you go outside the color map area, it displays the selected file again.

I think this is actually more intuitive. This gives you the chance to inspect file sizes and file names without actually changing the tree view, which may be undesirable. 

Please note that WinDirStat does not show the file size upon hovering, this is where QDirStat could be made better than WinDirStat :)

If you think this is inconsistent behaviour, you can introduce a preference to make both behaviours possible :)

Thanks a lot for considering this.

**Comment by shundhammer** [comment]
Implemented.

I am not yet sure if this isn't a big too busily flickering the way it is now; maybe it should get a timeout.

**Comment by shundhammer** [comment]
This is now disabled by default; see issue #86.

To enable it again, edit the QDirStat config file (`~/.config/QDirStat/QDirStat.conf`):

          UseTreemapHover=true

**Comment by shundhammer** [comment]
Update: This can now be changed in the new "General" page of the configuration dialog; no need to edit the config file manually.
