### ISSUE TITLE
Segmentation fault with custom cleanup action while scanning a directory

### ISSUE THREAD

**Issue by Smile4ever** [shundhammer/qdirstat#31]
I have configured a custom cleanup action, named "Open file in default application". The command for this is:
```xdg-open %p```

If I start a scan and during this scan, I execute the custom cleanup action on a file, qdirstat crashes and exits with an segmentation fault. I am able to reproduce this over and over again.

**Comment by shundhammer** [comment]
Oops, that's right. At this point, cleanup actions need to be disabled since by default when the cleanup is finished, it will trigger a re-read of that branch, and that will clash with the scan already in progress.

**Comment by shundhammer** [comment]
BTW for that cleanup, you should clearly choose "Refresh Policy: No Refresh" in the options of that cleanup.

On second thought, it would be enough to disable those cleanups that have another refresh policy set. "No Refresh" won't do any harm - but the others do.

**Comment by Smile4ever** [comment]
Setting the cleanup action Refresh Policy to No refresh makes the crash go away :)

**Comment by shundhammer** [comment]
Now disabling cleanups that have a refresh policy other than "No Refresh" while directory reading is in progress; otherwise the re-read when the cleanup action has finished clashes with the directory read alreay in progress.

Fixed with https://github.com/shundhammer/qdirstat/commit/e68b0815534ea69c19a9f662a86a7e258782b329.

This is not an optimal solution, but a very pragmatic one; the optimal solution might queue updates and execute them after the main read is done.
