### ISSUE TITLE
The ability to modify the appearance of the treemap

### ISSUE THREAD

**Issue by bala7s** [shundhammer/qdirstat#36]
The light effect on the chart looks really bad, so it would be great to turn it off optionally.
Also an option to adding outlines to boxes would be good.

**Comment by shundhammer** [comment]
This "chart" is called a _treemap_. But hey, that term is only mentioned on the QDirStat home page (README.md) 22 times (so my browser's "find" function tells me), so how can anybody talking about details about rendering that thing know?

**Comment by shundhammer** [comment]
And frankly, I take offense (no smiley here) about that "looks really bad".

You can say that you don't like it - that's your opinion and your taste. Okay. But you who elevated you to the rank of _arbiter elegantiarum_ to make such a bold general statement?

**Comment by shundhammer** [comment]
Having said that, there are a number of options to customize the appearance of that treemap. If you look into your `~/.config/QDirStat/QDirStat.conf`, you will find those settings:

```
[Treemaps]
AmbientLight=40
CurrentItemColor=#ff0000
CushionGridColor=#808080
CushionShading=true
DirFillColor=#107db4
EnsureContrast=true
FileFillColor=#de8d53
ForceCushionGrid=false
HeightScaleFactor=1
MinTileSize=3
OutlineColor=#000000
SelectedItemsColor=#ffff00
Squarify=true
```

They directly correspond to the _Treemap_ config page of the old _KDirStat_:

![KDirStat Treemap Configuration]
(http://kdirstat.sourceforge.net/screen-shots/kdirstat-config-treemap.png)

**Comment by shundhammer** [comment]
I don't plan to add that config page to QDirStat because those settings are just too arcane for the normal user. I have serious doubts that any relevant number of users ever changed anything here for permanent usage; people experiment and then reset everything to the defaults because that's what is really most useful.

But the settings are there in the config file if anybody really wants to change anything. Just make sure you edit that file while QDirStat is _not_ running because it will write its current values back to that file upon exit.

**Comment by shundhammer** [comment]
For more details, see the [KDirStat news archive](http://kdirstat.sourceforge.net/news-archive.html) and scroll down to the _2003-01-05 Treemaps are back_ section (no HTML anchors there, sorry).

Turning off cushion shading will get you something like this:

![Plain squarified treemap](http://kdirstat.sourceforge.net/screen-shots/squarified-treemap.png)

Turning off squarifying will make it even more basic:

![Plain non-squarified treemap](http://kdirstat.sourceforge.net/screen-shots/plain-treemap.png)

The orange treemap tile color is _FileFillColor_, the blue directory background is _DirFillColor_.

Experiment to your heart's content. Just don't complain that the result doesn't look good; that's why the cushion shading is there.

If you want cushion shading, but no other colors, simply delete all MIME type groups in QDirStat's MIME type config dialog (or select the same color for all of them). Then you'll get something like this:

![Monochrome cushion treemap](http://kdirstat.sourceforge.net/screen-shots/squarified-cushion-treemap.png)
