### ISSUE TITLE
An option to add free disk space to the treemap

### ISSUE THREAD

**Issue by bala7s** [shundhammer/qdirstat#37]
WinDirStat has this feature, and I really like it.

**Comment by shundhammer** [comment]
So you must be in a very elite club. It's disabled even in WinDirStat by default, and there are good reasons for that: Unless the disk is nearly full, that treemap tile for the free space completely dwarfs everything else in the treemap. The net result is that the treemap loses its usefulness pretty much completely.

Add to that certain complications in a Linux environment: By default, a certain amount of disk space is reserved for _root_. Would that be part of that "free space" treemap tile? If it's displayed as a separate tile, the treemap layout algorithm (which strictly sorts by size) might move it away from the rest of the free space - after all, it's someting like 5% or 10% of the disk space, so it might be considerably less than the rest of the free space. It would need to be inside the total free space treemap tile to visualize that correctly, so the free space tile would need a subdivision like a directory - reserved for _root_ vs. available for everyone.

And it gets worse. As Btrfs is becoming increasingly popular, free space is not quite what it used to be: On a Btrfs filesystem, a lot of free space is not immediately available because of its "copy on write" behaviour, i.e. the filesystem keeps one or more older versions of each file around. This is heavily used by filesystem _snapshots_ that can be useful to roll back a root filesystem to a previous state, e.g. to restore to the exact state before package upgrades were done. Just how much disk space is really availble is not easy to find out; there are several subcommands to the _btrfs_ command to display such details. The value Btrfs reports to the Linux kernel (which is what it returns for the _statfs()_ system call and what the _df_ command shows) is completely bogus because it does not take any of that into account.

So, which value would QDirStat report? For the lack of anything better, it would clearly be what _statfs()_ returns - which is pretty much useless for Btrfs which is becoming more and more popular (it's even the default filesystem for the root partition on recent SUSE distributions).

**Comment by shundhammer** [comment]
![windirstat-drive-d-with-free-space](https://cloud.githubusercontent.com/assets/11538225/20030639/8e822ff2-a369-11e6-8001-ebf90519ab0f.png)
![windirstat-all-drives-with-free-space](https://cloud.githubusercontent.com/assets/11538225/20030640/8e840dc2-a369-11e6-90a8-f9984e97afc3.png)
![windirstat-drive-c-with-free-space](https://cloud.githubusercontent.com/assets/11538225/20030641/8e89f160-a369-11e6-88c0-032352fda226.png)
![Uploading windirstat-drive-d.png…]()
![windirstat-all-drives](https://cloud.githubusercontent.com/assets/11538225/20030642/8e8e9166-a369-11e6-8b89-437e4bfd086b.png)
![Uploading windirstat-drive-c.png…]()

**Comment by shundhammer** [comment]
![Uploading windirstat-all-drives-with-free-space.png…]()

WinDirStat showing drive C: and D: with free space. The free space treemap tiles dwarf everything else, even pagefile.sys (the swap space) and hiberfil.sys.

**Comment by shundhammer** [comment]
![windirstat-all-drives-with-free-space](https://cloud.githubusercontent.com/assets/11538225/20030681/3d30c662-a36a-11e6-862f-28e66c86160b.png)

WinDirStat showing drive C: and D: with free space. The free space treemap tiles dwarf everything else, even pagefile.sys (the swap space) and hiberfil.sys.

**Comment by shundhammer** [comment]
![windirstat-drive-c](https://cloud.githubusercontent.com/assets/11538225/20030698/7ec70df2-a36a-11e6-8755-3346a2174eaf.png)

WinDirStat showing only drive C:. This time, pagefile.sys and hiberfil.sys are displayed in blue.

**Comment by shundhammer** [comment]
![windirstat-drive-c-with-free-space](https://cloud.githubusercontent.com/assets/11538225/20030711/d125cdb8-a36a-11e6-944b-ee82003dc677.png)

WinDirStat showing drive C: with free space. This time the free space tile is a little less dominant, but together with pagefile.sys and hiberfil.sys it still consumes about 75% of all space, leaving the user to guess what the hell all the little stuff might be. You need to zoom into directories to make the treemap display any useful here - i.e. to get rid of the large meaningless blobs.

**Comment by shundhammer** [comment]
![windirstat-drive-d](https://cloud.githubusercontent.com/assets/11538225/20030733/2bbca864-a36b-11e6-9400-6899451859cb.png)

WinDirStat showing drive D:.

**Comment by shundhammer** [comment]
![windirstat-drive-d-with-free-space](https://cloud.githubusercontent.com/assets/11538225/20030741/4d490a90-a36b-11e6-911d-a21cdd5e6c7f.png)

WinDirStat showing drive D: with free space. Since that free space is 80% of the total disk space, everything else is completely dwarfed. Again, you'd need to zoom into directories to make any sense whatsoever of that treemap. This is what QDirStat does by default by omitting that free space right away. And that's probably also the reason why this "feature" is turned off by default in WinDirStat. It's not useful at all to display anything meaningful.

**Comment by shundhammer** [comment]
And all this assumes that you always scan the complete filesystem, not just a directory branch. In the latter case, displaying free space would not make any sense at all because it just doesn't relate to the rest of the display at all; it would require yet another subdivision, this time of the used space, so you'd get a large treemap tile for the free space on that partition, another large one by the disk space used by everything else, and a probably pretty small one for the disk space used by the directory you are investigating. This is not useful at all.

**Comment by shundhammer** [comment]
Verdict: No. This is not going to happen. This would be a lot of work for no usefulness whatsoever.

**Comment by bala7s** [comment]
In WinDirStat, I use the treemap to navigate, so small blocks doesn't really an issue for me, and it never was.
For me, it would be great to see how much free space I have, directly in the app, in the chart.

I think, WinDirStat simply checks the free space of the drive and displays it as a simple block.

**Comment by shundhammer** [comment]
Sigh. I write a long, long text, and all I ever get as a reply is something that does not relate at all to anything I wrote. Why do I even bother?

**Comment by flurbius** [comment]
I read it :-)
And you make a good case for it especially your last point - about it making no sense when you are scanning less than a whole partition.

I still would like to see this feature implemented as I have two use cases where it is useful.

1. External storage/backup drives - to see whats using the space and how much more can be fit in.
2. Drives that are almost full and need space to be made available.  Specifically where will I get the most bang for deleting stuff.

Dont read this as me urging you to implement this feature, I'm just pointing out a couple of uses.
