### ISSUE TITLE
Use Theme Icons

### ISSUE THREAD

**Issue by timoll** [shundhammer/qdirstat#44]
The Icons that are used look pretty out of place when a different icon theme is used.

[QIcon ](http://doc.qt.io/qt-5/qicon.html#fromTheme-1) has some nice features that allow using theme icons with backup icons should they not be available.

I haven't looked too much into the source code, but it could also be possible to let Qt determine the mime type of files to use mime icons from the desktop theme.

I have already made some progress and replaced some of the simpler Icons that are used in the UI.

Some progress, icons are from the arc icon theme:

![image](https://cloud.githubusercontent.com/assets/17759381/22389512/35ef0946-e4e6-11e6-92dd-d6fcbe292077.png)

**Comment by shundhammer** [comment]
If you look into the `src/icons/` directory, you will find 23 icons for actions (menus, toolbar) and below `tree-medium/` and `tree-small/` 12 icons for filesystem objects (directories, files, block and character devices, symlinks), some of them for special status (mount points, directories without read permission, excluded directories). The filesystem objects come in two different sizes.

That short analysis would not have taken too much time; it's a simple matter of using a file browser or the file views on the GitHub repo. Yet, that would have shown that it's not quite that simple; how would a mapping between QDirStat's internal icon names and whatever an icon theme uses work? And how many icon themes exist that provide suitable icons for them all?

Worse, what would happen if an icon theme doesn't provide them all, but only a subset? That would be the most common case. Would it then fall back to the internal icons, mixing theme icons and those that come with QDirStat?

I would strictly veto that; visual appearance lives by consistency. And this is worst with icons. If a theme cannot provide the full set of required icons, I'd rather have none of them than mixing different icon styles within the same application.

And then there is the little matter how to load them. Right now, the C++ code only needs to take care of the tree icons; all the icons for the actions in the menus and the toolbar come from Qt Designer "*.ui" XML files. The application code only includes the header files generated from them and instantiates the respective UI class.

There is no way in hell I am going back to fiddling with tons of boilerplate code to create all that widget and QAction stuff manually again. This stuff will remain hidden from plain view, and Qt Designer will remain the tool to care about that.

But trying to load icons from fallback cascades like "try the main icon theme, then try another one etc. and finally fall back to the compiled-in Qt resource files" would mean exactly that.

In KDE 3 times, the KDE libs had classes like the KIconProvider that handled that kind of thing, but at the cost of needing to load every single icon explicitly in the application, and there was **always** the risk that an icon could not be found.

This is now fixed with using compiled-in icons with the Qt resource file system and referencing them with a fixed path in the Qt Designer .ui XML files.

But it gets even worse. With a requirement like "use the theme icons only if 70% or better of all needed icons can be provided", all icons would have to be preloaded (or at least checked which comes down to the same) by some global or singleton IconProvider class, which then would have to make a decision whether to keep the preloaded theme icons or (because too few of them are available) throw them away and fall back to built-in icons instead.

Does that sound like overengineering? Yes, it sure does.

Does that sound like there is a reasonable chance of success in normal environments that this would work in many cases? I don't think so.

Would that mean that despite the overengineering such a sophisticated icon engine would fall back to the built-in icons we are seeing now? I am pretty sure about that.

**Comment by shundhammer** [comment]
IMHO those theme-related functions in QIcon are either ill-designed, or they were meant with completely different expectations: If you ship different sets of icons with a commercial application, this may have a reasonable chance of success. 

But merely relying on Open Source artwork that tends to have different names for just about everything, even worse between KDE and GNOME or even Xfce, Enlightenment and whatnot, there is just no way to even figure out names for all the needed icons that are stable enough between those icon themes, let alone how they change over time.

I've been doing that stuff for too long to have any hopes of that kind of thing to stabilize. That's the stuff that is constantly changing, and the net result is that icons cannot be found at all (thus falling back to the built-in ones), or, worse, that icons with the same name mean something completely different after a while.

And I have no intention in hunting down pixels because some icon designer became too creative, or because somebody thought it might be a good idea to enforce consistent naming between their icons and introduce subtle breakages that way ("arrow-left.png" vs. "arrow_left.png" vs. "arrowleft.png" vs. "left.png" vs. "generic-arrow-left.png" vs. "move-left.png").

**Comment by shundhammer** [comment]
Summary: Stability and consistency within the application is much more important than trying to look the same as some other application on the same desktop.

I threw out KDE stuff for good reasons. I have no intention in getting dependency hell back through the back door via icons. ;-)

**Comment by shundhammer** [comment]
XDG icons spec:

https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

Looks like they started that spec with a lot of energy, only to get bogged down in all the gory details after a short while. The latest update is from 2006, 10+ years ago. They included really weird stuff ("weather-showers-scattered"), but very common everyday icons appear to be missing (or maybe I just didn't look hard enough).

**Comment by timoll** [comment]
Fair enough.

I think at least the tree-view should use the theme icons because the directory select from qt uses the icon theme of the system and is in my opinion also a part of the application. 

I have done some work on my branch on it and am pretty content how the majority works already. I have tested it with some popular icon themes. The files them-self use the icons from the mime types. 

![image](https://cloud.githubusercontent.com/assets/17759381/22400495/d68abed8-e5b6-11e6-913e-fa6ef444b721.png)

Here you see how it looks on my branch and with the latest release when you open a directory to scan.

But if you say that you'll never merge something that tries to consistently use theme icons I will probably stop working on it.

**Comment by timoll** [comment]
Here is an example with the arc icon theme:

![image](https://cloud.githubusercontent.com/assets/17759381/22400549/5e81e126-e5b8-11e6-9c4b-8575f05b3170.png)

I have to note that the actions are currently solved very experimental and it is something that I would change if I continue the work.

**Comment by timoll** [comment]
Had another Idea.

Expose the setting if the default or theme icons should be used to the user in the configuration.

To achieve the most consistency each icon would have a fallback icon name so that first a secondary icon from the theme is searched. 

To make this simpler from the architectural view I would suggest to make the binding from the icon name to the icon as late as possible (So a cleanup would have 3 strings, two for the theme and one for the default).

**Comment by shundhammer** [comment]
As for the file dialogs: They can be overridden by Qt plug-ins. Many desktops, foremost KDE, do that. The difference to in-application icons is that those icons are just a few, and they are all standardized, so none of them should go missing. And even if they did, that would be a problem of that desktop environment, not of the application.

**Comment by shundhammer** [comment]
In your suggestions I saw a lot of technical ideas, but I don't see any strategy to address the problems I pointed out:

- How to ensure some amount of consistency

- What to do when some of the icons are missing

- How to collect information how many percent of the expected icons could be loaded from the theme

- How to ensure icons can still easily be used from tools like Qt Designer

- How to handle cases where just no predefined icon (form the XDG spec or whatever) is present, for example for symlinks: There is usually an overlay icon that is supposed to be put on top of a normal MIME type icon, but no standalone "generic symlink" icon


I am not sure if my initial message became clear enough: This is more an organizational problem rather than a technical one. And purely technical solutions to organizational problems tend to fail in spectacular ways -- I've seen that too often.

**Comment by Yanpas** [comment]
In clementine there is an option to use native icons and fallback to clementine's

**Comment by shundhammer** [comment]
Yes, other projects do things differently. No doubt about that. :smiley: 

But that does not change any of the problems I pointed out above even one bit.
