### ISSUE TITLE
Space Sniffer like Treemap?

### ISSUE THREAD

**Issue by dufferzafar** [shundhammer/qdirstat#57]
qdirstat's treemap doesn't provide much information unless you hover on entries.

Perhaps we could have a treemap similar to [Space Sniffer](http://www.uderzo.it/main_products/space_sniffer/videos.html) which has File / Folder name & size on the tiles themselves.

Another feature of those tiles is that you can browse the structure by double-clicking on them etc.

**Comment by shundhammer** [comment]
Huh? The whole idea of a treemap is to visualize a value (here: the file size) with the area of each tile relative to the others. This is the information it provides.

To find out more about a treemap tile that stands out from the others (which is the whole point of that visualization), click on it. Then it parent directory opens in the tree view, and you an see a lot more information about it. 

Displaying a file's name in the treemap is counterproductive; it just clutters the treemap display with information that is of little use; only in very rare cases you will know what that thing is and, more importantly, in what directory it is. Just the filename does not do anybody any good.

That's why there is the full path and the size in the status line - ONE item, the one you are interested in, not dumping all filenames into that window. And that's why the two views communicate. That's the idea behind QDirStat (and formerly KDirStat).

Treemap-only visualizations have to go down that road and try to dump all information into the treemap, but that's just the poor man's solution to the real thing.

Ever heard of SequoiaView? No? I thought so. And I can tell you why: Because they also displayed onle the treemap. They pioneereed the idea of shaded treemaps which gives visual cues as to which files are clustered together in a directory. They also invented squarified treemaps where the tiles are no longer very thin, but long slice-like rectangles. Yet nobody uses that program anymore: Because just pure treemaps are not enough information, and you can't do much with them.

People use WinDirStat on Windows which is a Windows clone of KDirStat, the predecessor of QDirStat. Why? Because all those three programs give the user the power of both traditional tree views and treemaps. The aggregate is much more than the sum of the parts.

As for "browsing tiles": Looks like you haven't discovered yet the mouse wheel in the treemap or the zoom in/out toolbar buttons or context menu entries. Please read the "features" section of the README.md carefully; you might discover a lot more things yet. :smiley:

**Comment by shundhammer** [comment]
And frankly, the visual appearance of SpaceSniffer makes me barf. There is no shading of any kind, the labels on each tile clutter the display, and they seem to avoid screenshots with many items because that would show that below a certain size you simply can't put the name and size into the tile anymore. And all the frames (one for each directory level) contribute to the ugliness and take away even more screen space because they also put the directory name on the top of each frame.

Try this with anything the size of an average Linux root filesystem; you'll see nothing but directory frames and no content whatsoever. What good would that do?
