### ISSUE TITLE
Treemap doesn't use all available space.

### ISSUE THREAD

**Issue by Jedi121ch195** [shundhammer/qdirstat#58]
The Treemap doesn't use all space avaible for each folder but leaves grey areas in each zone : 
![image](https://cloud.githubusercontent.com/assets/26313569/23774831/0bf08a9c-0526-11e7-9261-772bbe15c4a4.png)
At maximum zoom there's no problem the area is filled with tiles :
![image](https://cloud.githubusercontent.com/assets/26313569/23774940/7fd8131c-0526-11e7-912a-0627b57d2f7a.png)

**Comment by shundhammer** [comment]
Yes, it does.

Those grey areas are directories where the size of those files are too small for any useful rendering.
By default that is 3 pixels on the smallest side - any tile below that will not be rendered.

This value can be configured in `~/.config/QDirStat/QDirStat.conf`:

    [Treemaps]
    ...
    MinTileSize=3
    ...

**Comment by shundhammer** [comment]
![tile-size-3](https://cloud.githubusercontent.com/assets/11538225/23795958/8c1355b6-0598-11e7-9a14-7504f128d047.png)

Default `MinTileSize` 3

![tile-size-1](https://cloud.githubusercontent.com/assets/11538225/23795974/9b039a04-0598-11e7-932a-ffc67648c9f3.png)

Customized `MinTileSize` 1

![tile-size-0](https://cloud.githubusercontent.com/assets/11538225/23795998/b2447576-0598-11e7-83a5-52631a58859c.png)

`MinTileSize` 0 - no difference to 1

**Comment by shundhammer** [comment]
Beware that this will consume **a lot** more resources since all those tiny tiles now have to be taken into account, too.

**Comment by shundhammer** [comment]
I know it is tempting, and I had the same thought before: Why not do some rendering with the directory just to fill that empty space?

In my examples above that might indeed work - it's my /work directory where I keep my photos, my MP3 collection, my videos. Those directories are indeed filled with only one file type, so I could simply render each photo directory in cyan and each MP3 directory in yellow.

But that does not work at all in the general case: When a directory contains mixed content (which is the case in the vast majority of directories), what color should it get? The color of its predominant content maybe? Well, what if that cannot be determined since over half the files belong to the "other" (i.e. "no clue what that thing is") category? We'd need some generic "directory with small stuff" color, right?

Well, guess what, we have that. It's that grey you see. :smiley: 

But that cannot be rendered just like the files because then you could not see a difference between a large file (like an ISO buried deep down in the directory hierarchy) and a large directory with a lot of small files. And that's what the treemap is there for in the first place.

**Comment by shundhammer** [comment]
Maybe rendering those areas not just in grey, but in some "grey noise" pattern might be an improvement. Let me think about that.

**Comment by Jedi121ch195** [comment]
Actually, the story is I'm a big user of WinDirStat and then I searched for
a equivalent for Ubuntu for another machine therefore found qdirstat.
I never had the issue with WinDirStat which seems to render any file how
small it is not leaving any grey area.

2017-03-10 14:10 GMT+01:00 Stefan Hundhammer <notifications@github.com>:

**Comment by shundhammer** [comment]
Here we go again with this "oh, but it's not like WinDirStat" bullshit. Guess what? **I don't give a shit**. It's not WinDirStat. Get over it.

**Comment by Jedi121ch195** [comment]
OK don't get too upset.

> When a directory contains mixed content (which is the case in the vast majority of directories), what color should it get?

Tiles represent files and not folders in the treemap, so one file is one tile. The color of the tile depend on the file extension.

**Comment by shundhammer** [comment]
Don't lecture me what my own program does. Files have tiles, and so do directories. You just don't see them in the default configuration.

http://kdirstat.sourceforge.net/news-archive.html

Scroll down to "2003-01-05 Treemaps are back" and read and look at the screenshots there to get an idea.

**Comment by shundhammer** [comment]
Experimenting with gradients for the directory tiles:

![dir-gradient](https://cloud.githubusercontent.com/assets/11538225/23812600/7e769e48-05db-11e7-820c-2a6f70916403.png)

**Comment by Jedi121ch195** [comment]
That's far readable for me.
Would be great.

**Comment by shundhammer** [comment]
One reason why your WinDirStat experience is different is probably also the fact that Windows tends to have far less files than Linux: My Linux root filesystem has 338.000+ items including 258.000+ files in 8 GB while my Windows (XP) has 42.000+ items including 37.000+ files in 7 GB. Roughly 9 times as many files in roughly the same space means a lot more tiny files which contributes a lot to the "lots of stuff suppressed because of miniscule size" phenomenon.
