### ISSUE TITLE
Support for IEC binary prefixes/units

### ISSUE THREAD

**Issue by fturco** [shundhammer/qdirstat#59]
In my opinion Qdirstat should support displaying IEC binary prefixes/units for file sizes: KiB/MiB/GiB/TiB (powers of 1024) instead of (or in addition to) KB/MB/GB/TB (power of 1000). What do you think?

**Comment by shundhammer** [comment]
Not only no, but **hell, no**.

There is only one group of people who use a factor of 1000 for any of those units: Hardware vendors (hard disks, flash media) who deliberately cheat their customer by claiming their stuff has 32 GB, not the 32 000 000 bytes they actually sell.

All sane people use 1024. This GiB / GB insanity was only invented by wiseasses who need to make everything in this world extra complicated. Actually, this was the point where this simple thing that was clear to everybody before became unclear by introducing yet another unit scheme that the world does not need or want.

**Comment by shundhammer** [comment]
I just had to boot Windows, and lo and behold, they are clearly using factor 1024, yet MB/GB (not MiB/GiB) in the file explorer and (as far as I could see) everywhere else - just the way all normal people have been doing it since the beginning of the computer era.

I repeat: Nobody but fraudulent hard disk makers ever use MB/GB with a factor of 1000.

**Comment by shundhammer** [comment]
I just answered this which came in via mail:

> Would it also be possible to add a setting to switch between GiB and GB? i.e 1024-based / 1000-based.

Possible yes, desirable no.

Not only because of what I wrote in

  https://github.com/shundhammer/qdirstat/issues/59

But also because I learned the hard way that users NEVER read any documentation, so it will never be clear again what unit base is in use when somebody posts screenshots of QDirStat in public forums; and then some clueless people start spreading false rumors.

Sizes in computing were always 1024-based, and that's how it is today; even if it's mostly for historical reasons. But it was clear until some particular hardcore wiseasses started introducing another, completely incompatible set of units that are 1000-based. And now confusion reigns supreme because it's now never clear which ones are in use.

With real GUIs, it's only GNOME programs that tend to stick to those 1000-based units; but even there, it's not all of them. Everybody else uses the old convention, i.e. 1024-based.

And then there is that plethora of web programmers who never can be bothered to stick to any standard at all; everbody does his own thing.

I don't want to be part of that confusion. It's 1024 for QDirStat.

The least desirable thing for a GUI program would be to make that configurable: From that point on, you'd never know without checking what unit type it uses. If you change the default, you might get it back again with a new home directory on a newly installed system, so you could never be certain if it's 1000 or 1024 based.
