### ISSUE TITLE
Notice: Fedora packaging

### ISSUE THREAD

**Issue by eclipseo** [shundhammer/qdirstat#66]
Hello,

I'm proud to announce that qdirstat has been packaged for Fedora Linux, and is now available on Fedora 25, 26, and the development release Rawhide.

Best regards,

Robert-André.

**Comment by shundhammer** [comment]
Thanks for letting me know!

Since I google for QDirStat on a regular basis, I had seen that packaging QDirStat for Fedora was in the making, but I hadn't seen a result yet.

If ever you need something to make QDirStat work better or to overcome any packaging or dependency issues, don't hesitate to contact me.

Thanks for the work!
