### ISSUE TITLE
Allow selecting fixed unit size for all files

### ISSUE THREAD

**Issue by adrianjohnson** [shundhammer/qdirstat#71]
Currently QDirStat selects the units (Bytes, kB, MB, GB, etc) for each file size automatically to keep the number in the 1-999 range. Sometimes it is easier to work with a single unit for all files so that the digits are in ascending order. It can also be easier to quickly see the file sizes when visually scanning down a list as I don't have to read the unit prefix character for each size.

I would like an option (maybe a View menu entry) to be able to select between auto (current behavior) and one of the unit sizes. If a fixed unit size is selected, all file sizes are displayed in this unit, using as many digits as required, and if a required, a decimal separator.

This would be like running 'du' with one of the -b, -k, or -m options.

**Comment by shundhammer** [comment]
No - I don't think this would be useful or desirable.

Showing all sizes human-readable (i.e. without a crazy number of digits) is one of the main features of QDirStat. If the sizes in any specific directory tree have roughly the same dimension (which happens, albeit pretty rarely), they will typically have the same unit anyway.

But the normal case is that the dimensions are vastly different, so it is very often necessary to use different units so humans can make any sense of the numbers.

> This would be like running 'du' with one of the -b, -k, or -m options.

Yes, that's what I fear, too. Frankly, the utter lack of any kind of a useful user interface was the main reason why I wrote the first KDirStat (from which QDirStat evolved) back in 1999. I do not want to go back there. And I also do not want to find my QDirStat being distributed in any Linux (or BSD or whatever) distro with such a user-unfriendly default enabled just because some package maintainer thought it would be a cool idea.

**Comment by shundhammer** [comment]
Let me show you some things you might have missed; you can easily recreate this with QDirStat's file size histogram view (_View_ -> _File Size Statistics_ or `F2`):

This is my `/work` partition where I keep my own data - source files, my photos, videos and other stuff:

![work-p081](https://user-images.githubusercontent.com/11538225/35196189-1cf84fe8-fecf-11e7-9464-89cd6e0d36a7.png)

As you can see, the median file size there is just 4.7 kB even though my photos are by far the most common file type with a median size of 943 kB overall (2.1 MB for the originals in `/work/photos/orig`, 397 kB for the post-processed versions in `/work/photos/sort`).

![work-file-types](https://user-images.githubusercontent.com/11538225/35196239-af398552-fecf-11e7-9ebe-d4ab66047aea.png)

![work-photos](https://user-images.githubusercontent.com/11538225/35196271-09ba48cc-fed0-11e7-9506-e8aa2bebefa9.png)

![work-photos-orig](https://user-images.githubusercontent.com/11538225/35196274-1067fce6-fed0-11e7-85a7-2d53554d6c93.png)

![work-photos-sort](https://user-images.githubusercontent.com/11538225/35196278-165902e4-fed0-11e7-8a24-398eb1f6eb06.png)

You might have noticed that the histogram for all of `/work` shows only percentiles P0..P81 by default. Why? Well, let's extend that a little further to show P0..P99:

![work-p099](https://user-images.githubusercontent.com/11538225/35196312-8b563012-fed0-11e7-8af2-b001fc37353b.png)

...and even more to show everything from P0..P100 (min..max):

![work-p100](https://user-images.githubusercontent.com/11538225/35196317-9aac5dac-fed0-11e7-8749-fd03883ec410.png)

So we are dealing with a lot of files distributed over a vast range of file sizes; 2 GB is the maximum here (but it might easily be even more for people who keep images of virtual machines around). Yet, the median is just a measly 4.7 kB.

So, you propose to not let QDirStat auto-select the units that fit best, but you want to set a fixed unit. Which one would you select in a scenario like this (which is just all too common)?

Even if you mean well and want to average things out, you'll end up with at least MB for everything -- which would mean that the vast majority of file sizes in this directory tree would be displayed as something like 0.0000047 MB. Yuck. Or go the other way and use kB all the time, thus giving the user a size of 2,100 kB for my average photo?

Even worse, making life a misery again for everybody using a non-English locale, so people never know what the hell is the decimal separator and what the thousands separator? Believe me, most Europeans are sick and tired of those American norms (including the unreadable date notation, but that's another matter).

No, no, and no again.

If you want a visual impression: That's what the percentage bars are for. So far I never met anybody who could not instantly make sense of this:

![root-tree-usr](https://user-images.githubusercontent.com/11538225/35196381-a1ab556c-fed1-11e7-9763-d180d0b42a33.png)

When you see that, you instantly know that you don't even need to bother with stuff below the second entry (`/usr/share`) because it's just peanuts compared to the first two.

**Comment by shundhammer** [comment]
If you think my `/work` partition is an extreme example, here is another one: An Ubuntu root partition.

![root-p091](https://user-images.githubusercontent.com/11538225/35196403-fa0c0ddc-fed1-11e7-846f-e0a3a61906ba.png)

![root-p099](https://user-images.githubusercontent.com/11538225/35196412-fe78eb88-fed1-11e7-96c2-1b7ca64b2ab6.png)

![root-p100](https://user-images.githubusercontent.com/11538225/35196415-02d35506-fed2-11e7-8c9f-b484dd58f9d7.png)

The maximum file size is less extreme, but still vastly different from the median: 142 MB max vs. 2.2 kB median. Again, there is a good reason the histogram auto-scale selected to display only P0..P91 by default because everything beyond P91 are just outliers - crazy values that can't reasonably be put into perspective with the "normal" ones (the ones between the first and the third quartile (P25..P75) plus some times the interquartile distance (see the histogram documentation for more information).

Again, everything else but auto-selected units would be a UI nightmare.
