### ISSUE TITLE
Feature request: ability to rename files

### ISSUE THREAD

**Issue by dandv** [shundhammer/qdirstat#76]
Use case: I'm finding that some large files are numerically named videos. I'd like to be able to quickly double click on them, see what they're about, and rename them to something more significant if I want to keep them. F2 would be a great shortcut for that.

**Comment by shundhammer** [comment]
QDirStat is not a general-purpose file manager, and it doesn't attempt to be one. If you need a file manager, please start one; you can do that with one mouse click (even starting with the directory you currently see in QDirStat).

Adding file manager functionality to QDirStat would bring complexity both in terms of user interface and code-wise to a whole new level; it would open all kinds of security concerns. There would have to be many more options than you currently think of; just think about file ownership and permissions. Think about renaming multiple files. Think about moving files from one directory to another (and the consequent refreshing in QDirStat's directory tree that would be required). Think about moving files across filessytem boundaries.

Verdict: No.

OTOH, if you have actions that can mapped to simple actions, you can define your own cleanup action for that. In your particular case, though, this might be difficult since it sounds like something really interactive.

If you can split this up into two separate actions, it might work; you could define one for viewing your video and one for renaming. But even the renaming is something interactive which doesn't quite fit into that scheme; this is why I recommend to simply use a file manager.

**Comment by shundhammer** [comment]
For defining your custom cleanup actions, it might help to think a little outside the box: Many things can be achieved by starting a shell window (xterm, gnome-terminal, xfce4-terminal or whatever) and add one or two commands to its command line (most shell windows support an option `-e` (_"execute"_) for things like that).

No, this isn't pretty, but since this is a very special task, IMHO a kludge is justified. 😈
