### ISSUE TITLE
Improve colors tiles

### ISSUE THREAD

**Issue by thibaultmol** [shundhammer/qdirstat#79]
Hi,

Thank you for making a properly maintained *dirstat project!
The feature to the cache to a file is great!

Only annoyance I have with it is that the colors and shading of the tiles, don't really look that good. (Would prefer something like Windirstat: [screenshot](https://imgur.com/a/pcUacU4) (if that's possible)

**Comment by shundhammer** [comment]
I don't like the treemap colors in WinDirStat at all: Not a palette that harmonizes at all, and the colors tend to be washed out by the light effects.

Having said that, you know that you can configure those colors to anything you like?
![qdirstat-mime-config](https://user-images.githubusercontent.com/11538225/41500392-9b31c2e8-7190-11e8-8eea-0f143dccec49.png)

QDirStat only has three pages of configuration options, so it's somewhat surprising that people don't find something that even has its own config page... :smile: 

As for the type of shading: This will remain as it is because there are semantics behind it; the bumps and the lighting are visual cues what files belong together in a directory.

There was also a discussion about this in issue #36.
