### ISSUE TITLE
no problem, wondered about feature request, project priorities, 

### ISSUE THREAD

**Issue by c4pt00** [shundhammer/qdirstat#83]
was wondering if you wanted to implement, an export for the TreeMap in qdirstat to a file which could use .SVG, (vector graphics) or other format, .PNG, to store the data in a larger format when exported 10MP, 5MP, 1920x1080 etc, to be able to pinpoint or work with the image using an external program outside of this source code for qdirstat

e.g
similar code, using qt make, not sure if qt4 or qt5 base, syntax seems really similar, for cpp outside of (qt) ?

http://doc.qt.io/qt-5/qtsvg-svggenerator-example.html

my guess is around here for qtPainter,

https://github.com/shundhammer/qdirstat/blob/master/src/TreemapTile.cpp#L361

not sure exactly where in the code, other problems at the moment, was just wondering if you wanted to implement this

wanted to use the SVG or PNG export for personal mental experimentation thinking about another project related to different code with AI, just as a thought model,

**Comment by shundhammer** [comment]
The way that the treemap is rendered is pixel-based. It's not a vector graphics, so exporting it to SVG would not get you any benefits whatsoever, in particular not a higher resolution when zooming in.

Exporting it to a higher-resolution pixel graphic would be doable. You'd have to specify the desired size in both dimensions, though; the treemap layout algorithm can handle any aspect ratio, but depending on the aspect ratio, the layout will look differently.

Of course, since there is only a limited number of color shades for each of the tiles, there are also limitations how smooth the transition from dark to light can get; not sure how much better the overall resolution would ultimately become.

For starters, you could try it on a 4k monitor with QDirStat running fullscreen and pushing the border between the treemap and the tree view above all the way up; that could give you some impressions how much better it will really look.

If the intention is to print treemaps, the color range of printers is probably also a limiting factor; the dynamic range of a monitor is (AFAIK) much larger than that of a printer's ink or toner.

So, what exactly is the use case for this?

**Comment by shundhammer** [comment]
No response
