### ISSUE TITLE
NTFS: Hard links make size of directories appear as half of the size of their actual content

### ISSUE THREAD

**Issue by ajz3d** [shundhammer/qdirstat#88]
When I was analyzing a tree of an **NTFS** volume, I have noticed that directory sizes do not match the sum of the file sizes that constitute them.

For example, there are four files in a directory: one of size of 1.0MB, one of 768kB and two 2.2kB files.
QDirStat 1.5 shows me that this directory contains 902.3 kB of data which is roughly half of what it actually contains.

This bug (?) does not seem to appear on EXT4 file systems.

**Comment by shundhammer** [comment]
That sounds very weird.

As a matter of fact, what QDirStat does internally is to query the filesystem with an `lstat()` system call for each file and directory and then for each directory on each level calculate the sum of all those individual values. So what you see reported as a directory's size is in fact just the sum of all those values.

But there are more things that might come into play. There may be sparse files, and there may be files with multiple hard links. Linux filesystems can do both those things; I am not sure how much of them NTFS supports, though.

There is also the cluster size which might be a factor for very small files: Disk space is not allocated on a per-byte level, but in larger chunks called _clusters_. Old FAT filesystems were notorious for very large cluster sizes because MS-DOS back then could only address them with 16 bit integers, so for larger partitions it was necessary to have huge clusters (up to 32 kB) just to make use of all that disk space. So even a file of only 100 Bytes would consume at least one cluster which might come down to 32 kB. For large files that is not much of a factor, but if you have a lot of tiny files it might be.

Microsoft writes about NTFS cluster sizes:

https://support.microsoft.com/en-my/help/140365/default-cluster-size-for-ntfs-fat-and-exfat

So for real life NTFS partitions up to 16 TB this should normally be 4 kB per cluster. This should be a non-issue.

**Comment by shundhammer** [comment]
If a file is a _sparse file_, you should see something like

  16 MB (allocated: 4.7 kB)

If a file has multiple hard links, you should see something like

  16 MB (5 links)

which makes calculating sums a bit difficult.

If you have files with multiple hard links, each directory that the file appears in will get a share of that file allotted. If you have a file _bigstuff_ with 10 MB that has 5 hard links, each directory that has one of those links will add 1/5 = 2 MB to its total size:

    /usr/share/foo                                     4 MB
    /usr/share/foo/bar/            10 MB / 5 =         2 MB
    /usr/share/foo/bar/bigstuff    10 MB / 5 links
    /usr/share/foo/baz/            10 MB / 5 =         2 MB
    /usr/share/foo/baz/bigstuff    10 MB / 5 links

The rationale for that is that you are most likely most interested in the accumulated sums that you'd need for a backup or that would tell you how much disk space would be freed when you delete that complete subtree.

If you only delete some of those hard links, the disk space still remains allocated, of course, only it's now shared between fewer hard links, so there is no gain from deleting just some of the hard links of such a file.

But in most real life filesystems this is pretty much a non-issue these days; Linux doesn't use hard links that much anymore. Symlinks took over most of that, and for symlinks there is a clear distinction between the original file that consumes the disk space and all the symlinks that just point to that file.

I don't know how heavily real life NTFS partitions use hard links. They do exist in the Windows world, but how widely they are used (and if that applies to the phenomenon that you saw) I don't know.

Microsoft writes:

https://docs.microsoft.com/de-de/windows/desktop/FileIO/hard-links-and-junctions

**Comment by shundhammer** [comment]
So, what QDirStat does is to collect the information provided by the relevant syscalls (mostly `lstat()`) and calculate sums. Even if those syscalls return wrong values for certain situations, the sums should clearly be consistent within QDirStat: The directory size is the size of the directory node itself plus the sizes of all the files in that directory.

QDirStat uses the byte size for all calculations and for displaying the values. It also stores the _block count_ for each file (which needs to be multiplied by the _block size_ of that particular filesystem, typically 512 Bytes), but that value is not shown anywhere so far. It is used internally to identify sparse files, though:

https://en.wikipedia.org/wiki/Sparse_file

**Comment by shundhammer** [comment]
There is also that NTFS feature called _alternate data streams_:

https://en.wikipedia.org/wiki/NTFS#Alternate_data_streams_(ADS)

Basically that means that a file could have more than one content; the normal file content plus one or more _alternate stream_. The system calls would only report the size of the normal file content, not that of any alternate streams. Not even the Windows Explorer would list that, and it basically couldn't do anything useful with such a file without breaking it (i.e. without removing those alternate streams).

While it fell out of use a long time ago, there may still be some old media or partitions around with files that still use them.

But even then, the sizes should add up correctly within QDirStat. Or did you compare them with some other tool and then calculated the sums reported by that other tool vs. what QDirStat reports?

**Comment by ajz3d** [comment]
This is an excellent and a very detailed explanation. Thank you.

I looked again into directory tree I was viewing earlier and it seems that most, and in some cases all, of the files have exactly 2 hard links. In directories containing files without any hard links, the displayed size is just a plain sum of filesizes and matches the result of programs which I used as a reference (Thunar's properties dialog and Double Commander's "Calculate Occupied Space" command).

It looks like NTFS quite heavily uses hard links because it wasn't easy to find a directory with files that wouldn't be hard linked at least once.

**Comment by shundhammer** [comment]
OK, then I'll call this resolved. Closing.
:thumbsup:

**Comment by Kadilov** [comment]
I believe there is something wrong with detection of NTFS hardlinks with qdirstat and, possibly, with Linux in general. After I noticed some inconsistent numbers when scanning a portable NTFS drive I discovered this bug report and read the discussion (it describes the exact thing that I see with my portable drive). Files that are stored in problematic directories are reported as having 2 links by qdirstat and `stat` console command, but when I checked them with Windows 10 fsutil tool by running "fsutil hardlink list _filename_" it showed only one path. In comparison, running the same command against notepad.exe (placed by Microsoft in "C:\Windows" of Windows 10 partition) will result in listing of three paths.
To illustrate it further, here is an output of Linux `stat` command with three files: first one is "normal", second one is an example of a "problematic" file, and the third one is notepad.exe from Windows partition.

```
stat "/run/media/alexandershchadilov/Transcend/Германия/Цвикау/MOV05182.MPG"                  
  File: /run/media/alexandershchadilov/Transcend/Германия/Цвикау/MOV05182.MPG
  Size: 10743851        Blocks: 20992      IO Block: 4096   regular file
Device: 811h/2065d      Inode: 15017       Links: 1
Access: (0777/-rwxrwxrwx)  Uid: ( 1000/alexandershchadilov)   Gid: (  100/   users)
Access: 2020-04-20 00:11:05.132045300 +0300
Modify: 2010-07-02 09:38:48.000000000 +0400
Change: 2012-09-13 16:01:57.734375000 +0400
 Birth: -
```

```
stat "/run/media/alexandershchadilov/Transcend/Youtube/Интерьер/Тренинг Рисунок интерьера.mp4"
  File: /run/media/alexandershchadilov/Transcend/Youtube/Интерьер/Тренинг Рисунок интерьера.mp4
  Size: 104488492       Blocks: 204080     IO Block: 4096   regular file
Device: 811h/2065d      Inode: 2637        Links: 2
Access: (0777/-rwxrwxrwx)  Uid: ( 1000/alexandershchadilov)   Gid: (  100/   users)
Access: 2020-06-11 15:36:32.684195400 +0300
Modify: 2018-04-29 12:10:42.379525400 +0300
Change: 2018-04-29 12:32:39.517861400 +0300
 Birth: -
```

```
stat /run/media/alexandershchadilov/5452782C52781548/Windows/notepad.exe
  File: /run/media/alexandershchadilov/5452782C52781548/Windows/notepad.exe -> unsupported reparse point
  Size: 26              Blocks: 0          IO Block: 4096   symbolic link
Device: 804h/2052d      Inode: 155463      Links: 3
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/alexandershchadilov)   Gid: (  100/   users)
Access: 2020-06-11 15:31:54.902294500 +0300
Modify: 2020-04-12 22:37:49.481834200 +0300
Change: 2020-04-12 22:48:46.252865000 +0300
 Birth: -
```

Note that the second, "problematic" file is described as a "regular file", while notepad.exe is a "symbolic link".
This test was performed with openSUSE Leap 15.1 and qdirstat 1.5.
As a side note, baobab application does not decrease folder size in this situation - however, I understand that it may be because it does not bother about NTFS hard links at all.

**Comment by shundhammer** [comment]
I just (~20 min ago) noticed something similar.

It appears to me that NTFS has hard-link counts for files where there really are no hardlinks.

When I scan the same filesystem with the new "ignore hard links" option set to "on", the result is _much_ closer to what `du` and the new "filesystem" panel are reporting.

**Comment by Kadilov** [comment]
I also have these Intel's logs named "IntelGFXCoin.log" and "IntelCPHS.log": `fsutil` in Windows and `stat` in Linux describe them in the same way as a "problematic" case in my aforementioned example. I would like to stress that "fsutil hardlink list _filename_" is designed to show actual paths, not the counter - just in case it was not clear.
Additionally, I downloaded FindLinks tool from Microsoft website and it reports zero hard links with these log files.

**Comment by shundhammer** [comment]
Okay, thanks for the additional information.

I don't know yet what to make of this; if the Linux `stat()` system call and the `stat` command disagree with Microsoft's own tools, I tend to believe Microsoft in this case (which is a rare thing for me... :smiley:).

If I can find a way to figure out that we are dealing with an NTFS filesystem, it might be possible to suppress that whole hard link accounting for those directory trees; but right now, Linux reports those mounts as "fuseblk" which might actually be anything:

![QDirStat-fs-overview](https://user-images.githubusercontent.com/11538225/84435701-8bae0000-ac32-11ea-8fc7-19b2b1aa60e3.png)

That information is obtained from `/proc/mounts´ which is really the only portable way to do this (to keep it working with BSD and other Unix systems and MacOS X).

In the worst case, QDirStat could try to run an external program (very much like it checks if one of the supported package managers `rpm`, `dpkg` or `pacman` is available); but that would really be an evil hack.

If you can find out some more about those hard links on the Windows side, I'd be grateful; I don't have much of a Windows development environment, just an ageing Windows 7 for gaming.

**Comment by shundhammer** [comment]
For the record: Those are the files that I checked:

```
[sh @ balrog] ...boot/Intel/Logs 19 % pwd
/win/boot/Intel/Logs
[sh @ balrog] ...boot/Intel/Logs 20 % df -hT .
Filesystem     Type     Size  Used Avail Use% Mounted on
/dev/sda1      fuseblk   98G   63G   36G  64% /win/boot
[sh @ balrog] ...boot/Intel/Logs 21 % ls -lh  
total 628K
-rwxrwx--- 1 root plugdev  82K Feb 21  2011 IntelAMT.log
-rwxrwx--- 2 root plugdev 441K Feb 21  2011 IntelChipset.log
-rwxrwx--- 2 root plugdev  30K Feb 21  2011 IntelControlCenter.log
-rwxrwx--- 2 root plugdev  65K Feb 21  2011 IntelIRST.log
[sh @ balrog] ...boot/Intel/Logs 22 % stat *  
  File: IntelAMT.log
  Size: 83342     	Blocks: 168        IO Block: 4096   regular file
Device: 801h/2049d	Inode: 61924       Links: 1
Access: (0770/-rwxrwx---)  Uid: (    0/    root)   Gid: (   46/ plugdev)
Access: 2011-02-21 20:40:32.405104200 +0100
Modify: 2011-02-21 20:40:58.223149500 +0100
Change: 2011-03-19 17:25:50.138411600 +0100
 Birth: -
  File: IntelChipset.log
  Size: 451320    	Blocks: 888        IO Block: 4096   regular file
Device: 801h/2049d	Inode: 61829       Links: 2
Access: (0770/-rwxrwx---)  Uid: (    0/    root)   Gid: (   46/ plugdev)
Access: 2011-02-21 20:39:53.202235300 +0100
Modify: 2011-02-21 20:40:29.191498500 +0100
Change: 2011-03-19 17:25:50.138411600 +0100
 Birth: -
  File: IntelControlCenter.log
  Size: 30204     	Blocks: 64         IO Block: 4096   regular file
Device: 801h/2049d	Inode: 63253       Links: 2
Access: (0770/-rwxrwx---)  Uid: (    0/    root)   Gid: (   46/ plugdev)
Access: 2011-02-21 20:41:20.156788000 +0100
Modify: 2011-02-21 20:41:21.669990700 +0100
Change: 2011-03-19 17:25:50.138411600 +0100
 Birth: -
  File: IntelIRST.log
  Size: 66052     	Blocks: 136        IO Block: 4096   regular file
Device: 801h/2049d	Inode: 62882       Links: 2
Access: (0770/-rwxrwx---)  Uid: (    0/    root)   Gid: (   46/ plugdev)
Access: 2011-02-21 20:41:15.258379400 +0100
Modify: 2011-02-21 20:41:21.685590700 +0100
Change: 2011-03-19 17:25:50.138411600 +0100
 Birth: -
```

**Comment by shundhammer** [comment]
This `lsblk` command looks like a hot candidate to find out what filesystem a  device with _fuseblk_ really is:

```
[sh @ balrog] ~ 7 % lsblk -no name,fstype
sda    
├─sda1 ntfs
└─sda2 ntfs
sdb    
├─sdb1 swap
├─sdb2 ext4
├─sdb3 ext4
├─sdb4 
└─sdb5 ext4
sdc    
├─sdc1 swap
├─sdc2 ext4
├─sdc3 ext4
└─sdc4 ext4
sr0    
```

**Comment by shundhammer** [comment]
Commit 8fd45f6c12b78c0a4b4c3758d6d242cf99c33eb6 is a crude hack, but it seems to vastly improve the situation:

Now on NTFS the link count is reset to 1 for all files that claim to have multiple hard links.

Probably this is a bit too extreme; some hard links may be valid after all. I also tried to just decrease the hard link count by 1 for those that have a value greater than 1, but that does not seem to improve anything, and it would be a really arbitrary thing.

So from here on, QDirStat does not take hard links on NTFS into account at all anymore.

**Comment by shundhammer** [comment]
@Kadilov, @ajz3d : Please retry with the latest Git master.

**Comment by Kadilov** [comment]
@shundhammer I used a Windows command-line application `mftrcrd` to investigate MFT records of these files (not that I am accustomed to such things). They have additional DOS-like (12 character max) names for some kind of backwards compatibility.

> When you create a long file name, Windows may also create a short 8.3 form of the name, called the 8.3 alias or short name, and store it on disk also. 

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#short-vs-long-names

I believe this is the reason why they have "2" in the counter - technically, this "short name" is stored very much like a "true", "MS verified" hard link (e.g. notepad.exe). I can provide more details ('mftrcrd' output) if you want, but I think it all boils down to the question: should these short names be considered hard links in the sense assumed by `stat` developers? If the answer is "no", than it means that - if I understand Linux dependencies correctly - `ntfs-3g` has a bug and it should be reported to the mail list here:
https://sourceforge.net/p/ntfs-3g/mailman/

**Comment by shundhammer** [comment]
@Kadilov Thanks; that makes a lot of sense.

In the Linux/Unix world, having the short MS-DOS compatibility 8+3 names as well as the long names would actually justify a hard link count of 2: After all, those are two separate names that both address the exact same file.

But the way this has been handled traditionally for this special short 8+3 / long name on Linux has a history with VFAT filesystems that behave exactly the same, and VFAT does _not_ pretend that they are different hard links; even more so since you only get _one_ of them when enumerating the directory with the `opendir()` / `readdir()` system calls.

So, IMHO ntfs-3g should behave the same and not pretend that there are actually different hard links; only one of them (the longer one) is actually ever visible at any time. You don't see the short name with any tool, starting with simple `ls`.

The only reason that `du` does not exhibit the same problem is that `du` keeps track of what hard links have been seen before and which have not, so the overall sum is correct (at least on the top level, no clue how it accounts for different directories that each have one of the links).

So my guess is that they introduced this some day in ntfs-3g, tested with `du`, and everything was still fine, so damn the consequences. But you are right: IMHO this is clearly a bug in ntfs-3g. They pretend to have several hard links when it's actually only one directory entry, just with two different names.

So for the purposes of QDirStat, AFAICS the only reasonable thing to do is what my hack from a few days ago does: Just disregard any hard links on NTFS. Everything else would be pure guesswork: It could decrease the link count from 2 to 1 if it's 2, it could use hard_link_count / 2 in case there are legitimate hard links; but can we rely on there always being a long and a short name? I don't think so.

And even after a bug report to the ntfs-3g project and a possible fix, how long would it take for that fix to reach end users and to be widely available? How long would it take until most LTS (long-time support) users would have phased out the buggy version? And how would QDirStat behave in the meantime with some broken and some fixed ntfs-3g modules being out there?

So, until further notice, **QDirStat does now disregard all hard links on NTFS**.

**Comment by bobmorane06** [comment]
FYI I'm facing the same issue, QDirStat reports half of the real size on an NTFS drive because all files show 2 links. I'm using it on a PC booting Xubuntu from a USB key (migrating data from an ntfs drive to en ext4 drive) so I won't install the build environment. Do you happen to store nightly / unstable builds somewhere? (so that I use a version with your commit "Crude hack against bogus NTFS hard links (Fixes GitHub issue #88)"?

**Comment by shundhammer** [comment]
@bobmorane06: No, sorry, no nightly/unstable builds for (X)ubuntu. When I think about it, I trigger a rebuild of the current Git version for openSUSE; but I don't have any similar infrastructure for any Ubuntu flavour.

But you can simply build QDirStat on any other machine with roughly the same distro and copy the binary; it's only one single file. This is something that I intend to keep up as long as I can; auxiliary files tend to get in the way.

HTH

**Comment by jpandre** [comment]
I do not understand why you multiply the file sizes by the count
of names.

I have created a file with three names on ext3 :

[linux@optiplex ~]$ /bin/ls -li on-ext3
total 348
1132059 -rw-r--r-- 3 linux linux 112234 Jul 28 08:57 first
1132059 -rw-r--r-- 3 linux linux 112234 Jul 28 08:57 second
1132059 -rw-r--r-- 3 linux linux 112234 Jul 28 08:57 third

The three entries show the same inode number 1132059,
then they are entries to the same file.

[linux@optiplex ~]$ stat on-ext3/first
  File: on-ext3/first
  Size: 112234    	Blocks: 232        IO Block: 4096   regular file
Device: 808h/2056d	Inode: 1132059     Links: 3
Access: (0644/-rw-r--r--)  Uid: (  500/   linux)   Gid: (  500/   linux)
Access: 2020-07-28 08:57:25.888247500 +0200
Modify: 2020-07-28 08:57:25.784448200 +0200
Change: 2020-07-28 11:55:30.275569501 +0200
 Birth: -

[linux@optiplex ~]$ du -s on-ext3
120	on-ext3

du show a total use of 120 1024-bytes blocks, which is consistent
with the space used by the file shown by stat (232 512-bytes
blocks).

Why would you multiply the space used by a file by the number
of names ?
On the contrary, you would have to count names with the same
inode number as a single file.

Now, doing the same on ntfs :

[linux@optiplex linux]$ /bin/ls -li on-ntfs
total 330
112 -rw-r--r-- 4 linux linux 112234 Jul 28 08:57 first-name
112 -rw-r--r-- 4 linux linux 112234 Jul 28 08:57 second-name
112 -rw-r--r-- 4 linux linux 112234 Jul 28 08:57 third-name

The entries have the same inode number 112, so they represent
the same file. However the count of names is 4 because there
also is a short name for the same inode 112 :

[linux@optiplex linux]$ /bin/ls -li on-ntfs/FIRST-~1
112 -rw-r--r-- 4 linux linux 112234 Jul 28 08:57 on-ntfs/FIRST-~1

[linux@optiplex linux]$ stat on-ntfs/first-name
  File: on-ntfs/first-name
  Size: 112234    	Blocks: 220        IO Block: 4096   regular file
Device: 33h/51d	Inode: 112         Links: 4
Access: (0644/-rw-r--r--)  Uid: (  500/   linux)   Gid: (  500/   linux)
Access: 2020-07-28 08:57:25.888247500 +0200
Modify: 2020-07-28 08:57:25.784448200 +0200
Change: 2020-07-28 12:12:19.765835300 +0200
 Birth: -

[linux@optiplex linux]$ du -s on-ntfs
110	on-ntfs

The number of disk 512-byte blocks is 220 in this case, and the
total size shown by du is consistent with a single instance of the
file.

Why would the number of names come into play when computing
the size on disk ?

**Comment by shundhammer** [comment]
I explained that at least half a dozen times already. Please read.

**Comment by Kadilov** [comment]
I've sent a report to `ntfs-3g` and one the developers published a patch in a mailing list. It adds a mount option that forces `ntfs-3g` to calculate a number of hard links instead of relying on the counter stored in a MFT.
https://sourceforge.net/p/ntfs-3g/mailman/ntfs-3g-devel/thread/2dab15d0-8723-b547-e894-5baf5553de46%40wanadoo.fr/#msg37071821

As for QDirStat fix, I was unsure why it worked for me in Ubuntu 20.04 but not in openSUSE Leap 15.2. Looks like it is because `lsblk` can work differently depending on the distribution. From `lsblk` manual:
> The lsblk command reads the sysfs filesystem and udev db to gather information. If the udev db is not available or lsblk is compiled without udev support than it tries to read LABELs, UUIDs and filesystem types from the block  device. In
> this case root permissions are necessary.

"Compiled without udev support" - this might be the case with openSUSE, at least some users think so:
https://bugzilla.opensuse.org/show_bug.cgi?id=1169006
It means empty output from `lsblk -no fstype` without root.
This could be a rare scenario (I've seen the post claiming that 5 other distros do not do that). 
A command that works without root privileges in openSUSE, in case you decide to look into this:
`udevadm info -q all -n /dev/sda1 | grep -i FS_TYPE | cut -d "=" -f2`
Gives me "ntfs" on my dual-boot installation.

**Comment by shundhammer** [comment]
Hm... this seems to be awfully fragile, relying so much on the output of the `udevadm` command, that command being available in the first place, and the command not being castrated for non-privileged users (as tends to happen due to paranoid "security concerns"); not to mention non-Linux systems like all the BSD variants out there (yes, they also have ntfs-3g and `lsblk`).

**Comment by Kadilov** [comment]
I had an impression that dependencies are almost the same, like:
1. Currently, `lsblk` is used and it needs `udev` in all distributions if used without root, according to manual.
2. Calling `udevadm` needs `udev` and `udevadm` itself.

But I do not know anything about how 'udevadm' is handled in distributions.
Alternatives that came to mind:
a.) Leave it as it is, because this is a rare case/known issue,
or
b.) If `lsblk` fails to name a file system, like in openSUSE Leap, check for `fuseblk` partitions and show a "known NTFS issue" warning if `fuseblk` is found, 
or
c.) revert fix to not depend on `udev`, always check for `fuseblk` partitions and show a "known NTFS issue" warning if `fuseblk` is found.

**Comment by shundhammer** [comment]
It's already detected as _fuseblk_, but that doesn't mean that it's NTFS. Strictly speaking, it could be anything.

**Comment by shundhammer** [comment]
@jpandre wrote:
> I do not understand why you multiply the file sizes by the count of names.

I don't know how you might possibly get that idea. To the contrary: QDirStat **divides** the nominal size by the number of hard links, and that is how each entry (each individual hard link) is counted.

This is all explained in great detail here: https://github.com/shundhammer/qdirstat/issues/25

And _ntfs-3g_ is flat-out lying about the number of hard links on NTFS: It counts the old MS-DOS-compatible 12+3 name as another hard link, even though it is not enumerated when reading the directory with `opendir()` / `readdir()`. This is plain wrong.

**Comment by Kadilov** [comment]
I thought about a warning that does not state that NTFS is detected, but only informs that an issue might exist if NTFS partitions are used. Not very elegant, I know. Just an idea.

**Comment by Kadilov** [comment]
Also, two commands can be tried one after another. On every device detection check for `fuseblk`, if found -
use `lsblk`, if failed -
use 'udevadm', if failed -
do nothing. Or maybe ask user:
"QDirStat did not recognize a file system type of one or more partitions. If you are going to scan an NTFS partition, disabling of hard links detection is recommended for better accuracy." Buttons: "Disable (this time only)"/"Cancel".
