### ISSUE TITLE
Automatically mounted BTRFS sub-subvolumes are treated as mountpoints and aren't automatically scanned

### ISSUE THREAD

**Issue by Atemu** [shundhammer/qdirstat#89]
When a btrfs subvolume is automatically mounted because it is a children of another subvolume, Qdirstat treats it as if it was a separate mount and doesn't continue reading it.

Repro: 

1. Mount a BTRFS in `/mnt/mountpoint`
2. `btrfs subvolume create `/mnt/mountpoint/subvolume/`
3. `touch /mnt/mountpoint/subvolume/test`
3. `qdirstat /mnt/mountpoint/`

The file `test` only shows up after telling qdirstat to continue reading from `/mnt/subvolume/`.

I skimmed over #39 but that issue seems to be about separately mounted same-level btrfs subvolumes, not automatically mounted child subvolumes.

**Comment by shundhammer** [comment]
Having said that, I thought about supporting this special case: A Btrfs on removable media that might be auto-mounted by some _udev_ rule, but without subvolumes (probably because nobody bothered to set up _udev_ rules for those subvolumes).

My first thought was "ok, then let's also assume it is a subvolume if it appears as a mount point (i.e. device minor/major of the directory are different than on the parent directory), but it does not appear in `/proc/mounts`, i.e. it shows up as device _unknown_ here".

But that would raise a zillion problems with the most common use case of Btrfs: Using it as a root filesystem and having snapshots. Those snapshots are also just subvolumes; they are just not mounted. Like your subvolume here, they are not automatically scanned, and that is definitely the desired behavior; otherwise disk space accounting would go haywire every single time.

With the CoW (copy-on-write) strategy and reference-counting each disk block separately that Btrfs does, a snapshot showing up in QDirStat would cause complete chaos; there is no way to keep that stuff apart. Suddenly, your 40 GB root filesystem would show to hold about 200 GB worth of data; that would completely defeat the purpose of QDirStat.

Disk space accounting is broken by design in Btrfs. Even Btrfs native tools can't make very much sense of it, and by the time the output of those tools reaches the user, everybody is completely confused.

Just look at a well-used Btrfs with those commands:

- `sudo btrfs filesystem df /mnt/mountpoint`
- `sudo btrfs filesystem du /mnt/mountpoint`
- `sudo btrfs filesystem usage /mnt/mountpoint`

And then try to make sense of the output.

As soon as there are snapshots, there is complete confusion: All the files and directories that were changed between the snapshots appear twice or, with several snapshots, multiple times. It's not even as simple as with hard links; there is no indication in the filesystem with normal syscalls that a file is referenced multiple times.

Btrfs manages to violate just about every single rule that Linux/Unix filesystems are based on. It pretends to be a normal filesystem, but in reality it behaves more like a reference-counting database of disk blocks. Btrfs reports completely bogus values to all kinds of syscalls, in particular those syscalls that tools like `df` and `du` are based on. That's why Btrfs brings all those tools of its own, and even in a surprising number of variations that all do similar, yet slightly different things that are even inconsistent among each other.

**Comment by shundhammer** [comment]
I would support your special case if I had a good idea how to do it; I acknowledge that this is a problem for normal users that just want to use an existing Btrfs on such removable media that get auto-mounted by some _udev_ rule and/or their desktop (KDE, GNOME, Xfce, whatever).

But that has to integrate well with the most important use case which is using Btrfs as a root filesystem and using snapshots as a quick backup. So QDirStat can't simply happily continue scanning if it detects a mount point (i.e. it starts reading a new directory and it detects that its device minor/major number are different than the parent directory), yet it cannot determine what device this new directory is on.

Having to resort to `/proc/mounts` for that was already a kludge; see the explanations at issue #39. The designers of Btrfs in their infinite wisdom decided that one single ioctl was "enough for everybody" (where have we ever heard that before?), i.e. for all Btrfs operations on the syscall level, and since many of them require root privileges, that ioctl is a privileged one; not even basic info calls can be done without root privileges.

This is also broken by design IMHO; there is no good reason why a command like `btrfs subvolume list` would always require root privileges. And that's something that QDirStat would have to call, either by syscall or as an external program.

So going through the indirection of checking `/proc/mounts` is the only thing that QDirStat can do at all to figure out if we are looking at a Btrfs subvolume rather than at a normal mount point; but that requires to actually mount those subvolumes.

So sorry, this looks like _no can do_.

If anybody has a good idea how to do this, feel free to reopen. But I am not very optimistic about that.

**Comment by Atemu** [comment]
Wouldn't it be possible to detect if a subvolume is a snapshot by checking it's `ro` btrfs property?

**Comment by shundhammer** [comment]
That would be with

`sudo btrfs property get /mnt/mount-point ro`

which again would require root privileges, so it's back to square one.
