### ISSUE TITLE
Filter / Show / Hide file types in treemap

### ISSUE THREAD

**Issue by newhoa** [shundhammer/qdirstat#92]
This is just a feature request. When looking through files, sometimes large files obfuscate smaller files visually in the treemap. Or other times I'd just like to focus on cleaning up certain file types.

It would be useful if there was either a filter bar that let you add file types to show, or a menu that showed the MIME Categories (from your settings configuration) and let you check or uncheck either certain categories, or file types within those categories.

I read a few requests on here to ignore certain file types while scanning and that has been rejected. This may be rejected also being somewhat similar, but I am asking not to ignore files when scanning, but simply to filter the treemap results.

Thanks for the consideration and for this great program.

**Comment by shundhammer** [comment]
My first thought about this is that this is counterproductive: The whole purpose of the treemap is to show how large files are relative to each other.

Then there is the problem that you are free to start cleanup actions from both views, from the tree and from the treemap. Those actions might very well affect things that you don't currently see, and you might be sorry for it a short moment later: If you hide some types of files from the view, yet a cleanup deletes them along with those that you do see, you might not be aware of what you are doing. There is real danger of doing real damage.

OTOH both arguments are also true for excluded directories; a recursive cleanup operation that descends into an excluded directory (or into a mounted filesystem that is also not shown by default), the same thing might easily happen.

On the other hand, excluded directories are not very common, and for mounted filesystems you probably don't even have sufficient permissions to do much damage -- unless, of course, you are running QDirStat as root.

So there is this conflict about avoiding damage because of hiding files and a new way of using the view. Can you elaborate a bit more about real world use cases that you have in mind?

Let me think about this. Let me discuss this with some other people. Maybe somebody has a good idea how to bring both aspects together.

**Comment by shundhammer** [comment]
Okay, thanks for the explanations; that makes things a lot clearer.

Now let me think of ways how to do this.

**Comment by shundhammer** [comment]
Some ideas are beginning to form in my mind.

Besides your what you suggested to hide individual large files interactively, using a logarithmic scale might be an option: I.e. each treemap tile would not correspond directly to the size of the underlying item, but to the logarithm of its size, so an exceptionally huge file would no longer completely dwarf everything else. Of course, it would be instantly switchable between the normal linear scale and the logarithmic scale, and maybe different logarithms (log10 / decadic vs. ln / natural; maybe also ld / dual) might be useful. I think I will play a little bit with that to get a feeling just how useful that is.

Stay tuned.

BTW that does not mean that hiding huge files interactively is from the table; a logarithmic treemap is just another approach for very much the use case, and it would require less user interactions.

**Comment by shundhammer** [comment]
Here is a first implementation of logarithmic treemaps:

https://github.com/shundhammer/qdirstat/tree/huha-log-treemap

I experimented with this in different scenarios. This is my home directory with the traditional linear treemap:

![qdirstat-home-dir-linear-treemap](https://user-images.githubusercontent.com/11538225/52500666-deab1980-2bde-11e9-9783-0b695cbc79cf.png)

Switching to a logarithmic treemap (Menu _Treemap_ -> Logarithmic Scale) gives me this:

![qdirstat-home-dir-log-treemap](https://user-images.githubusercontent.com/11538225/52500751-069a7d00-2bdf-11e9-8700-d87c13dc9042.png)

Okay so far; individual files don't dwarf everything else anymore. I think this is what you wanted, right?

So let's go big; let's see my /work directory where I keep my photo collection, a bunch of videos, some virtual machine disks and the files for games like _War Thunder_ and _World of Tanks_; there are some really large files among those.

![qdirstat-work-linear-treemap](https://user-images.githubusercontent.com/11538225/52500896-51b49000-2bdf-11e9-9ad6-3cc05a003ba7.png)

And now switching to the logarithmic treemap:

![qdirstat-work-log-treemap](https://user-images.githubusercontent.com/11538225/52500919-62650600-2bdf-11e9-883b-cc04f7cdb954.png)

Eh - what?

What's wrong here? Some scaling error? I thought I had found something: The minimum tile size for the treemap also needs to be adapted to the logarithmic scale, of course, to avoid filtering out tiles that are supposedly tiny, but in the logarithmic scale they are a lot less tiny. I scaled that value as well, and still it was the same. I explicitly set the value to 1, and it's till the same.

Some logging output later I found that this is perfectly expected: With the logarithmic scale everything is so similar in size that with the sheer number of files in that entire subtree each individual tile just becomes so tiny that it finally disappears.

That's the downside of a logarithmic scale: It is the great equalizer. But the treemap lives by showing differences, and those differences are now gone. It's just one large grey mass.

**Comment by shundhammer** [comment]
If you can (i.e. if you know how to check out a branch and how to build QDirStat from the sources - it's described in the project home README.md), please check out that branch, build it and play around with that logarithmic treemap.

It might help in some situations, and it might be completely counterproductive in others. It is certainly not an option to enable by default; in many cases, it might make the treemap completely useless.

There is still the slight possibility that I overlooked a bug in that new logarithmic scaling, but AFAICS it's really just the effect of scaling down everything to more or less the same size.

Right now it uses the plain `log()` function from the C/C++ standard library. That function uses the natural logarithm (ln(), based on _e_). Using the decadic (base 10) logarithm would just make it worse since it equalizes great numbers even more.

I am not sure how useful that all is. Please experiment.

**Comment by shundhammer** [comment]
Changing `MinTileSize` in `~/.config/QDirStat/QDirstat.conf` to 1 (default: 3) gives me this for the logarithmic treemap in /work:

![qdirstat-work-log-treemap-min-tile-size-1](https://user-images.githubusercontent.com/11538225/52501687-38144800-2be1-11e9-9add-6b18924320cf.png)

This shows some MIME colors to give some hints about what all that tiny stuff is, but at the same time performance really suffers.

**Comment by newhoa** [comment]
I installed the new logarithmic source branch and have played around with it for a short time. That's really impressive that you were able to do something like that so quickly! So these are just my very initial impressions.

Maybe I needed to add some flags when compiling or something, but in this build when I hover my mouse over files in the treemap, it doesn't show me the file name in the status bar like it used to. Maybe I'm misremembering.

I did encounter a problem with the logarithmic scaling treemap. When I scanned my home directory, it did not show tiles for files -- only folders (like the image you posted [here](https://user-images.githubusercontent.com/11538225/52500919-62650600-2bdf-11e9-883b-cc04f7cdb954.png)). Once I zoomed the treemap in a level on certain directories it began to show files. MinTileSize was already set to 3. And even zoomed in on some directories, like my 1.1TB 150,000 file Downloads directory while it did show some files, most of the tiles were folder tiles. And oddly enough some of the folders were incredibly small but showed large tiles. [Here is an example screenshot](https://i.imgur.com/s7GGEE0.png).

Okay, as for the new scale:

I think the logarithmic scale is actually very useful! When I was in certain directories it was more useful in showing clusters and concentrations of files. And you were more easily able to see some of the more relatively small sized files.

I do think, though, that some problems still remain that can't be addressed without filtering.

I navigated to a download directory. Some of the folders were torrents being downloaded, and many padding files were in those directories. So while a lot of room wasn't taken up by the largest files, a lot of the room was now taken up by 1000s of unimportant padding files.

There was another directory that had a lot of files, and there were some large hash text files (200MB). In both linear and logarithmic scales, these files were very small. They were actually larger on the linear scale which kind of surprised me since the directory had a lot of very large files. However, on both scales they were small enough that they were almost impossible to see and select.

The logarithmic scale I am finding very useful. I'm seeing a lot of files that I would have never seen with linear. But sometimes it's important to see those smaller files scaled linearly and compare them among themselves or other specific sets of files. Or to outright just hide certain sets of files. And there is no way to do either of those things. In some directories, I either see smaller files in logarithmic and don't get a sense of really how relatively large they are (and even then they might be too small to click or see individually), or I use linear and don't see them at all.

And there is still a problem of a finite amount of pixel space to show a progressively increasing amount of files and types.

I can't personally think of a way around these things without filtering. And while the logarithmic scale is nice and useful and helpful and a great idea, I hope filtering will not be totally off the table at some point in the future.

I'm impressed that you came up with this idea so quickly and implemented it so fast. Thanks again for considering all of this and I will continue to play with and test it out.

**Comment by shundhammer** [comment]
Okay, thanks for the feedback!

> Maybe I needed to add some flags when compiling or something, but in this build when I hover my mouse over files in the treemap, it doesn't show me the file name in the status bar like it used to. Maybe I'm misremembering.

This is a configuration parameter that is now (since V1.5) _false_ by default, but it is now easily accessible via the new _General_ tab in the configuration dialog.

> I did encounter a problem with the logarithmic scaling treemap. When I scanned my home directory, it did not show tiles for files -- only folders (like the image you posted [here](https://user-images.githubusercontent.com/11538225/52500919-62650600-2bdf-11e9-883b-cc04f7cdb954.png)). Once I zoomed the treemap in a level on certain directories it began to show files.

This is expected if there are many files: Since the logarithmic scale drastically downsizes the larger tiles, they are now much more equal in size (i.e. in area), so entire directories full of many files tend to disappear because they are filtered out by _MinTileSize_.

> MinTileSize was already set to 3.

Try a smaller size. This is exactly the problem I described in the logarithmic treemap of my `/work` directory.

**Comment by shundhammer** [comment]
I am wondering if tweaking the treemap is indeed the right approach for your use case.

Did you try the _File Type Statistics_ window? It might be more useful for you. It is a completely different approach, but it might actually be closer to what you want to do.

You know that you can start this for the entire directory tree that you scanned, or only for a subtree. From the _File Type Statistics_ window, you can open one of the MIME categories and then select any of the filename extensions. A double-click (or a the _Locate_ button) will open a window showing you paths where you have files with that extension. Clicking on any of those paths will locate and open that directory in the main window and select the matching files in that directory.

![File Size Statistics](https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-locating-file-types.png)

The treemap's strength is really identifying large files buried deep down in a directory hierarchy. As a byproduct (but no more than that), it can also give some first impression about known MIME categories and roughly how much disk space they occupy all over the scanned directory tree.

But it's always only roughly as the logarithmic treemap shows: Tiny files tend to disappear, and with them their MIME catagory color also disappears. So if you have a lot of those tiny files that all together still consume a lot of your disk space, the treemap might not tell you that because so many of them are just not visualized in the treemap view.

This is a compromise between utility and performance; hence the _MinTileSize_ parameter. The reasoning was that all that little stuff is of little consequence in the ~~grand scheme of things~~ treemap as it was intended to be used.

**Comment by shundhammer** [comment]
Going off on a tangent, maybe it's time to give directories in the treemap a different color if they are largely dominated by any single MIME category.

Right now all directories have that grey-blueish gradient; maybe a directory that consists of 95% (90%? 80%?) JPG files should also get the JPG color. I am not sure if that should affect only directories that don't have any visible child tiles or all directories in general, but this might be worth a try.

**Comment by naught101** [comment]
Personally I would prefer the ability to quickly exclude/hide files/directories completely (from the list and the tree map).

For example, I have about 245GB in my home dir, and 200GB of that is music, and 33 is a directory of large data files, none of which I want to remove. But I would like to be able to see what large folders exist in home, so that I can back up without wasting space. I want to look at the total of everything except those two directories. this is a new computer, and the problem will get worse as more cache files are created. I have often found myself in similar situations in other directories, too.

It's worth pointing out that none of the alternative software (k4dirstat, filelight, ncdu) does this, so this would make qdirstat substantially more useful.

I think "hiding" would be more useful than "excluding", and it would be nice if there was a "show hidden" toggle, so that hidden files/directories could be unhidden.

**Comment by shundhammer** [comment]
I know that it's not quite the same, but you are aware that you can zoom in the treemap to any directory that you want to see in more details? (Mouse wheel, menu, context menu, toolbar buttons).

Also, the treemap is really mostly useful to spot large files, not so much on the directory level. The cushion rendering does give some hints what belongs together, but grouping files into directory is not exactly a strong point of this way of rendering data. For finding out large directories, the tree view is much more useful.

**Comment by shundhammer** [comment]
I talked about this with a good friend of mine who is also involved in this project.

I think I understand your intentions, but so far nobody could come up with an idea how to do this without turning it into a user interface nightmare.

What I would expect from such a feature are those functions (which would be available from the context menu):

- Ignore this file (the currently selected one).
- Ignore this type of file -- if a, say, JPG file is selected, ignore all *.jpg files

Then those ignored files would disappear from the treemap, and they would be greyed out from the tree (or maybe moved into another pseudo directory in the tree named `<Ignored>`?).

But of course the files would still be there on disk. They would still consume disk space, and they would still be affected by certain cleanup actions . This is _one_ problem.

Another problem is to make the user aware that they are still there. I understand that your intention is to make the ignored file(s) no longer dominate the treemap. So, they should of course not consume so much screen real estate anymore; but they should still be visible in some way.

Very much like screen estate on your computer desktop, that could be displayed by some kind of icon -- either one as a marker that _something_ is there that is just currently not shown, or, probably much better to display in the treemap (and fitting into the treemap layout algorithm) that marker could be a thin strip on the narrow side of that directory's treemap tile.

But then the problems continue: The fundamental rule of that kind of treemap is that the area of a treemap tile directly corresponds to the size of the file that it represents.

But when you ignore one or more files, at first the area of that directory' treemap tile would remain the same; only its content would be redistributed among the other files in that directory _without_ the ignored files. After all, that was the whole point of that ignore feature.

But now picture this: You just ignored that huge 4 GB ISO in your downloads directory, and the treemap for the directory is rebuilt to show the remaining files, e.g., those 4 PDFs of about 10 MB each that are also in that directory.

Since the whole downloads directory had been allocated the screen space for a bit over 4 GB, those PDFs would now be shown in the same space, i.e. they would look just as large as a 1 GB file each. That would grossly distort the dimensions in that treemap, effectively making it very much useless.

So, that wouldn't do. After ignoring the ISO, the entire treemap would have to be rebuilt. For that, the treemap widget would no longer use the _totalSize()_ of each directory, but a newly introduced _visualSize()_ that would subtract the accumulated sizes of the ignored files in that subtree.

Rebuilding the treemap, however, means that the directory that you were just working on might end up at a very different spot in the treemap, throwing the user completely off track. It's not only the screen flicker, it's complete disorientation.

This is where the user interface nightmare that I mentioned earlier on starts. Or, rather, where it most drastically manifests itself.

**Comment by shundhammer** [comment]
This _might_ work (well, kind of, anyway) for the current directory if you zoomed the treemap in all the way (mouse wheel); then ignoring a file or all files of a certain type would not also have an effect on neighboring directories.

But in that scenario, is this really an issue? When you already drilled down to that level, how hard is it to just visually ignore that one big blob that gets in the way? If the rest of the directory is so much dwarfed by that one thing and disappears into clutter (the _misc_ area of each directory treemap area where no individual files are rendered anymore, just a grey gradient), should you really be concerned about that small stuff? Or, to put it another way, is the treemap really helpful there at all?

The treemap's strength is to easily point out big blobs (even if they are hiding deep down in a directory hierarchy), and the way QDirStat does it, also to give you some impression with colors what type of files are there.

But if your intention is to meticulously go through each file in turn and make a decision if it is legit (i.e. you need it) or it's cruft (i.e. you should get rid of it), the tree widget is the much better tool.

**Comment by naught101** [comment]
> they should of course not consume so much screen real estate anymore; but they should still be visible in some way.

There is a status bar already, how about a bit warning in **bold** and red, that mentions that there are files not displayed in the tree map?

> The fundamental rule of that kind of treemap is that the area of a treemap tile directly corresponds to the size of the file that it represents.

Technically this is not quite true. A tile size corresponds to the size of the object it represents (files) _relative to all other objects included in the tree map_. It is somewhat arbitrary (although a very sensible default) to decide that the set of all other objects are the files included in one directory and all it's subdirectories. The tree already excludes other files on disk (e.g. files above the parent directory I chose).

> You just ignored that huge 4 GB ISO in your downloads directory, and the treemap for the directory is rebuilt to show the remaining files, e.g., those 4 PDFs of about 10 MB each that are also in that directory

Yes, this is exactly the behaviour that would be useful (albeit a simple example), when I'm looking for large files to delete, but I have a subset of even larger files that I know that I don't want to delete. When we're talking about terrabyte disks and I'm wanting to save gigabytes, but I have hundreds of gigs of movies and music that I don't want to delete, it does become a problem. I can't simply enter other directories to check inside them, because there are too many. Also, I'm not necessarily looking for individual files to delete, but also things like cache directories in my home dir, that have thousands of small files.

> After ignoring the ISO, the entire treemap would have to be rebuilt. For that, the treemap widget would no longer use the totalSize() of each directory, but a newly introduced visualSize() that would subtract the accumulated sizes of the ignored files in that subtree.

Yes, speed could be an issue. I admit I haven't looked at your code, so I don't know how it is handled. I was imagining it like this:

- Each tile/file has it's real disk size stored, and it's size relative to the parent directory, and it's visual size.
- Each directory has it's size relative to it's parent directory stored, as well as it's total visual size (excluding hidden files).
- When a file/directory is hidden, walk up the branch, updating all of the parent directory's relative sizes. Then walk down the (whole) tree, updating the visual sizes.

I don't know how fast that can be in practice. But the tree builds relatively fast on my machine anyway, even on large directories, and I'm only really likely to exclude a few large files/directories.

> Rebuilding the treemap, however, means that the directory that you were just working on might end up at a very different spot in the treemap, throwing the user completely off track. It's not only the screen flicker, it's complete disorientation

Yes, that might be a bit annoying. But if I exclude the largest directories, then I'm still going to end up with the biggest things in the top left, so it's still going to make sense.

**Comment by shundhammer** [comment]
I just realized that with the restrictions already mentioned, this feature is already there.

All you need is a custom cleanup action that does nothing and has a refresh policy of "assume deleted". For better usability, it is advisable to add a hotkey.

_Caveat:_ You need to specify a command for this to work, but that command can easily do nothing; like a simple `echo %p`.

To add a hotkey, you need to edit the config file manually; QDirStat does support hotkeys for cleanups, but there is no GUI support to configure that.

The resulting section in `~/.config/QDirStat/QDirStat-cleanup.conf` should look like that:

```
[Cleanup_99]
Active=true
AskForConfirmation=false
Command=echo %p
Hotkey=F8
OutputWindowAutoClose=false
OutputWindowPolicy=ShowNever
Recurse=false
RefreshPolicy=AssumeDeleted
Title=Ignore this item
WorksForDir=true
WorksForDotEntry=false
WorksForFile=true
```

The number (`_99`) will automatically be adjusted the next time you start QDirStat.

To use this, start QDirStat and select an item (a file or an entire directory) in the tree or in the treemap and use either the context menu ("_Ignore this item_") or the `F8` key; voila, the item is gone.

Of course it is only gone from the treemap and from the tree view; it is still on disk. The next time you restart QDirStat or you refresh the tree, it will be back again.

_**CAUTION**: Be really, really careful with clean up actions after you ignored items this way. Any cleanup action that affects more than one file (i.e. a complete directory or many files via wildcards) might easily also affect an item that you ignored._

**Comment by naught101** [comment]
Ah, that is quite cool! I will give it a try soon. Thank you :)

**Comment by naught101** [comment]
Finally got around to trying this, and it works beautifully! Thank you!

**Comment by stdedos** [comment]
Using the ignore action leaves the list view unmodified (if sorted by % size).

Is that intentional?

**Comment by shundhammer** [comment]
> Using the ignore action leaves the list view unmodified (if sorted by % size).

What do you mean: "Leaves it unmodified"? The selected item(s) should be removed from both views. That works fine for me.

**Comment by stdedos** [comment]
They are removed from both views, but, the list view is not re-sorted (up to the root level).
