### ISSUE TITLE
endless recursion on $'\uFEFF' filename

### ISSUE THREAD

**Issue by phiresky** [shundhammer/qdirstat#99]
keeps reading forever and ever:

![image](https://user-images.githubusercontent.com/2303841/56851928-f740eb00-6914-11e9-884b-4fdaa186df71.png)

reproduce:

```
touch $'\uFEFF'
qdirstat .
```

found this because I just tried to create weird filenames to see if qdirstat-cache-writer fails on unicode stuff:

cat [blns.txt](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt); while read line; do touch -- "$line"; done

**Comment by shundhammer** [comment]
Hm... weird. Okay, I'll check what's going on here.

Wikipedia says that's the _byte order mark_ character in Unicode.

**Comment by shundhammer** [comment]
I can reproduce this with QDirStat 1.5, but with git master this does not happen.

![weird-file-1 5](https://user-images.githubusercontent.com/11538225/57183447-73a37300-6ead-11e9-89ec-0ded63e202f3.png)

_QDirStat 1.5: Endless recursion while reading directories_

![weird-file](https://user-images.githubusercontent.com/11538225/57183453-85851600-6ead-11e9-8e51-0fd6b434b930.png)

_QDirStat from git master (7b8f90e9021e9be): Just the wrong type detected (?!)_

Why it detects that file as a directory is beyond me. But it's no longer that much of a problem.

What has changed between QDirStat 1.5? Well... a lot. In directory reading, just about everything; I made it much faster (see the _News_ section on the project home page), and in that process, I first rearranged the code quite a bit to make it more modular (it's now no longer that huuuge `startReading()` function), then I started sorting the directory entries by i-no and using `fstatat()` instead of `lstat()`.

One of those changes seems to have improved the situation of this particular problem.

It's still a minor defect because it detects the wrong object type: Directory (which can't be read, thus the lock in the icon) instead of plain file. But it's a minor problem, and mostly cosmetic.

**Comment by shundhammer** [comment]
Hm... I think I can explain the "locked" icon: After the `fstatat()` call there is the check if it's a directory or not:

https://github.com/shundhammer/qdirstat/blob/master/src/DirReadJob.cpp#L222

```C++
            if ( fstatat( dirFd, entryName.toUtf8(), &statInfo, flags ) == 0 )	// OK?
            {
                if ( S_ISDIR( statInfo.st_mode ) )	// directory child?
                {
                    DirInfo *subDir = new DirInfo( entryName, &statInfo, _tree, _dir );
                    CHECK_NEW( subDir );

                    processSubDir( entryName, subDir );

                }
                else  // non-directory child
                {
```

If it gets into the _directory_ branch, it will get into `processSubDir()` where it will create a new read job:

https://github.com/shundhammer/qdirstat/blob/master/src/DirReadJob.cpp#L320

When that read job is executed, it will check for read and execute permissions:

https://github.com/shundhammer/qdirstat/blob/master/src/DirReadJob.cpp#L171

```C++
    if ( access( _dirName.toUtf8(), X_OK | R_OK ) != 0 )
    {
	ok = false;
	logWarning() << "No permission to read directory " << _dirName << endl;
	finishReading( _dir, DirError );
    }
```

And this fails, so it doesn't even get to the `opendir()`...`readdir()` part. And a directory that could not be read gets the "locked folder" icon.

**Comment by shundhammer** [comment]
It gets weirder.

In `gdb` it looks like the shell created this as a name for that file:

```
(gdb) p entry->d_name
$7 = "﻿\000\b", '\000' <repeats 250 times>
```

Amazing that the kernel even accepts this.

What happens when this goes through `QString::fromUtf8()` and back through `QString::toUtf8()` is anybody's guess; but anyway, either the `fromUtf8()` part already fails and the content is broken then already, or it gets broken on the way back; one way or the other, the kernel won't accept that `entry->d_name` that it gave me with `readdir()` to the subsequent `fstatat()` call.

It might be the assumption that these days file names should all be UTF-8, and that sequence might just not be valid UTF-8. I don't know.

One way or the other, if anybody really uses such file names that's asking for trouble. And if the trouble is no worse than getting the wrong icon, that's good enough for me. :smiley: .

**Comment by shundhammer** [comment]
The improvement from endless recursion to just getting the wrong type and thus the wrong icon might indeed be caused by using `fstatat()` instead of `lstat()`: Where `lstat()` took the complete path to that file, `fstatat()` now only takes the name and the file descriptor of the open directory. So there are less problematic steps involved when constructing the complete path from the directory's path plus the entry's name: The resulting path might just be the same over and over again.

`/tmp/weirdstuff/ + $garbage` -> `/tmp/weirdstuff//`

I.e. it just adds more slashes at the end which the next syscalls will happily cut away, so it will land in the same directory where it came from, and there will be no end condition.

That sounds plausible IMHO.
